var artists = TAFFY([
	{"country":"South Korea","agency":"BPM Entertainment","counter2":9,"city":"Cheongju","counter1":30,"zodiac":"Gemini","chineseZodiac":"Tiger","groupNameUpper":"VIVIZ","positions":"Main Dancer, Vocalist","counter":39,"nameUpper":"SINB","zodiacId":3,"birthDate":19980603,"realName":"Hwang Eunbi","idolId":1,"groupName":"VIVIZ","chineseZodiacId":3,"fandom":"Na.V","imageFileName":"SINB_VIVIZ","name":"SinB","age":24}
	,{"country":"South Korea","agency":"Source Music","counter2":5,"city":"Seoul","counter1":2,"zodiac":"Sagittarius","chineseZodiac":"Pig","groupNameUpper":"GFRIEND","positions":"Leader, Vocalist, Visual","counter":7,"nameUpper":"SOWON","zodiacId":9,"birthDate":19951207,"realName":"Kim Sojung","idolId":2,"groupName":"Gfriend","chineseZodiacId":12,"fandom":"BUDDY","imageFileName":"SOWON_GFRIEND","name":"Sowon","age":26}
	,{"country":"South Korea","agency":"Dreamcatcher Company","counter2":3,"city":"Daejeon","counter1":8,"zodiac":"Taurus","chineseZodiac":"Dog","groupNameUpper":"DREAMCATCHER","positions":"Leader, Lead Vocalist, Lead Dancer, Visual","counter":11,"nameUpper":"JIU","zodiacId":2,"birthDate":19940517,"realName":"Kim Minji","idolId":3,"groupName":"Dreamcatcher","chineseZodiacId":11,"fandom":"InSomnia","imageFileName":"JIU_DREAMCATCHER","name":"Jiu","age":28}
	,{"country":"South Korea","agency":"WAKEONE and Swing Entertainment","counter2":15,"city":"Seoul","counter1":20,"zodiac":"Pisces","chineseZodiac":"Goat","groupNameUpper":"KEP1ER","positions":"(none)","counter":35,"nameUpper":"DAYEON","zodiacId":12,"birthDate":20030302,"realName":"Kim Dayeon","idolId":4,"groupName":"Kep1er","chineseZodiacId":8,"fandom":"Kep1ian","imageFileName":"DAYEON_KEP1ER","name":"Dayeon","age":19}
	,{"country":"South Korea","agency":"BlockBerryCreative","counter2":6,"city":"Bundang-gu","counter1":14,"zodiac":"Libra","chineseZodiac":"Dragon","groupNameUpper":"LOONA","positions":"Dancer, Vocalist, Rapper, Visual, Center","counter":20,"nameUpper":"HEEJIN","zodiacId":7,"birthDate":20001019,"realName":"Jeon Heejin","idolId":5,"groupName":"LOONA","chineseZodiacId":5,"fandom":"Orbit","imageFileName":"HEEJIN_LOONA","name":"Heejin","age":21}
	,{"country":"South Korea","agency":"RBW","counter2":2,"city":"Busan","counter1":20,"zodiac":"Sagittarius","chineseZodiac":"Horse","groupNameUpper":"PURPLE KISS","positions":"Main Vocalist, Lead Dancer, Rapper","counter":22,"nameUpper":"CHAEIN","zodiacId":9,"birthDate":20021205,"realName":"Lee Chaeyoung","idolId":6,"groupName":"Purple Kiss","chineseZodiacId":7,"fandom":"PLORY","imageFileName":"CHAEIN_PURPLEKISS","name":"Chaein","age":19}
	,{"country":"South Korea","agency":"iMe Entertainment","counter2":5,"city":"Seoul","counter1":6,"zodiac":"Virgo","chineseZodiac":"Snake","groupNameUpper":"DREAM NOTE","positions":"Main Rapper, Main Dancer, Vocalist, Center, Face of the Group","counter":11,"nameUpper":"SUMIN","zodiacId":6,"birthDate":20010907,"realName":"Park Sumin","idolId":7,"groupName":"Dream Note","chineseZodiacId":6,"fandom":"Page","imageFileName":"SUMIN_DREAMNOTE","name":"Sumin","age":21}
	,{"country":"South Korea","agency":"High Up Entertainment","counter2":2,"city":"Daejeon/Chungcheong","counter1":9,"zodiac":"Sagittarius","chineseZodiac":"Monkey","groupNameUpper":"STAYC","positions":"Vocalist, Rapper, Maknae","counter":11,"nameUpper":"J","zodiacId":9,"birthDate":20041209,"realName":"Jang Yeeun","idolId":8,"groupName":"Stayc","chineseZodiacId":9,"fandom":"SWITH","imageFileName":"J_STAYC","name":"J","age":17}
	,{"country":"South Korea","agency":"WAKEONE and Swing Entertainment","counter2":0,"city":"Uijeongbu/Gyeonggi-do","counter1":5,"zodiac":"Capricorn","chineseZodiac":"Monkey","groupNameUpper":"KEP1ER","positions":"(none)","counter":5,"nameUpper":"YOUNGEUN","zodiacId":10,"birthDate":20041227,"realName":"Seo Youngeun","idolId":9,"groupName":"Kep1er","chineseZodiacId":9,"fandom":"Kep1ian","imageFileName":"YOUNGEUN_KEP1ER","name":"Youngeun","age":17}
	,{"country":"South Korea","agency":"JYP Entertainment","counter2":1,"city":"Guti/Gyeonggi-do","counter1":0,"zodiac":"Aquarius","chineseZodiac":"Ox","groupNameUpper":"TWICE","positions":"Leader, Main Vocalist","counter":1,"nameUpper":"JIHYO","zodiacId":11,"birthDate":19970201,"realName":"Park Jihyo","idolId":10,"groupName":"Twice","chineseZodiacId":2,"fandom":"ONCE","imageFileName":"JIHYO_TWICE","name":"Jihyo","age":25}
	,{"country":"South Korea","agency":"Yuehua Entertainment","counter2":0,"city":"Gwonseon-gu/Suwon/Gyeonggi-do","counter1":3,"zodiac":"Cancer","chineseZodiac":"Dragon","groupNameUpper":"EVERGLOW","positions":"Lead Rapper, Sub Vocalist","counter":3,"nameUpper":"AISHA","zodiacId":4,"birthDate":20000721,"realName":"Heo Yoorim","idolId":11,"groupName":"Everglow","chineseZodiacId":5,"fandom":"For Ever","imageFileName":"AISHA_EVERGLOW","name":"Aisha","age":22}
	,{"country":"South Korea","agency":"Pledis Entertainment","counter2":1,"city":"Boseong-gun/South Jeolla","counter1":3,"zodiac":"Aries","chineseZodiac":"Goat","groupNameUpper":"FROMIS_9","positions":"Vocalist, Maknae","counter":4,"nameUpper":"JIHEON","zodiacId":1,"birthDate":20030417,"realName":"Baek Jiheon","idolId":12,"groupName":"fromis_9","chineseZodiacId":8,"fandom":"Flover","imageFileName":"JIHEON_FROMIS9","name":"Jiheon","age":19}
	,{"country":"South Korea","agency":"High Up Entertainment","counter2":3,"city":"Seoul","counter1":9,"zodiac":"Leo","chineseZodiac":"Snake","groupNameUpper":"STAYC","positions":"Main Vocalist","counter":12,"nameUpper":"SIEUN","zodiacId":5,"birthDate":20010801,"realName":"Park Sieun","idolId":13,"groupName":"Stayc","chineseZodiacId":6,"fandom":"SWITH","imageFileName":"SIEUN_STAYC","name":"Sieun","age":21}
	,{"country":"South Korea","agency":"iMe Entertainment","counter2":2,"city":"Incheon","counter1":6,"zodiac":"Scorpius","chineseZodiac":"Dragon","groupNameUpper":"DREAM NOTE","positions":"Main Vocalist, Rapper","counter":8,"nameUpper":"MISO","zodiacId":8,"birthDate":20001025,"realName":"Jeon Jimin","idolId":14,"groupName":"Dream Note","chineseZodiacId":5,"fandom":"Page","imageFileName":"MISO_DREAMNOTE","name":"Miso","age":21}
	,{"country":"South Korea","agency":"WM Entertainment","counter2":10,"city":"Busan/South Gyeongnam","counter1":13,"zodiac":"Gemini","chineseZodiac":"Rabbit","groupNameUpper":"OH MY GIRL","positions":"Lead Dancer, Sub Vocalist, Maknae","counter":23,"nameUpper":"ARIN","zodiacId":3,"birthDate":19990618,"realName":"Choi Yewon","idolId":15,"groupName":"Oh My Girl","chineseZodiacId":4,"fandom":"Miracle","imageFileName":"ARIN_OHMYGIRL","name":"Arin","age":23}
	,{"country":"South Korea","agency":"J9 Entertainment","counter2":1,"city":"Busan","counter1":1,"zodiac":"Aries","chineseZodiac":"Rabbit","groupNameUpper":"CIGNATURE","positions":"Vocalist, Center, Face of the Group","counter":2,"nameUpper":"JEEWON","zodiacId":1,"birthDate":19990401,"realName":"Kim jiwon","idolId":16,"groupName":"cignature","chineseZodiacId":4,"fandom":"signfan","imageFileName":"JEEWON_CIGNATURE","name":"Jeewon","age":23}
	,{"country":"South Korea","agency":"TR Entertainment","counter2":16,"city":"North Jeolla","counter1":11,"zodiac":"Gemini","chineseZodiac":"Monkey","groupNameUpper":"TRI.BE","positions":"Main Rapper, Main Dancer, Lead Vocalist","counter":27,"nameUpper":"HYUNBIN","zodiacId":3,"birthDate":20040526,"realName":"Kim Hyunbin","idolId":17,"groupName":"TRI.BE","chineseZodiacId":9,"fandom":"TRUE","imageFileName":"HYUNBIN_TRIBE","name":"Hyunbin","age":18}
	,{"country":"South Korea","agency":"IST Entertainment","counter2":8,"city":"Gwangju/Jeolla-do","counter1":22,"zodiac":"Scorpius","chineseZodiac":"Horse","groupNameUpper":"WEEEKLY","positions":"Main Dancer, Lead Vocalist, Center","counter":30,"nameUpper":"SOEUN","zodiacId":8,"birthDate":20021026,"realName":"Park Soeun","idolId":18,"groupName":"Weeekly","chineseZodiacId":7,"fandom":"Daileee","imageFileName":"SOEUN_WEEEKLY","name":"Soeun","age":19}
	,{"country":"South Korea","agency":"WM Entertainment","counter2":0,"city":"Seoul","counter1":5,"zodiac":"Virgo","chineseZodiac":"Pig","groupNameUpper":"OH MY GIRL","positions":"Main Dancer, Lead Vocalist, Face of the Group","counter":5,"nameUpper":"YOOA","zodiacId":6,"birthDate":19950917,"realName":"Yoo Shiah","idolId":19,"groupName":"Oh My Girl","chineseZodiacId":12,"fandom":"Miracle","imageFileName":"YOOA_OHMYGIRL","name":"Yooa","age":27}
	,{"country":"South Korea","agency":"IST Entertainment","counter2":6,"city":"Anyang/Gyeonggi-do","counter1":3,"zodiac":"Cancer","chineseZodiac":"Monkey","groupNameUpper":"WEEEKLY","positions":"Lead Vocalist, Visual, Center","counter":9,"nameUpper":"JIHAN","zodiacId":4,"birthDate":20040712,"realName":"Han Jihyo","idolId":20,"groupName":"Weeekly","chineseZodiacId":9,"fandom":"Daileee","imageFileName":"JIHAN_WEEEKLY","name":"Jihan","age":18}
	,{"country":"South Korea","agency":"Starship Entertainment","counter2":18,"city":"Seoul","counter1":24,"zodiac":"Virgo","chineseZodiac":"Monkey","groupNameUpper":"IVE","positions":"Vocalist, Visual","counter":42,"nameUpper":"WONYOUNG","zodiacId":6,"birthDate":20040831,"realName":"Jang Wongyoung","idolId":21,"groupName":"IVE","chineseZodiacId":9,"fandom":"DIVE","imageFileName":"WONYOUNG_IVE","name":"Wonyoung","age":18}
	,{"country":"Japan","agency":"TR Entertainment","counter2":1,"city":"Tokyo","counter1":1,"zodiac":"Aries","chineseZodiac":"Dog","groupNameUpper":"TRI.BE","positions":"Main Dancer, Sub Vocalist, Maknae","counter":2,"nameUpper":"MIRE","zodiacId":1,"birthDate":20060326,"realName":"Aoyagi Sumire","idolId":22,"groupName":"TRI.BE","chineseZodiacId":11,"fandom":"TRUE","imageFileName":"MIRE_TRIBE","name":"Mire","age":16}
	,{"country":"China","agency":"SM Entertainment","counter2":1,"city":"Harbin/Heilongjiang","counter1":2,"zodiac":"Scorpius","chineseZodiac":"Horse","groupNameUpper":"AESPA","positions":"Main Vocalist, Maknae","counter":3,"nameUpper":"NING NING","zodiacId":8,"birthDate":20021023,"realName":"Ning Yizhuo","idolId":23,"groupName":"aespa","chineseZodiacId":7,"fandom":"MY","imageFileName":"NINGNING_AESPA","name":"Ning Ning","age":19}
	,{"country":"South Korea","agency":"High Up Entertainment","counter2":19,"city":"Busan","counter1":19,"zodiac":"Aquarius","chineseZodiac":"Horse","groupNameUpper":"STAYC","positions":"Lead Vocalist","counter":38,"nameUpper":"ISA","zodiacId":11,"birthDate":20020123,"realName":"Lee Chaeyoung","idolId":24,"groupName":"Stayc","chineseZodiacId":7,"fandom":"SWITH","imageFileName":"ISA_STAYC","name":"ISA","age":20}
	,{"country":"South Korea","agency":"WM Entertainment","counter2":4,"city":"Anyang/Gyeonggi-do","counter1":9,"zodiac":"Leo","chineseZodiac":"Dog","groupNameUpper":"OH MY GIRL","positions":"Leader, Main Vocalist","counter":13,"nameUpper":"HYOJUNG","zodiacId":5,"birthDate":19940728,"realName":"Choi Hyojung","idolId":25,"groupName":"Oh My Girl","chineseZodiacId":11,"fandom":"Miracle","imageFileName":"HYOJUNG_OHMYGIRL","name":"Hyojung","age":28}
	,{"country":"South Korea","agency":"Starship Entertainment","counter2":3,"city":"Seogwipo/Jeju-do","counter1":2,"zodiac":"Scorpius","chineseZodiac":"Monkey","groupNameUpper":"IVE","positions":"Main Vocalist","counter":5,"nameUpper":"LIZ","zodiacId":8,"birthDate":20041121,"realName":"Kim Jiwon","idolId":26,"groupName":"IVE","chineseZodiacId":9,"fandom":"DIVE","imageFileName":"LIZ_IVE","name":"Liz","age":17}
	,{"country":"South Korea","agency":"NV Entertainment","counter2":0,"city":"Osan/Gyeonggi-do","counter1":2,"zodiac":"Leo","chineseZodiac":"Monkey","groupNameUpper":"WOO!AH!","positions":"Main Vocalist, Lead Dancer, Maknae","counter":2,"nameUpper":"MINSEO","zodiacId":5,"birthDate":20040812,"realName":"Kim Minseo","idolId":27,"groupName":"woo!ah!","chineseZodiacId":9,"fandom":"wow!","imageFileName":"MINSEO_WOOAH","name":"Minseo","age":18}
	,{"country":"South Korea","agency":"BlockBerryCreative","counter2":3,"city":"Jeonju/North Jeolla","counter1":4,"zodiac":"Scorpius","chineseZodiac":"Dragon","groupNameUpper":"LOONA","positions":"Dancer, Vocalist, Rapper, Visual","counter":7,"nameUpper":"HYUNJIN","zodiacId":8,"birthDate":20001115,"realName":"Kim Hyunjin","idolId":28,"groupName":"LOONA","chineseZodiacId":5,"fandom":"Orbit","imageFileName":"HYUNJIN_LOONA","name":"Hyunjin","age":21}
	,{"country":"South Korea","agency":"High Up Entertainment","counter2":1,"city":"Gwanju/Jeolla-do","counter1":15,"zodiac":"Aries","chineseZodiac":"Monkey","groupNameUpper":"STAYC","positions":"Lead Vocalist","counter":16,"nameUpper":"YOON","zodiacId":1,"birthDate":20040414,"realName":"Shim Jayun","idolId":29,"groupName":"Stayc","chineseZodiacId":9,"fandom":"SWITH","imageFileName":"YOON_STAYC","name":"Yoon","age":18}
	,{"country":"China","agency":"Yuehua Entertainment","counter2":3,"city":"Hangzhou/Zhejiang","counter1":4,"zodiac":"Capricorn","chineseZodiac":"Dragon","groupNameUpper":"EVERGLOW","positions":"Lead Dancer, Sub Vocalist, Sub Rapper, Visual, Center, Face of the Group, Maknae","counter":7,"nameUpper":"YIREN","zodiacId":10,"birthDate":20001229,"realName":"Wang Yiren","idolId":30,"groupName":"Everglow","chineseZodiacId":5,"fandom":"For Ever","imageFileName":"YIREN_EVERGLOW","name":"Yiren","age":21}
	,{"country":"South Korea","agency":"Starship Entertainment","counter2":1,"city":"Gapyeong/Gyeonggi-do","counter1":7,"zodiac":"Pisces","chineseZodiac":"Pig","groupNameUpper":"IVE","positions":"Vocalist, Visual, Maknae","counter":8,"nameUpper":"LEESEO","zodiacId":12,"birthDate":20070221,"realName":"Lee Hyunseo","idolId":31,"groupName":"IVE","chineseZodiacId":12,"fandom":"DIVE","imageFileName":"LEESEO_IVE","name":"Leeseo","age":15}
	,{"country":"South Korea","agency":"BPM Entertainment","counter2":3,"city":"Incheon","counter1":7,"zodiac":"Leo","chineseZodiac":"Tiger","groupNameUpper":"VIVIZ","positions":"Lead Dancer, Vocalist, Maknae","counter":10,"nameUpper":"UMJI","zodiacId":5,"birthDate":19980819,"realName":"Kim Yewon","idolId":32,"groupName":"VIVIZ","chineseZodiacId":3,"fandom":"Na.V","imageFileName":"UMJI_VIVIZ","name":"Umji","age":24}
	,{"country":"South Korea","agency":"Yuehua Entertainment","counter2":0,"city":"Bundang-gu/Seongnam/Gyeonggi-do","counter1":3,"zodiac":"Leo","chineseZodiac":"Rabbit","groupNameUpper":"EVERGLOW","positions":"Leader, Lead Vocalist, Visual, Face of the Group","counter":3,"nameUpper":"SIHYEON","zodiacId":5,"birthDate":19990805,"realName":"Kim Sihyeon","idolId":33,"groupName":"Everglow","chineseZodiacId":4,"fandom":"For Ever","imageFileName":"SIHYEON_EVERGLOW","name":"Sihyeon","age":23}
	,{"country":"South Korea","agency":"BlockBerryCreative","counter2":0,"city":"Bucheon","counter1":5,"zodiac":"Gemini","chineseZodiac":"Snake","groupNameUpper":"LOONA","positions":"Rapper, Dancer, Vocalist","counter":5,"nameUpper":"CHOERRY","zodiacId":3,"birthDate":20010604,"realName":"Choi Yerin","idolId":34,"groupName":"LOONA","chineseZodiacId":6,"fandom":"Orbit","imageFileName":"CHOERRY_LOONA","name":"Choerry","age":21}
	,{"country":"South Korea","agency":"JYP Entertainment","counter2":2,"city":"Incheon","counter1":1,"zodiac":"Cancer","chineseZodiac":"Dragon","groupNameUpper":"ITZY","positions":"Main Vocalist, Sub Rapper","counter":3,"nameUpper":"LIA","zodiacId":4,"birthDate":20000721,"realName":"Choi Jisoo","idolId":35,"groupName":"ITZY","chineseZodiacId":5,"fandom":"MIDZY","imageFileName":"LIA_ITZY","name":"Lia","age":22}
	,{"country":"South Korea","agency":"MYSTIC Story","counter2":11,"city":"Yeonsu-gu/Incheon","counter1":15,"zodiac":"Aquarius","chineseZodiac":"Goat","groupNameUpper":"BILLLIE","positions":"Main Dancer, Lead Rapper","counter":26,"nameUpper":"SHEON","zodiacId":11,"birthDate":20030128,"realName":"Kim Suyeon","idolId":36,"groupName":"Billlie","chineseZodiacId":8,"fandom":"Belllie've","imageFileName":"SHEON_BILLLIE","name":"Sheon","age":19}
	,{"country":"South Korea","agency":"BlockBerryCreative","counter2":6,"city":"Seoul","counter1":30,"zodiac":"Scorpius","chineseZodiac":"Horse","groupNameUpper":"LOONA","positions":"Vocalist, Rapper, Maknae","counter":36,"nameUpper":"YEOJIN","zodiacId":8,"birthDate":20021111,"realName":"Im Yeojin","idolId":37,"groupName":"LOONA","chineseZodiacId":7,"fandom":"Orbit","imageFileName":"YEOJIN_LOONA","name":"Yeojin","age":19}
	,{"country":"Japan","agency":"MYSTIC Story","counter2":1,"city":"Hyoge","counter1":7,"zodiac":"Virgo","chineseZodiac":"Horse","groupNameUpper":"BILLLIE","positions":"Main Dancer, Sub Vocalist","counter":8,"nameUpper":"TSUKI","zodiacId":6,"birthDate":20020921,"realName":"Fukutomi Tsuki","idolId":38,"groupName":"Billlie","chineseZodiacId":7,"fandom":"Belllie've","imageFileName":"TSUKI_BILLLIE","name":"Tsuki","age":20}
	,{"country":"South Korea","agency":"BlockBerryCreative","counter2":5,"city":"Chuncheon","counter1":5,"zodiac":"Gemini","chineseZodiac":"Ox","groupNameUpper":"LOONA","positions":"Rapper, Vocalist, Visual","counter":10,"nameUpper":"JINSOUL","zodiacId":3,"birthDate":19970613,"realName":"Jeong Jinsol","idolId":39,"groupName":"LOONA","chineseZodiacId":2,"fandom":"Orbit","imageFileName":"JINSOUL_LOONA","name":"Jinsoul","age":25}
	,{"country":"South Korea","agency":"Pledis Entertainment","counter2":0,"city":"Pohang","counter1":5,"zodiac":"Taurus","chineseZodiac":"Dragon","groupNameUpper":"FROMIS_9","positions":"Main Dancer, Lead Rapper, Vocalist","counter":5,"nameUpper":"CHAEYOUNG","zodiacId":2,"birthDate":20000514,"realName":"Lee Chaeyoung","idolId":40,"groupName":"fromis_9","chineseZodiacId":5,"fandom":"Flover","imageFileName":"CHAEYOUNG_FROMIS9","name":"Chaeyoung","age":22}
	,{"country":"South Korea","agency":"NV Entertainment","counter2":2,"city":"Nowon-gu/Seoul","counter1":2,"zodiac":"Pisces","chineseZodiac":"Snake","groupNameUpper":"WOO!AH!","positions":"Leader, Lead Vocalist, Lead Rapper, Main Dancer, Visual","counter":4,"nameUpper":"NANA","zodiacId":12,"birthDate":20010309,"realName":"Kwon Nayeon","idolId":41,"groupName":"woo!ah!","chineseZodiacId":6,"fandom":"wow!","imageFileName":"NANA_WOOAH","name":"Nana","age":21}
	,{"country":"South Korea","agency":"IST Entertainment","counter2":5,"city":"Bundang-gu/Seongnam/Gyeonggi-do","counter1":5,"zodiac":"Taurus","chineseZodiac":"Horse","groupNameUpper":"WEEEKLY","positions":"Main Vocalist, Main Dancer, Sub Rapper","counter":10,"nameUpper":"MONDAY","zodiacId":2,"birthDate":20020510,"realName":"Kim Jimin","idolId":42,"groupName":"Weeekly","chineseZodiacId":7,"fandom":"Daileee","imageFileName":"MONDAY_WEEEKLY","name":"Monday","age":20}
	,{"country":"South Korea","agency":"IST Entertainment","counter2":0,"city":"Songpa-gu/Seoul","counter1":3,"zodiac":"Sagittarius","chineseZodiac":"Snake","groupNameUpper":"WEEEKLY","positions":"Leader, Main Dancer, Sub Vocalist, Sub Rapper, Visual, Center","counter":3,"nameUpper":"SOOJIN","zodiacId":9,"birthDate":20011212,"realName":"Lee Soojin","idolId":43,"groupName":"Weeekly","chineseZodiacId":6,"fandom":"Daileee","imageFileName":"SOOJIN_WEEEKLY","name":"Soojin","age":20}
	,{"country":"South Korea","agency":"IST Entertainment","counter2":0,"city":"Ilsanseo-gu/Goyang/Gyeonggi-do","counter1":3,"zodiac":"Pisces","chineseZodiac":"Monkey","groupNameUpper":"WEEEKLY","positions":"Sub Vocalist, Sub Rapper","counter":3,"nameUpper":"JAEHEE","zodiacId":12,"birthDate":20040318,"realName":"Lee Jaehee","idolId":44,"groupName":"Weeekly","chineseZodiacId":9,"fandom":"Daileee","imageFileName":"JAEHEE_WEEEKLY","name":"Jaehee","age":18}
	,{"country":"South Korea","agency":"MYSTIC Story","counter2":4,"city":"Jeonju/Jeollabuk-do","counter1":19,"zodiac":"Capricorn","chineseZodiac":"Snake","groupNameUpper":"BILLLIE","positions":"Main Vocalist","counter":23,"nameUpper":"HARAM","zodiacId":10,"birthDate":20010113,"realName":"Kim Haram","idolId":45,"groupName":"Billlie","chineseZodiacId":6,"fandom":"Belllie've","imageFileName":"HARAM_BILLLIE","name":"Haram","age":21}
	,{"country":"South Korea","agency":"iMe Entertainment","counter2":0,"city":"Incheon","counter1":3,"zodiac":"Scorpius","chineseZodiac":"Rabbit","groupNameUpper":"DREAM NOTE","positions":"Lead Vocalist, Lead Dancer, Rapper","counter":3,"nameUpper":"BONI","zodiacId":8,"birthDate":19991030,"realName":"Choi Euijeong","idolId":46,"groupName":"Dream Note","chineseZodiacId":4,"fandom":"Page","imageFileName":"BONI_DREAMNOTE","name":"Boni","age":22}
	,{"country":"South Korea","agency":"SM Entertainment","counter2":3,"city":"Paldal-gu/Gyeonggi-do","counter1":1,"zodiac":"Aries","chineseZodiac":"Dragon","groupNameUpper":"AESPA","positions":"Leader, Main Dancer, Lead Rapper, Sub Vocalist, Visual, Face of the Group, Center","counter":4,"nameUpper":"KARINA","zodiacId":1,"birthDate":20000411,"realName":"Yoo Jimin","idolId":47,"groupName":"aespa","chineseZodiacId":5,"fandom":"MY","imageFileName":"KARINA_AESPA","name":"Karina","age":22}
	,{"country":"South Korea","agency":"FNC Entertainment","counter2":3,"city":"Gwangju","counter1":6,"zodiac":"Pisces","chineseZodiac":"Rabbit","groupNameUpper":"CHERRY BULLET","positions":"Main Vocalist","counter":9,"nameUpper":"BORA","zodiacId":12,"birthDate":19990303,"realName":"Kim Bora","idolId":48,"groupName":"Cherry Bullet","chineseZodiacId":4,"fandom":"Lullet","imageFileName":"BORA_CHERRYBULLET","name":"Bora","age":23}
	,{"country":"South Korea","agency":"Cube Entertainment","counter2":7,"city":"Incheon","counter1":13,"zodiac":"Aquarius","chineseZodiac":"Ox","groupNameUpper":"(G)I-DLE","positions":"Main Vocalist, Visual","counter":20,"nameUpper":"MIYEON","zodiacId":11,"birthDate":19970131,"realName":"Jo Miyeon","idolId":49,"groupName":"(g)i-dle","chineseZodiacId":2,"fandom":"Neverland","imageFileName":"MIYEON_GIDLE","name":"Miyeon","age":25}
	,{"country":"South Korea","agency":"ALLART Entertainment","counter2":1,"city":"(none)","counter1":4,"zodiac":"Leo","chineseZodiac":"Goat","groupNameUpper":"PIXY","positions":"Sub Vocalist, Maknae","counter":5,"nameUpper":"DAJEONG","zodiacId":5,"birthDate":20030731,"realName":"Jung Dajeong","idolId":50,"groupName":"Pixy","chineseZodiacId":8,"fandom":"Winxy","imageFileName":"DAJEONG_PIXY","name":"Dajeong","age":19}
	,{"country":"South Korea","agency":"Cube Entertainment","counter2":2,"city":"Incheon","counter1":10,"zodiac":"Virgo","chineseZodiac":"Horse","groupNameUpper":"LIGHTSUM","positions":"Lead Dancer, Rapper","counter":12,"nameUpper":"SANGAH","zodiacId":6,"birthDate":20020904,"realName":"Yoon Sangah","idolId":51,"groupName":"Lightsum","chineseZodiacId":7,"fandom":"SUMIT","imageFileName":"SANGAH_LIGHTSUM","name":"Sangah","age":20}
	,{"country":"South Korea","agency":"YG Entertainment","counter2":3,"city":"Gunpo/Gyeonggi-do","counter1":7,"zodiac":"Capricorn","chineseZodiac":"Pig","groupNameUpper":"BLACKPINK","positions":"Lead Vocalist, Visual","counter":10,"nameUpper":"JISOO","zodiacId":10,"birthDate":19950103,"realName":"Kim Jisoo","idolId":52,"groupName":"Blackpink","chineseZodiacId":12,"fandom":"BLINK","imageFileName":"JISOO_BLACKPINK","name":"Jisoo","age":27}
	,{"country":"South Korea","agency":"Cube Entertainment","counter2":0,"city":"Seoul","counter1":1,"zodiac":"Virgo","chineseZodiac":"Tiger","groupNameUpper":"(G)I-DLE","positions":"Leader, Main Rapper, Sub Vocalist, Center","counter":1,"nameUpper":"SOYEON","zodiacId":6,"birthDate":19980826,"realName":"Jeon Soyeon","idolId":53,"groupName":"(g)i-dle","chineseZodiacId":3,"fandom":"Neverland","imageFileName":"SOYEON_GIDLE","name":"Soyeon","age":24}
	,{"country":"USA","agency":"Vine Entertainment","counter2":2,"city":"Los Angeles/California","counter1":8,"zodiac":"Aquarius","chineseZodiac":"Tiger","groupNameUpper":"SECRET NUMBER","positions":"Main Rapper, Sub Vocalist","counter":10,"nameUpper":"JINNY","zodiacId":11,"birthDate":19980120,"realName":"Jinny Park","idolId":54,"groupName":"Secret Number","chineseZodiacId":3,"fandom":"LOCKEY","imageFileName":"JINNY_SECRETNUMBER","name":"Jinny","age":24}
	,{"country":"South Korea","agency":"IST Entertainment","counter2":4,"city":"Seoul","counter1":5,"zodiac":"Gemini","chineseZodiac":"Rooster","groupNameUpper":"WEEEKLY","positions":"Sub Vocalist, Sub Rapper, Visual, Maknae","counter":9,"nameUpper":"ZOA","zodiacId":3,"birthDate":20050531,"realName":"Cho Hyewon","idolId":55,"groupName":"Weeekly","chineseZodiacId":10,"fandom":"Daileee","imageFileName":"ZOA_WEEEKLY","name":"Zoa","age":17}
	,{"country":"South Korea","agency":"Source Music","counter2":0,"city":"Ilsan","counter1":1,"zodiac":"Libra","chineseZodiac":"Ox","groupNameUpper":"GFRIEND","positions":"Main Vocalist","counter":1,"nameUpper":"YUJU","zodiacId":7,"birthDate":19971004,"realName":"Choi Yuna","idolId":56,"groupName":"Gfriend","chineseZodiacId":2,"fandom":"BUDDY","imageFileName":"YUJU_GFRIEND","name":"Yuju","age":25}
	,{"country":"Japan","agency":"JYP Entertainment","counter2":4,"city":"Osaka","counter1":3,"zodiac":"Capricorn","chineseZodiac":"Rat","groupNameUpper":"TWICE","positions":"Sub Vocalist","counter":7,"nameUpper":"SANA","zodiacId":10,"birthDate":19961229,"realName":"Minatozaki Sana","idolId":57,"groupName":"Twice","chineseZodiacId":1,"fandom":"ONCE","imageFileName":"SANA_TWICE","name":"Sana","age":25}
	,{"country":"South Korea","agency":"J9 Entertainment","counter2":1,"city":"Yeosu","counter1":6,"zodiac":"Cancer","chineseZodiac":"Tiger","groupNameUpper":"CIGNATURE","positions":"Vocalist, Visual","counter":7,"nameUpper":"CHAESOL","zodiacId":4,"birthDate":19980714,"realName":"Moon Chaesol","idolId":58,"groupName":"cignature","chineseZodiacId":3,"fandom":"signfan","imageFileName":"CHAESOL_CIGNATURE","name":"Chaesol","age":24}
	,{"country":"South Korea","agency":"TR Entertainment","counter2":1,"city":"Siheung/Gyeonggi-do","counter1":1,"zodiac":"Scorpius","chineseZodiac":"Goat","groupNameUpper":"TRI.BE","positions":"Lead Vocalist, Lead Dancer","counter":2,"nameUpper":"JINHA","zodiacId":8,"birthDate":20031121,"realName":"Kim Jinha","idolId":59,"groupName":"TRI.BE","chineseZodiacId":8,"fandom":"TRUE","imageFileName":"JINHA_TRIBE","name":"Jinha","age":18}
	,{"country":"South Korea","agency":"JYP Entertainment","counter2":3,"city":"Jeonju","counter1":6,"zodiac":"Gemini","chineseZodiac":"Dragon","groupNameUpper":"ITZY","positions":"Leader, Main Dancer, Lead Vocalist, Sub Rapper","counter":9,"nameUpper":"YEJI","zodiacId":3,"birthDate":20000526,"realName":"Hwang Yeji","idolId":60,"groupName":"ITZY","chineseZodiacId":5,"fandom":"MIDZY","imageFileName":"YEJI_ITZY","name":"Yeji","age":22}
	,{"country":"South Korea","agency":"High Up Entertainment","counter2":11,"city":"Pohang/North Gyeongsang","counter1":13,"zodiac":"Pisces","chineseZodiac":"Snake","groupNameUpper":"STAYC","positions":"Leader, Vocalist, Rapper","counter":24,"nameUpper":"SUMIN","zodiacId":12,"birthDate":20010313,"realName":"Bae Sumin","idolId":61,"groupName":"Stayc","chineseZodiacId":6,"fandom":"SWITH","imageFileName":"SUMIN_STAYC","name":"Sumin","age":21}
	,{"country":"South Korea","agency":"MYSTIC Story","counter2":2,"city":"Daegu","counter1":4,"zodiac":"Capricorn","chineseZodiac":"Dragon","groupNameUpper":"BILLLIE","positions":"Main Vocalist, Lead Dancer","counter":6,"nameUpper":"SUHYEON","zodiacId":10,"birthDate":20000115,"realName":"Kim Suhyeon","idolId":62,"groupName":"Billlie","chineseZodiacId":5,"fandom":"Belllie've","imageFileName":"SUHYEON_BILLLIE","name":"Suhyeon","age":22}
	,{"country":"South Korea","agency":"MNH Entertainment","counter2":0,"city":"Ulsan","counter1":2,"zodiac":"Aquarius","chineseZodiac":"Rat","groupNameUpper":"SOLOIST","positions":"(none)","counter":2,"nameUpper":"CHUNGHA","zodiacId":11,"birthDate":19960209,"realName":"Kim Chanmi","idolId":63,"groupName":"soloist","chineseZodiacId":1,"fandom":"BYULHARANG","imageFileName":"CHUNGHA_SOLOIST","name":"Chungha","age":26}
	,{"country":"China","agency":"Dreamcatcher Company","counter2":3,"city":"Wuhan","counter1":8,"zodiac":"Aries","chineseZodiac":"Rat","groupNameUpper":"DREAMCATCHER","positions":"Sub Vocalist","counter":11,"nameUpper":"HANDONG","zodiacId":1,"birthDate":19960326,"realName":"Han Dong","idolId":64,"groupName":"Dreamcatcher","chineseZodiacId":1,"fandom":"InSomnia","imageFileName":"HANDONG_DREAMCATCHER","name":"Handong","age":26}
	,{"country":"South Korea","agency":"High Up Entertainment","counter2":0,"city":"Pyeongtaek","counter1":3,"zodiac":"Gemini","chineseZodiac":"Goat","groupNameUpper":"STAYC","positions":"Vocalist","counter":3,"nameUpper":"SEEUN","zodiacId":3,"birthDate":20030614,"realName":"Yoon Seeun","idolId":65,"groupName":"Stayc","chineseZodiacId":8,"fandom":"SWITH","imageFileName":"SEEUN_STAYC","name":"Seeun","age":19}
	,{"country":"Taiwan","agency":"Cube Entertainment","counter2":1,"city":"Taoyuan","counter1":4,"zodiac":"Capricorn","chineseZodiac":"Dragon","groupNameUpper":"(G)I-DLE","positions":"Sub Vocalist, Visual, Maknae","counter":5,"nameUpper":"SHUHUA","zodiacId":10,"birthDate":20000106,"realName":"Yeh Shuhua","idolId":66,"groupName":"(g)i-dle","chineseZodiacId":5,"fandom":"Neverland","imageFileName":"SHUHUA_GIDLE","name":"Shuhua","age":22}
	,{"country":"Japan","agency":"Starship Entertainment","counter2":2,"city":"Nagoya/Aichi","counter1":6,"zodiac":"Aquarius","chineseZodiac":"Monkey","groupNameUpper":"IVE","positions":"Rapper, Vocalist","counter":8,"nameUpper":"REI","zodiacId":11,"birthDate":20040203,"realName":"Naoi Rei","idolId":67,"groupName":"IVE","chineseZodiacId":9,"fandom":"DIVE","imageFileName":"REI_IVE","name":"Rei","age":18}
	,{"country":"South Korea","agency":"WM Entertainment","counter2":1,"city":"Yongin","counter1":3,"zodiac":"Capricorn","chineseZodiac":"Dragon","groupNameUpper":"SOLOIST","positions":"(none)","counter":4,"nameUpper":"CHAEYEON","zodiacId":10,"birthDate":20000111,"realName":"Lee Chaeyeon","idolId":68,"groupName":"soloist","chineseZodiacId":5,"fandom":"WIZ*ONE","imageFileName":"CHAEYEON_SOLOIST","name":"Chaeyeon","age":22}
	,{"country":"South Korea","agency":"Vine Entertainment","counter2":0,"city":"Seoul","counter1":2,"zodiac":"Scorpius","chineseZodiac":"Rabbit","groupNameUpper":"SECRET NUMBER","positions":"Lead Dancer, Sub Vocalist, Visual, Center","counter":2,"nameUpper":"SOODAM","zodiacId":8,"birthDate":19991109,"realName":"Lee Soodam","idolId":69,"groupName":"Secret Number","chineseZodiacId":4,"fandom":"LOCKEY","imageFileName":"SOODAM_SECRETNUMBER","name":"Soodam","age":22}
	,{"country":"South Korea","agency":"Woollim Entertainment","counter2":0,"city":"Gwangju","counter1":5,"zodiac":"Scorpius","chineseZodiac":"Snake","groupNameUpper":"ROCKET PUNCH","positions":"Vocalist, Rapper, Dancer","counter":5,"nameUpper":"YUNKYOUNG","zodiacId":8,"birthDate":20011101,"realName":"Seo Yunkyoung","idolId":70,"groupName":"Rocket Punch","chineseZodiacId":6,"fandom":"KETCHY","imageFileName":"YUNKYOUNG_ROCKETPUNCH","name":"Yunkyoung","age":20}
	,{"country":"South Korea","agency":"Brave Entertainment","counter2":1,"city":"Suwon","counter1":0,"zodiac":"Taurus","chineseZodiac":"Goat","groupNameUpper":"BRAVE GIRLS","positions":"Vocalist, Visual","counter":1,"nameUpper":"YUJEONG","zodiacId":2,"birthDate":19910502,"realName":"Nam Yujeong","idolId":71,"groupName":"Brave Girls","chineseZodiacId":8,"fandom":"FEARLESS","imageFileName":"YUJEONG_BRAVEGIRLS","name":"Yujeong","age":31}
	,{"country":"South Korea","agency":"JYP Entertainment","counter2":0,"city":"Daejeon","counter1":7,"zodiac":"Aquarius","chineseZodiac":"Monkey","groupNameUpper":"NMIXX","positions":"Vocalist, Dancer","counter":7,"nameUpper":"SULLYOON","zodiacId":11,"birthDate":20040126,"realName":"Seol Yoona","idolId":72,"groupName":"NMIXX","chineseZodiacId":9,"fandom":"NSWER","imageFileName":"SULLYOON_NMIXX","name":"Sullyoon","age":18}
	,{"country":"South Korea","agency":"Woollim Entertainment","counter2":0,"city":"Goyang","counter1":2,"zodiac":"Pisces","chineseZodiac":"Snake","groupNameUpper":"ROCKET PUNCH","positions":"Vocalist, Dancer","counter":2,"nameUpper":"SUYUN","zodiacId":12,"birthDate":20010317,"realName":"Kim Suyun","idolId":73,"groupName":"Rocket Punch","chineseZodiacId":6,"fandom":"KETCHY","imageFileName":"SUYUN_ROCKETPUNCH","name":"Suyun","age":21}
	,{"country":"South Korea","agency":"MYSTIC Story","counter2":0,"city":"Cheongju/Chungcheongbuk-do","counter1":2,"zodiac":"Virgo","chineseZodiac":"Rabbit","groupNameUpper":"BILLLIE","positions":"Main Rapper, Lead Vocalist","counter":2,"nameUpper":"MOON SUA","zodiacId":6,"birthDate":19990909,"realName":"Moon Sua","idolId":74,"groupName":"Billlie","chineseZodiacId":4,"fandom":"Belllie've","imageFileName":"MOONSUA_BILLLIE","name":"Moon Sua","age":23}
	,{"country":"South Korea","agency":"Woollim Entertainment","counter2":0,"city":"Buk-gu/Gwangju","counter1":5,"zodiac":"Sagittarius","chineseZodiac":"Dragon","groupNameUpper":"ROCKET PUNCH","positions":"Leader, Vocalist, Dancer, Rapper","counter":5,"nameUpper":"YEONHEE","zodiacId":9,"birthDate":20001206,"realName":"Kim Yeonhee","idolId":75,"groupName":"Rocket Punch","chineseZodiacId":5,"fandom":"KETCHY","imageFileName":"YEONHEE_ROCKETPUNCH","name":"Yeonhee","age":21}
	,{"country":"South Korea","agency":"Dreamcatcher Company","counter2":3,"city":"Incheon","counter1":4,"zodiac":"Capricorn","chineseZodiac":"Ox","groupNameUpper":"DREAMCATCHER","positions":"Lead Vocalist","counter":7,"nameUpper":"YOOHYEON","zodiacId":10,"birthDate":19970107,"realName":"Kim Yoohyeon","idolId":76,"groupName":"Dreamcatcher","chineseZodiacId":2,"fandom":"InSomnia","imageFileName":"YOOHYEON_DREAMCATCHER","name":"Yoohyeon","age":25}
	,{"country":"South Korea","agency":"BPM Entertainment","counter2":3,"city":"Seoul","counter1":9,"zodiac":"Gemini","chineseZodiac":"Ox","groupNameUpper":"VIVIZ","positions":"Main Vocalist","counter":12,"nameUpper":"EUNHA","zodiacId":3,"birthDate":19970530,"realName":"Jung Eunbi","idolId":77,"groupName":"VIVIZ","chineseZodiacId":2,"fandom":"Na.V","imageFileName":"EUNHA_VIVIZ","name":"Eunha","age":25}
	,{"country":"South Korea","agency":"Urban Works Entertainment","counter2":0,"city":"Seoul","counter1":2,"zodiac":"Aquarius","chineseZodiac":"Snake","groupNameUpper":"SOLOIST","positions":"(none)","counter":2,"nameUpper":"MINJU","zodiacId":11,"birthDate":20010205,"realName":"Kim Minju","idolId":78,"groupName":"soloist","chineseZodiacId":6,"fandom":"WIZ*ONE","imageFileName":"MINJU_SOLOIST","name":"Minju","age":21}
	,{"country":"South Korea","agency":"Pledis Entertainment","counter2":3,"city":"Chuncheon","counter1":1,"zodiac":"Capricorn","chineseZodiac":"Ox","groupNameUpper":"FROMIS_9","positions":"Leader, Lead Dancer, Vocalist, Rapper, Visual","counter":4,"nameUpper":"SAEROM","zodiacId":10,"birthDate":19970107,"realName":"Lee Saerom","idolId":79,"groupName":"fromis_9","chineseZodiacId":2,"fandom":"Flover","imageFileName":"SAEROM_FROMIS9","name":"Saerom","age":25}
	,{"country":"Japan","agency":"JYP Entertainment","counter2":3,"city":"Kyoto","counter1":0,"zodiac":"Scorpius","chineseZodiac":"Rat","groupNameUpper":"TWICE","positions":"Main Dancer, Sub Vocalist, Sub Rapper","counter":3,"nameUpper":"MOMO","zodiacId":8,"birthDate":19961109,"realName":"Hirai Momo","idolId":80,"groupName":"Twice","chineseZodiacId":1,"fandom":"ONCE","imageFileName":"MOMO_TWICE","name":"Momo","age":25}
	,{"country":"China","agency":"Cube Entertainment","counter2":5,"city":"Beijing","counter1":7,"zodiac":"Libra","chineseZodiac":"Rabbit","groupNameUpper":"(G)I-DLE","positions":"Lead Dancer, Sub Vocalist, Sub Rapper, Face of the group","counter":12,"nameUpper":"YUQI","zodiacId":7,"birthDate":19990923,"realName":"Song Yuqi","idolId":81,"groupName":"(g)i-dle","chineseZodiacId":4,"fandom":"Neverland","imageFileName":"YUQI_GIDLE","name":"Yuqi","age":23}
	,{"country":"South Korea","agency":"WM Entertainment","counter2":1,"city":"Okcheon/North Chungcheong","counter1":1,"zodiac":"Aries","chineseZodiac":"Ox","groupNameUpper":"OH MY GIRL","positions":"Lead Vocalist, Lead Dancer, Visual","counter":2,"nameUpper":"JIHO","zodiacId":1,"birthDate":19970404,"realName":"Kim Jiho","idolId":82,"groupName":"Oh My Girl","chineseZodiacId":2,"fandom":"Miracle","imageFileName":"JIHO_OHMYGIRL","name":"Jiho","age":25}
	,{"country":"South Korea","agency":"WAKEONE and Swing Entertainment","counter2":0,"city":"Incheon","counter1":3,"zodiac":"Leo","chineseZodiac":"Rooster","groupNameUpper":"KEP1ER","positions":"Maknae","counter":3,"nameUpper":"YESEO","zodiacId":5,"birthDate":20050822,"realName":"Kang Yeseo","idolId":83,"groupName":"Kep1er","chineseZodiacId":10,"fandom":"Kep1ian","imageFileName":"YESEO_KEP1ER","name":"Yeseo","age":17}
	,{"country":"Taiwan","agency":"JYP Entertainment","counter2":3,"city":"Tainan","counter1":1,"zodiac":"Gemini","chineseZodiac":"Rabbit","groupNameUpper":"TWICE","positions":"Lead Dancer, Sub Vocalist, Visual, Maknae","counter":4,"nameUpper":"TZUYU","zodiacId":3,"birthDate":19990614,"realName":"Chou Tzuyu","idolId":84,"groupName":"Twice","chineseZodiacId":4,"fandom":"ONCE","imageFileName":"TZUYU_TWICE","name":"Tzuyu","age":23}
	,{"country":"Japan","agency":"MYSTIC Story","counter2":0,"city":"Osaka","counter1":2,"zodiac":"Aquarius","chineseZodiac":"Dog","groupNameUpper":"BILLLIE","positions":"Sub Vocalist, Maknae","counter":2,"nameUpper":"HARUNA","zodiacId":11,"birthDate":20060130,"realName":"Osato Haruna","idolId":85,"groupName":"Billlie","chineseZodiacId":11,"fandom":"Belllie've","imageFileName":"HARUNA_BILLLIE","name":"Haruna","age":16}
	,{"country":"South Korea","agency":"Dreamcatcher Company","counter2":6,"city":"Seongnam","counter1":2,"zodiac":"Aquarius","chineseZodiac":"Rabbit","groupNameUpper":"DREAMCATCHER","positions":"Lead Rapper, Sub Vocalist, Maknae","counter":8,"nameUpper":"GAHYEON","zodiacId":11,"birthDate":19990203,"realName":"Lee Gahyeon","idolId":86,"groupName":"Dreamcatcher","chineseZodiacId":4,"fandom":"InSomnia","imageFileName":"GAHYEON_DREAMCATCHER","name":"Gahyeon","age":23}
	,{"country":"South Korea","agency":"JYP Entertainment","counter2":0,"city":"Namyangju/Gyeonggi-do","counter1":3,"zodiac":"Aries","chineseZodiac":"Rooster","groupNameUpper":"NMIXX","positions":"Vocalist, Dancer, Rapper","counter":3,"nameUpper":"JIWOO","zodiacId":1,"birthDate":20050413,"realName":"Kim Jiwoo","idolId":87,"groupName":"NMIXX","chineseZodiacId":10,"fandom":"NSWER","imageFileName":"JIWOO_NMIXX","name":"Jiwoo","age":17}
	,{"country":"South Korea","agency":"RBW","counter2":0,"city":"Nam-gu/Gwangji","counter1":2,"zodiac":"Virgo","chineseZodiac":"Rabbit","groupNameUpper":"PURPLE KISS","positions":"Main Vocalist, Lead Dancer","counter":2,"nameUpper":"GOEUN","zodiacId":6,"birthDate":19990903,"realName":"Na Goeun","idolId":88,"groupName":"Purple Kiss","chineseZodiacId":4,"fandom":"PLORY","imageFileName":"GOEUN_PURPLEKISS","name":"Goeun","age":23}
	,{"country":"South Korea","agency":"RBW","counter2":0,"city":"Busan","counter1":10,"zodiac":"Aquarius","chineseZodiac":"Dragon","groupNameUpper":"PURPLE KISS","positions":"Main Dancer, Vocalist","counter":10,"nameUpper":"DOSIE","zodiacId":11,"birthDate":20000211,"realName":"Jang Eunseong","idolId":89,"groupName":"Purple Kiss","chineseZodiacId":5,"fandom":"PLORY","imageFileName":"DOSIE_PURPLEKISS","name":"Dosie","age":22}
	,{"country":"South Korea","agency":"BlockBerryCreative","counter2":0,"city":"Busan","counter1":6,"zodiac":"Gemini","chineseZodiac":"Ox","groupNameUpper":"LOONA","positions":"Leader, Dancer, Vocalist, Rapper","counter":6,"nameUpper":"YVES","zodiacId":3,"birthDate":19970524,"realName":"Ha Sooyoung","idolId":90,"groupName":"LOONA","chineseZodiacId":2,"fandom":"Orbit","imageFileName":"YVES_LOONA","name":"Yves","age":25}
	,{"country":"Thailand","agency":"Cube Entertainment","counter2":0,"city":"Bangkok","counter1":1,"zodiac":"Scorpius","chineseZodiac":"Ox","groupNameUpper":"(G)I-DLE","positions":"Main Vocalist","counter":1,"nameUpper":"MINNIE","zodiacId":8,"birthDate":19971023,"realName":"Minnie Nicha Yontararak","idolId":91,"groupName":"(g)i-dle","chineseZodiacId":2,"fandom":"Neverland","imageFileName":"MINNIE_GIDLE","name":"Minnie","age":24}
	,{"country":"Japan","agency":"RBW","counter2":0,"city":"(none)","counter1":2,"zodiac":"Scorpius","chineseZodiac":"Horse","groupNameUpper":"PURPLE KISS","positions":"Main Rapper, Lead Dancer, Vocalist","counter":2,"nameUpper":"YUKI","zodiacId":8,"birthDate":20021106,"realName":"Mori Koyuki","idolId":92,"groupName":"Purple Kiss","chineseZodiacId":7,"fandom":"PLORY","imageFileName":"YUKI_PURPLEKISS","name":"Yuki","age":19}
	,{"country":"South Korea","agency":"RBW","counter2":0,"city":"Gangdong-gu/Seoul","counter1":2,"zodiac":"Virgo","chineseZodiac":"Ox","groupNameUpper":"PURPLE KISS","positions":"Vocalist","counter":2,"nameUpper":"JIEUN","zodiacId":6,"birthDate":19970904,"realName":"Park Jieun","idolId":93,"groupName":"Purple Kiss","chineseZodiacId":2,"fandom":"PLORY","imageFileName":"JIEUN_PURPLEKISS","name":"Jieun","age":25}
	,{"country":"South Korea","agency":"RBW","counter2":0,"city":"(none)","counter1":1,"zodiac":"Taurus","chineseZodiac":"Horse","groupNameUpper":"PURPLE KISS","positions":"Main Dancer, Vocalist","counter":1,"nameUpper":"IREH","zodiacId":2,"birthDate":20020430,"realName":"Cho Seoyoung","idolId":94,"groupName":"Purple Kiss","chineseZodiacId":7,"fandom":"PLORY","imageFileName":"IREH_PURPLEKISS","name":"Ireh","age":20}
	,{"country":"Japan","agency":"Woollim Entertainment","counter2":1,"city":"Kashima/Ibaraki","counter1":3,"zodiac":"Libra","chineseZodiac":"Ox","groupNameUpper":"ROCKET PUNCH","positions":"Vocalist, Dancer","counter":4,"nameUpper":"JURI","zodiacId":7,"birthDate":19971003,"realName":"Takahashi Juri","idolId":95,"groupName":"Rocket Punch","chineseZodiacId":2,"fandom":"KETCHY","imageFileName":"JURI_ROCKETPUNCH","name":"Juri","age":25}
	,{"country":"South Korea","agency":"8D Entertainment","counter2":1,"city":"Yangsan/South Gyeongsang","counter1":2,"zodiac":"Cancer","chineseZodiac":"Rabbit","groupNameUpper":"SOLOIST","positions":"(none)","counter":3,"nameUpper":"HYEWON","zodiacId":4,"birthDate":19990705,"realName":"Kang Hyewon","idolId":96,"groupName":"soloist","chineseZodiacId":4,"fandom":"WIZ*ONE","imageFileName":"HYEWON_SOLOIST","name":"Hyewon","age":23}
	,{"country":"South Korea","agency":"JYP Entertainment","counter2":1,"city":"Busan","counter1":8,"zodiac":"Aries","chineseZodiac":"Monkey","groupNameUpper":"NMIXX","positions":"Vocalist, Dancer, Rapper","counter":9,"nameUpper":"JINNI","zodiacId":1,"birthDate":20040416,"realName":"Choi Yunjin","idolId":97,"groupName":"NMIXX","chineseZodiacId":9,"fandom":"NSWER","imageFileName":"JINNI_NMIXX","name":"Jinni","age":18}
	,{"country":"South Korea","agency":"JYP Entertainment","counter2":3,"city":"Bundang-gu/Seongnam/Gyeonggi-do","counter1":3,"zodiac":"Gemini","chineseZodiac":"Dog","groupNameUpper":"NMIXX","positions":"Vocalist, Dancer, Rapper, Maknae","counter":6,"nameUpper":"KYUJIN","zodiacId":3,"birthDate":20060526,"realName":"Jang Kyujin","idolId":98,"groupName":"NMIXX","chineseZodiacId":11,"fandom":"NSWER","imageFileName":"KYUJIN_NMIXX","name":"Kyujin","age":16}
	,{"country":"South Korea","agency":"ALLART Entertainment","counter2":2,"city":"(none)","counter1":6,"zodiac":"Cancer","chineseZodiac":"Snake","groupNameUpper":"PIXY","positions":"Main Dancer, Lead Vocalist","counter":8,"nameUpper":"DIA","zodiacId":4,"birthDate":20010716,"realName":"Choi Eunji","idolId":99,"groupName":"Pixy","chineseZodiacId":6,"fandom":"Winxy","imageFileName":"DIA_PIXY","name":"Dia","age":21}
	,{"country":"Japan","agency":"Cube Entertainment","counter2":0,"city":"Kanagawa","counter1":1,"zodiac":"Aries","chineseZodiac":"Goat","groupNameUpper":"LIGHTSUM","positions":"Sub Vocalist","counter":1,"nameUpper":"HINA","zodiacId":1,"birthDate":20030407,"realName":"Nagai Hina","idolId":100,"groupName":"Lightsum","chineseZodiacId":8,"fandom":"SUMIT","imageFileName":"HINA_LIGHTSUM","name":"Hina","age":19}
	,{"country":"South Korea","agency":"iMe Entertainment","counter2":0,"city":"Icheon/Gyeonggi-do","counter1":3,"zodiac":"Pisces","chineseZodiac":"Horse","groupNameUpper":"DREAM NOTE","positions":"Vocalist, Rapper, Visual, Maknae","counter":3,"nameUpper":"EUNJO","zodiacId":12,"birthDate":20020307,"realName":"Park Eunjo","idolId":101,"groupName":"Dream Note","chineseZodiacId":7,"fandom":"Page","imageFileName":"EUNJO_DREAMNOTE","name":"Eunjo","age":20}
	,{"country":"South Korea","agency":"WM Entertainment","counter2":0,"city":"Chuncheon/Gangwon","counter1":4,"zodiac":"Virgo","chineseZodiac":"Ox","groupNameUpper":"OH MY GIRL","positions":"Sub Vocalist","counter":4,"nameUpper":"YUBIN","zodiacId":6,"birthDate":19970909,"realName":"Bae Yubin","idolId":102,"groupName":"Oh My Girl","chineseZodiacId":2,"fandom":"Miracle","imageFileName":"YUBIN_OHMYGIRL","name":"Yubin","age":25}
	,{"country":"South Korea","agency":"Source Music","counter2":3,"city":"Sangju/Gyeongsangbuk-do","counter1":1,"zodiac":"Scorpius","chineseZodiac":"Rooster","groupNameUpper":"LE SSERAFIM","positions":"Vocalist","counter":4,"nameUpper":"GARAM","zodiacId":8,"birthDate":20051116,"realName":"Kim Garam","idolId":103,"groupName":"LE SSERAFIM","chineseZodiacId":10,"fandom":"FEARNOT","imageFileName":"GARAM_LESSERAFIM","name":"Garam","age":16}
	,{"country":"South Korea","agency":"JYP Entertainment","counter2":1,"city":"Suwon","counter1":3,"zodiac":"Sagittarius","chineseZodiac":"Goat","groupNameUpper":"ITZY","positions":"Lead Rapper, Lead Dancer, Sub Vocalist, Visual, Maknae","counter":4,"nameUpper":"YUNA","zodiacId":9,"birthDate":20031209,"realName":"Shin Yuna","idolId":104,"groupName":"ITZY","chineseZodiacId":8,"fandom":"MIDZY","imageFileName":"YUNA_ITZY","name":"Yuna","age":18}
	,{"country":"South Korea","agency":"SM Entertainment","counter2":0,"city":"Busan","counter1":2,"zodiac":"Capricorn","chineseZodiac":"Snake","groupNameUpper":"AESPA","positions":"Lead Vocalist, Lead Dancer, Visual","counter":2,"nameUpper":"WINTER","zodiacId":10,"birthDate":20010101,"realName":"Kim Minjeong","idolId":105,"groupName":"aespa","chineseZodiacId":6,"fandom":"MY","imageFileName":"WINTER_AESPA","name":"Winter","age":21}
	,{"country":"Japan","agency":"Source Music","counter2":1,"city":"Kagoshima","counter1":0,"zodiac":"Pisces","chineseZodiac":"Tiger","groupNameUpper":"LE SSERAFIM","positions":"Vocalist","counter":1,"nameUpper":"SAKURA","zodiacId":12,"birthDate":19980319,"realName":"Miyawaki Sakura","idolId":106,"groupName":"LE SSERAFIM","chineseZodiacId":3,"fandom":"FEARNOT","imageFileName":"SAKURA_LESSERAFIM","name":"Sakura","age":24}
	,{"country":"South Korea","agency":"Source Music","counter2":1,"city":"Miryang/Gyeongsangnam-do","counter1":4,"zodiac":"Scorpius","chineseZodiac":"Dog","groupNameUpper":"LE SSERAFIM","positions":"Vocalist, Dancer, Maknae","counter":5,"nameUpper":"EUNCHAE","zodiacId":8,"birthDate":20061110,"realName":"Hong Eunchae","idolId":107,"groupName":"LE SSERAFIM","chineseZodiacId":11,"fandom":"FEARNOT","imageFileName":"EUNCHAE_LESSERAFIM","name":"Eunchae","age":15}
	,{"country":"China","agency":"WAKEONE and Swing Entertainment","counter2":8,"city":"Sichuan","counter1":19,"zodiac":"Scorpius","chineseZodiac":"Rabbit","groupNameUpper":"KEP1ER","positions":"(none)","counter":27,"nameUpper":"XIAOTING","zodiacId":8,"birthDate":19991112,"realName":"Shen Xiaoting","idolId":108,"groupName":"Kep1er","chineseZodiacId":4,"fandom":"Kep1ian","imageFileName":"XIAOTING_KEP1ER","name":"Xiaoting","age":22}
	,{"country":"South Korea","agency":"BlockBerryCreative","counter2":0,"city":"Cheongju","counter1":6,"zodiac":"Aquarius","chineseZodiac":"Rabbit","groupNameUpper":"LOONA","positions":"Leader, Vocalist, Dancer","counter":6,"nameUpper":"KIMLIP","zodiacId":11,"birthDate":19990210,"realName":"Kim Jungeun","idolId":109,"groupName":"LOONA","chineseZodiacId":4,"fandom":"Orbit","imageFileName":"KIMLIP_LOONA","name":"KimLip","age":23}
	,{"country":"South Korea","agency":"JYP Entertainment","counter2":0,"city":"Yangsan/Gyeongsangnam-do","counter1":3,"zodiac":"Capricorn","chineseZodiac":"Monkey","groupNameUpper":"NMIXX","positions":"Vocalist, Dancer","counter":3,"nameUpper":"BAE","zodiacId":10,"birthDate":20041228,"realName":"Bae Jinsol","idolId":110,"groupName":"NMIXX","chineseZodiacId":9,"fandom":"NSWER","imageFileName":"BAE_NMIXX","name":"Bae","age":17}
	,{"country":"China","agency":"FC ENM","counter2":13,"city":"(none)","counter1":6,"zodiac":"Gemini","chineseZodiac":"Horse","groupNameUpper":"ILY:1","positions":"Vocalist","counter":19,"nameUpper":"RONA","zodiacId":3,"birthDate":20020605,"realName":"Chang Ching","idolId":111,"groupName":"ily:1","chineseZodiacId":7,"fandom":"Only:1","imageFileName":"RONA_ILY1","name":"Rona","age":20}
	,{"country":"South Korea","agency":"WAKEONE and Swing Entertainment","counter2":0,"city":"Jeonju/North Jeolla","counter1":1,"zodiac":"Leo","chineseZodiac":"Rat","groupNameUpper":"KEP1ER","positions":"Leader","counter":1,"nameUpper":"YUJIN","zodiacId":5,"birthDate":19960812,"realName":"Choi Yujin","idolId":112,"groupName":"Kep1er","chineseZodiacId":1,"fandom":"Kep1ian","imageFileName":"YUJIN_KEP1ER","name":"Yujin","age":26}
	,{"country":"South Korea","agency":"BlockBerryCreative","counter2":0,"city":"Suncheon/South Jeolla","counter1":11,"zodiac":"Leo","chineseZodiac":"Ox","groupNameUpper":"LOONA","positions":"Leader, Vocalist, Rapper","counter":11,"nameUpper":"HASEUL","zodiacId":5,"birthDate":19970818,"realName":"Cho Haseul","idolId":113,"groupName":"LOONA","chineseZodiacId":2,"fandom":"Orbit","imageFileName":"HASEUL_LOONA","name":"Haseul","age":25}
	,{"country":"South Korea","agency":"MYSTIC Story","counter2":2,"city":"Gwangmyeong/Gyeonggi-do","counter1":2,"zodiac":"Aquarius","chineseZodiac":"Rooster","groupNameUpper":"BILLLIE","positions":"Main Rapper, Lead Dancer","counter":4,"nameUpper":"SIYOON","zodiacId":11,"birthDate":20050216,"realName":"Kim Siyoon","idolId":114,"groupName":"Billlie","chineseZodiacId":10,"fandom":"Belllie've","imageFileName":"SIYOON_BILLLIE","name":"Siyoon","age":17}
	,{"country":"Taiwan","agency":"FC ENM","counter2":0,"city":"(none)","counter1":1,"zodiac":"Taurus","chineseZodiac":"Goat","groupNameUpper":"ILY:1","positions":"Rapper, Maknae","counter":1,"nameUpper":"ELVA","zodiacId":2,"birthDate":20030505,"realName":"Lee Yonghwa","idolId":115,"groupName":"ily:1","chineseZodiacId":8,"fandom":"Only:1","imageFileName":"ELVA_ILY1","name":"Elva","age":19}
	,{"country":"South Korea","agency":"JYP Entertainment","counter2":1,"city":"Incheon","counter1":6,"zodiac":"Pisces","chineseZodiac":"Goat","groupNameUpper":"NMIXX","positions":"Leader, Vocalist","counter":7,"nameUpper":"HAEWON","zodiacId":12,"birthDate":20030225,"realName":"Oh Haewon","idolId":116,"groupName":"NMIXX","chineseZodiacId":8,"fandom":"NSWER","imageFileName":"HAEWON_NMIXX","name":"Haewon","age":19}
	,{"country":"South Korea","agency":"NV Entertainment","counter2":1,"city":"Seocho-gu/Seoul","counter1":4,"zodiac":"Aquarius","chineseZodiac":"Goat","groupNameUpper":"WOO!AH!","positions":"Lead Vocalist, Visual","counter":5,"nameUpper":"WOOYEON","zodiacId":11,"birthDate":20030211,"realName":"Park Jinkyung","idolId":117,"groupName":"woo!ah!","chineseZodiacId":8,"fandom":"wow!","imageFileName":"WOOYEON_WOOAH","name":"Wooyeon","age":19}
	,{"country":"South Korea","agency":"Starship Entertainment","counter2":2,"city":"Bupyeong-gu/Incheon","counter1":2,"zodiac":"Libra","chineseZodiac":"Horse","groupNameUpper":"IVE","positions":"Main Dancer, Rapper","counter":4,"nameUpper":"GAEUL","zodiacId":7,"birthDate":20020924,"realName":"Kim Gaeul","idolId":118,"groupName":"IVE","chineseZodiacId":7,"fandom":"DIVE","imageFileName":"GAEUL_IVE","name":"Gaeul","age":20}
	,{"country":"South Korea","agency":"Starship Entertainment","counter2":0,"city":"Cheongju/North Chungcheong","counter1":8,"zodiac":"Virgo","chineseZodiac":"Goat","groupNameUpper":"IVE","positions":"Leader, Main Dancer, Vocalist","counter":8,"nameUpper":"YUJIN","zodiacId":6,"birthDate":20030901,"realName":"Ahn Yujin","idolId":119,"groupName":"IVE","chineseZodiacId":8,"fandom":"DIVE","imageFileName":"YUJIN_IVE","name":"Yujin","age":19}
	,{"country":"South Korea","agency":"Woollim Entertainment","counter2":1,"city":"Seoul","counter1":3,"zodiac":"Libra","chineseZodiac":"Pig","groupNameUpper":"SOLOIST","positions":"(none)","counter":4,"nameUpper":"EUNBI","zodiacId":7,"birthDate":19950927,"realName":"Kwon Eunbi","idolId":120,"groupName":"soloist","chineseZodiacId":12,"fandom":"RUBI","imageFileName":"EUNBI_SOLOIST","name":"Eunbi","age":27}
	,{"country":"South Korea","agency":"M25","counter2":0,"city":"Sang-dong/Yeoju/Gyeonggi-do","counter1":2,"zodiac":"Capricorn","chineseZodiac":"Pig","groupNameUpper":"CLASS:Y","positions":"Lead Dancer, Vocalist","counter":2,"nameUpper":"RIWON","zodiacId":10,"birthDate":20070111,"realName":"Kim Riwon","idolId":121,"groupName":"CLASS:y","chineseZodiacId":12,"fandom":"CLIKE:y","imageFileName":"RIWON_CLASSY","name":"Riwon","age":15}
	,{"country":"South Korea","agency":"Yuehua Entertainment","counter2":1,"city":"Sambang-dong/Gimhae/Gyeongsangnam-do","counter1":0,"zodiac":"Capricorn","chineseZodiac":"Dragon","groupNameUpper":"EVERGLOW","positions":"Main Vocalist, Main Dancer, Sub Rapper","counter":1,"nameUpper":"MIA","zodiacId":10,"birthDate":20000113,"realName":"Han Eunji","idolId":122,"groupName":"Everglow","chineseZodiacId":5,"fandom":"For Ever","imageFileName":"MIA_EVERGLOW","name":"Mia","age":22}
	,{"country":"South Korea","agency":"Cube Entertainment","counter2":0,"city":"Chuncheon/Gangwon-do","counter1":4,"zodiac":"Sagittarius","chineseZodiac":"Horse","groupNameUpper":"LIGHTSUM","positions":"Main Vocalist, Lead Dancer, Center","counter":4,"nameUpper":"NAYOUNG","zodiacId":9,"birthDate":20021130,"realName":"Kim Nayoung","idolId":123,"groupName":"Lightsum","chineseZodiacId":7,"fandom":"SUMIT","imageFileName":"NAYOUNG_LIGHTSUM","name":"Nayoung","age":19}
	,{"country":"New Zeland","agency":"YG Entertainment","counter2":1,"city":"Auckland","counter1":0,"zodiac":"Aquarius","chineseZodiac":"Ox","groupNameUpper":"BLACKPINK","positions":"Main Vocalist, Lead Dancer","counter":1,"nameUpper":"ROSE","zodiacId":11,"birthDate":19970211,"realName":"Park Chaeyoung","idolId":124,"groupName":"Blackpink","chineseZodiacId":2,"fandom":"BLINK","imageFileName":"ROSE_BLACKPINK","name":"Rose","age":25}
	,{"country":"South Korea","agency":"RBW","counter2":0,"city":"(none)","counter1":2,"zodiac":"Cancer","chineseZodiac":"Goat","groupNameUpper":"PURPLE KISS","positions":"Main Vocalist, Maknae","counter":2,"nameUpper":"SWAN","zodiacId":4,"birthDate":20030711,"realName":"Park Sujin","idolId":125,"groupName":"Purple Kiss","chineseZodiacId":8,"fandom":"PLORY","imageFileName":"SWAN_PURPLEKISS","name":"Swan","age":19}
	,{"country":"South Korea","agency":"M25","counter2":0,"city":"Suwon/Gyeonggi-do","counter1":3,"zodiac":"Cancer","chineseZodiac":"Snake","groupNameUpper":"CLASS:Y","positions":"Lead Vocalist, Rapper, Visual","counter":3,"nameUpper":"HYUNGSEO","zodiacId":4,"birthDate":20010625,"realName":"Myeong Hyungseo","idolId":126,"groupName":"CLASS:y","chineseZodiacId":6,"fandom":"CLIKE:y","imageFileName":"HYUNGSEO_CLASSY","name":"Hyungseo","age":21}
	,{"country":"Japan","agency":"Source Music","counter2":1,"city":"Kochi","counter1":2,"zodiac":"Leo","chineseZodiac":"Goat","groupNameUpper":"LE SSERAFIM","positions":"Vocalist, Rapper, Dancer","counter":3,"nameUpper":"KAZUHA","zodiacId":5,"birthDate":20030809,"realName":"Nakamura Kazuha","idolId":127,"groupName":"LE SSERAFIM","chineseZodiacId":8,"fandom":"FEARNOT","imageFileName":"KAZUHA_LESSERAFIM","name":"Kazuha","age":19}
	,{"country":"South Korea","agency":"iMe Entertainment","counter2":1,"city":"Yeongju-si/North Gyeongsang","counter1":3,"zodiac":"Taurus","chineseZodiac":"Dragon","groupNameUpper":"DREAM NOTE","positions":"Leader, Lead Dancer, Lead Vocalist","counter":4,"nameUpper":"YOUI","zodiacId":2,"birthDate":20000424,"realName":"Kim Jihyeon","idolId":128,"groupName":"Dream Note","chineseZodiacId":5,"fandom":"Page","imageFileName":"YOUI_DREAMNOTE","name":"YOUI","age":22}
	,{"country":"South Korea","agency":"Starship Entertainment","counter2":3,"city":"Gwangmyung/Gyeonggi-do","counter1":1,"zodiac":"Leo","chineseZodiac":"Rabbit","groupNameUpper":"WJSN","positions":"Main Vocalist, Maknae","counter":4,"nameUpper":"YEONJUNG","zodiacId":5,"birthDate":19990803,"realName":"Yoo Yeonjung","idolId":129,"groupName":"WJSN","chineseZodiacId":4,"fandom":"Ujung","imageFileName":"YEONJUNG_WJSN","name":"Yeonjung","age":23}
	,{"country":"South Korea","agency":"Starship Entertainment","counter2":1,"city":"Seoul","counter1":2,"zodiac":"Capricorn","chineseZodiac":"Rabbit","groupNameUpper":"WJSN","positions":"Main Dancer, Vocalist, Rapper","counter":3,"nameUpper":"YEOREUM","zodiacId":10,"birthDate":19990110,"realName":"Lee Jinsuk","idolId":130,"groupName":"WJSN","chineseZodiacId":4,"fandom":"Ujung","imageFileName":"YEOREUM_WJSN","name":"Yeoreum","age":23}
	,{"country":"South Korea","agency":"Source Music","counter2":1,"city":"Gangnam-gu/Seoul","counter1":10,"zodiac":"Scorpius","chineseZodiac":"Snake","groupNameUpper":"LE SSERAFIM","positions":"Vocalist","counter":11,"nameUpper":"YUNJIN","zodiacId":8,"birthDate":20011108,"realName":"Huh Yunjin","idolId":131,"groupName":"LE SSERAFIM","chineseZodiacId":6,"fandom":"FEARNOT","imageFileName":"YUNJIN_LESSERAFIM","name":"Yunjin","age":20}
	,{"country":"South Korea","agency":"KM Entertainment","counter2":0,"city":"Wonju/Gangwon","counter1":5,"zodiac":"Aquarius","chineseZodiac":"Monkey","groupNameUpper":"ICHILLIN","positions":"Lead Dancer, Sub Vocalist, Center","counter":5,"nameUpper":"YEJU","zodiacId":11,"birthDate":20040201,"realName":"Kim Yeju","idolId":132,"groupName":"ichillin","chineseZodiacId":9,"fandom":"Willing","imageFileName":"YEJU_ICHILLIN","name":"Yeju","age":18}
	,{"country":"USA","agency":"KM Entertainment","counter2":0,"city":"Los Angeles/California","counter1":4,"zodiac":"Scorpius","chineseZodiac":"Snake","groupNameUpper":"ICHILLIN","positions":"Main Rapper, Lead Dancer","counter":4,"nameUpper":"JACKIE","zodiacId":8,"birthDate":20011117,"realName":"Kang Chaeyeon/Jackeline Kang","idolId":133,"groupName":"ichillin","chineseZodiacId":6,"fandom":"Willing","imageFileName":"JACKIE_ICHILLIN","name":"Jackie","age":20}
	,{"country":"South Korea","agency":"Source Music","counter2":1,"city":"Incheon","counter1":1,"zodiac":"Leo","chineseZodiac":"Rat","groupNameUpper":"GFRIEND","positions":"Lead Dancer, Vocalist, Center, Face of the Group","counter":2,"nameUpper":"YERIN","zodiacId":5,"birthDate":19960819,"realName":"Jung Yerin","idolId":134,"groupName":"Gfriend","chineseZodiacId":1,"fandom":"BUDDY","imageFileName":"YERIN_GFRIEND","name":"Yerin","age":26}
	,{"country":"South Korea","agency":"Dreamcatcher Company","counter2":6,"city":"Changwon","counter1":1,"zodiac":"Leo","chineseZodiac":"Dog","groupNameUpper":"DREAMCATCHER","positions":"Main Dancer, Sub Vocalist, Lead Rapper","counter":7,"nameUpper":"SUA","zodiacId":5,"birthDate":19940810,"realName":"Kim Bora","idolId":135,"groupName":"Dreamcatcher","chineseZodiacId":11,"fandom":"InSomnia","imageFileName":"SUA_DREAMCATCHER","name":"Sua","age":28}
	,{"country":"South Korea","agency":"KM Entertainment","counter2":0,"city":"Yeongwol/Gangwon-do","counter1":1,"zodiac":"Capricorn","chineseZodiac":"Monkey","groupNameUpper":"ICHILLIN","positions":"Sub Vocalist, Sub Dancer","counter":1,"nameUpper":"SOHEE","zodiacId":10,"birthDate":20040101,"realName":"Um Sohee","idolId":136,"groupName":"ichillin","chineseZodiacId":9,"fandom":"Willing","imageFileName":"SOHEE_ICHILLIN","name":"Sohee","age":18}
	,{"country":"South Korea","agency":"Cube Entertainment","counter2":0,"city":"Seoul","counter1":2,"zodiac":"Aries","chineseZodiac":"Monkey","groupNameUpper":"LIGHTSUM","positions":"Leader, Main Dancer, Lead Vocalist","counter":2,"nameUpper":"JUHYEON","zodiacId":1,"birthDate":20040408,"realName":"Lee Juhyeon","idolId":137,"groupName":"Lightsum","chineseZodiacId":9,"fandom":"SUMIT","imageFileName":"JUHYEON_LIGHTSUM","name":"Juhyeon","age":18}
	,{"country":"South Korea","agency":"M25","counter2":4,"city":"Deokpung-dong/Hanam","counter1":3,"zodiac":"Gemini","chineseZodiac":"Goat","groupNameUpper":"CLASS:Y","positions":"Main Vocalist","counter":7,"nameUpper":"CHAEWON","zodiacId":3,"birthDate":20030604,"realName":"Yoon Chaewon","idolId":138,"groupName":"CLASS:y","chineseZodiacId":8,"fandom":"CLIKE:y","imageFileName":"CHAEWON_CLASSY","name":"Chaewon","age":19}
	,{"country":"South Korea","agency":"M25","counter2":3,"city":"Bangok-dong/Wonju/Gangwon-do","counter1":5,"zodiac":"Leo","chineseZodiac":"Pig","groupNameUpper":"CLASS:Y","positions":"Main Vocalist, Center","counter":8,"nameUpper":"JIMIN","zodiacId":5,"birthDate":20070725,"realName":"Won Jimin","idolId":139,"groupName":"CLASS:y","chineseZodiacId":12,"fandom":"CLIKE:y","imageFileName":"JIMIN_CLASSY","name":"Jimin","age":15}
	,{"country":"South Korea","agency":"Source Music","counter2":5,"city":"Seoul","counter1":7,"zodiac":"Leo","chineseZodiac":"Dragon","groupNameUpper":"LE SSERAFIM","positions":"Leader, Vocalist","counter":12,"nameUpper":"CHAEWON","zodiacId":5,"birthDate":20000801,"realName":"Kim Chaewon","idolId":140,"groupName":"LE SSERAFIM","chineseZodiacId":5,"fandom":"FEARNOT","imageFileName":"CHAEWON_LESSERAFIM","name":"Chaewon","age":22}
	,{"country":"South Korea","agency":"iMe Entertainment","counter2":0,"city":"Gwangsan-gu/Gwangju","counter1":2,"zodiac":"Leo","chineseZodiac":"Dragon","groupNameUpper":"DREAM NOTE","positions":"Main Vocalist","counter":2,"nameUpper":"LARA","zodiacId":5,"birthDate":20000809,"realName":"Moon Sinae","idolId":141,"groupName":"Dream Note","chineseZodiacId":5,"fandom":"Page","imageFileName":"LARA_DREAMNOTE","name":"Lara","age":22}
	,{"country":"Japan","agency":"WAKEONE and Swing Entertainment","counter2":0,"city":"Fukuoka","counter1":1,"zodiac":"Pisces","chineseZodiac":"Monkey","groupNameUpper":"KEP1ER","positions":"(none)","counter":1,"nameUpper":"HIKARU","zodiacId":12,"birthDate":20040312,"realName":"Ezaki Hikaru","idolId":142,"groupName":"Kep1er","chineseZodiacId":9,"fandom":"Kep1ian","imageFileName":"HIKARU_KEP1ER","name":"Hikaru","age":18}
	,{"country":"South Korea","agency":"M25","counter2":0,"city":"Songpa-gu/Seoul","counter1":2,"zodiac":"Sagittarius","chineseZodiac":"Goat","groupNameUpper":"CLASS:Y","positions":"Leader, Main Dancer, Lead Rapper, Vocalist","counter":2,"nameUpper":"HYEJU","zodiacId":9,"birthDate":20031209,"realName":"Hong Hyeju","idolId":143,"groupName":"CLASS:y","chineseZodiacId":8,"fandom":"CLIKE:y","imageFileName":"HYEJU_CLASSY","name":"Hyeju","age":18}
	,{"country":"South Korea","agency":"Cube Entertainment","counter2":0,"city":"Eunpyeong-gu/Seoul","counter1":1,"zodiac":"Virgo","chineseZodiac":"Horse","groupNameUpper":"LIGHTSUM","positions":"Main Vocalist","counter":1,"nameUpper":"CHOWON","zodiacId":6,"birthDate":20020916,"realName":"Han Chowon","idolId":144,"groupName":"Lightsum","chineseZodiacId":7,"fandom":"SUMIT","imageFileName":"CHOWON_LIGHTSUM","name":"Chowon","age":20}
	,{"country":"Japan","agency":"FC ENM","counter2":0,"city":"Osaka","counter1":1,"zodiac":"Cancer","chineseZodiac":"Horse","groupNameUpper":"ILY:1","positions":"Lead Vocalist","counter":1,"nameUpper":"RIRIKA","zodiacId":4,"birthDate":20020702,"realName":"Kishida Ririka","idolId":145,"groupName":"ily:1","chineseZodiacId":7,"fandom":"Only:1","imageFileName":"RIRIKA_ILY1","name":"Ririka","age":20}
	,{"country":"South Korea","agency":"MLD Entertainment","counter2":1,"city":"Seoul","counter1":1,"zodiac":"Leo","chineseZodiac":"Rabbit","groupNameUpper":"MOMOLAND","positions":"Lead Vocalist, Lead Dancer, Rapper, Face of the Group","counter":2,"nameUpper":"JOOE","zodiacId":5,"birthDate":19990818,"realName":"Lee Joowon","idolId":146,"groupName":"Momoland","chineseZodiacId":4,"fandom":"Merry Go Round","imageFileName":"JOOE_MOMOLAND","name":"Jooe","age":23}
	,{"country":"South Korea","agency":"MLD Entertainment","counter2":1,"city":"Wonju","counter1":1,"zodiac":"Libra","chineseZodiac":"Rabbit","groupNameUpper":"MOMOLAND","positions":"Main Vocalist","counter":2,"nameUpper":"AHIN","zodiacId":7,"birthDate":19990927,"realName":"Lee Ahin","idolId":147,"groupName":"Momoland","chineseZodiacId":4,"fandom":"Merry Go Round","imageFileName":"AHIN_MOMOLAND","name":"Ahin","age":23}
	,{"country":"South Korea","agency":"MLD Entertainment","counter2":2,"city":"Daegu","counter1":2,"zodiac":"Aries","chineseZodiac":"Dragon","groupNameUpper":"MOMOLAND","positions":"Lead Vocalist, Lead Dancer, Visual, Center, Maknae","counter":4,"nameUpper":"NANCY","zodiacId":1,"birthDate":20000413,"realName":"Nancy Jewel Mcdonie","idolId":148,"groupName":"Momoland","chineseZodiacId":5,"fandom":"Merry Go Round","imageFileName":"NANCY_MOMOLAND","name":"Nancy","age":22}
	,{"country":"South Korea","agency":"BlockBerryCreative","counter2":0,"city":"Incheon","counter1":2,"zodiac":"Scorpius","chineseZodiac":"Dragon","groupNameUpper":"LOONA","positions":"Rapper, Dancer, Vocalist","counter":2,"nameUpper":"GOWON","zodiacId":8,"birthDate":20001119,"realName":"Park Chaewon","idolId":149,"groupName":"LOONA","chineseZodiacId":5,"fandom":"Orbit","imageFileName":"GOWON_LOONA","name":"Gowon","age":21}
	,{"country":"South Korea","agency":"ALLART Entertainment","counter2":2,"city":"Busan","counter1":1,"zodiac":"Pisces","chineseZodiac":"Snake","groupNameUpper":"PIXY","positions":"Main Rapper, Visual","counter":3,"nameUpper":"LOLA","zodiacId":12,"birthDate":20010222,"realName":"Choi Yoojung","idolId":150,"groupName":"Pixy","chineseZodiacId":6,"fandom":"Winxy","imageFileName":"LOLA_PIXY","name":"Lola","age":21}
	,{"country":"South Korea","agency":"Pledis Entertainment","counter2":0,"city":"Seoul","counter1":2,"zodiac":"Sagittarius","chineseZodiac":"Tiger","groupNameUpper":"FROMIS_9","positions":"Lead Dancer, Vocalist, Center","counter":2,"nameUpper":"JISUN","zodiacId":9,"birthDate":19981122,"realName":"Roh Jisun","idolId":151,"groupName":"fromis_9","chineseZodiacId":3,"fandom":"Flover","imageFileName":"JISUN_FROMIS9","name":"Jisun","age":23}
	,{"country":"South Korea","agency":"WAKEONE Entertainment","counter2":0,"city":"Busan","counter1":2,"zodiac":"Libra","chineseZodiac":"Snake","groupNameUpper":"SOLOIST","positions":"(none)","counter":2,"nameUpper":"YURI","zodiacId":7,"birthDate":20011022,"realName":"Jo Yuri","idolId":152,"groupName":"soloist","chineseZodiacId":6,"fandom":"GLASSY","imageFileName":"YURI_SOLOIST","name":"Yuri","age":20}
	,{"country":"South Korea","agency":"M25","counter2":1,"city":"Gangneung/Gangwon-do","counter1":0,"zodiac":"Pisces","chineseZodiac":"Rat","groupNameUpper":"CLASS:Y","positions":"Main Rapper, Lead Dancer, Vocalist, Maknae","counter":1,"nameUpper":"SEONYU","zodiacId":12,"birthDate":20080320,"realName":"Kim Seonyu","idolId":153,"groupName":"CLASS:y","chineseZodiacId":1,"fandom":"CLIKE:y","imageFileName":"SEONYU_CLASSY","name":"Seonyu","age":14}
	,{"country":"South Korea","agency":"JYP Entertainment","counter2":0,"city":"Seoul","counter1":2,"zodiac":"Virgo","chineseZodiac":"Pig","groupNameUpper":"TWICE","positions":"Lead Vocalist, Lead Dancer, Center, Face of the Group","counter":2,"nameUpper":"NAYEON","zodiacId":6,"birthDate":19950922,"realName":"Im Nayeon","idolId":154,"groupName":"Twice","chineseZodiacId":12,"fandom":"ONCE","imageFileName":"NAYEON_TWICE","name":"Nayeon","age":27}
	,{"country":"South Korea","agency":"BlockBerryCreative","counter2":0,"city":"Uijeongbu","counter1":3,"zodiac":"Scorpius","chineseZodiac":"Snake","groupNameUpper":"LOONA","positions":"Dancer, Rapper, Vocalist","counter":3,"nameUpper":"OLIVIA HYE","zodiacId":8,"birthDate":20011113,"realName":"Son Hyeju","idolId":155,"groupName":"LOONA","chineseZodiacId":6,"fandom":"Orbit","imageFileName":"OLIVIAHYE_LOONA","name":"Olivia Hye","age":20}
	,{"country":"China","agency":"BlockBerryCreative","counter2":0,"city":"Tuen Mun/Hong Kong","counter1":1,"zodiac":"Sagittarius","chineseZodiac":"Rat","groupNameUpper":"LOONA","positions":"Vocalist, Rapper","counter":1,"nameUpper":"VIVI","zodiacId":9,"birthDate":19961209,"realName":"Wong Gaahei","idolId":156,"groupName":"LOONA","chineseZodiacId":1,"fandom":"Orbit","imageFileName":"VIVI_LOONA","name":"Vivi","age":25}
	,{"country":"South Korea","agency":"Starship Entertainment","counter2":0,"city":"Incheon","counter1":1,"zodiac":"Gemini","chineseZodiac":"Tiger","groupNameUpper":"WJSN","positions":"Vocalist, Rapper","counter":1,"nameUpper":"EUNSEO","zodiacId":3,"birthDate":19980527,"realName":"Son Juyeon","idolId":157,"groupName":"WJSN","chineseZodiacId":3,"fandom":"Ujung","imageFileName":"EUNSEO_WJSN","name":"Eunseo","age":24}
	,{"country":"South Korea","agency":"Starship Entertainment","counter2":0,"city":"Seoul","counter1":1,"zodiac":"Capricorn","chineseZodiac":"Dog","groupNameUpper":"WJSN","positions":"Lead Vocalist","counter":1,"nameUpper":"SEOLA","zodiacId":10,"birthDate":19941224,"realName":"Kim Hyunjung","idolId":158,"groupName":"WJSN","chineseZodiacId":11,"fandom":"Ujung","imageFileName":"SEOLA_WJSN","name":"Seola","age":27}
	,{"country":"Japan","agency":"MLD Entertainment","counter2":2,"city":"Kochi","counter1":1,"zodiac":"Pisces","chineseZodiac":"Goat","groupNameUpper":"LAPILLUS","positions":"Leader, Vocalist","counter":3,"nameUpper":"SHANA","zodiacId":12,"birthDate":20030313,"realName":"Nonaka Shana","idolId":159,"groupName":"Lapillus","chineseZodiacId":8,"fandom":"(none)","imageFileName":"SHANA_LAPILLUS","name":"Shana","age":19}
	,{"country":"South Korea","agency":"Yuehua Entertainment","counter2":0,"city":"Hanam/Gyeonggi-do","counter1":1,"zodiac":"Taurus","chineseZodiac":"Tiger","groupNameUpper":"EVERGLOW","positions":"Main Rapper, Main Dancer","counter":1,"nameUpper":"E:U","zodiacId":2,"birthDate":19980519,"realName":"Park Jiwon","idolId":160,"groupName":"Everglow","chineseZodiacId":3,"fandom":"For Ever","imageFileName":"EU_EVERGLOW","name":"E:U","age":24}
	,{"country":"South Korea","agency":"ALLART Entertainment","counter2":0,"city":"Busan","counter1":2,"zodiac":"Pisces","chineseZodiac":"Goat","groupNameUpper":"PIXY","positions":"Sub Vocalist","counter":2,"nameUpper":"SUA","zodiacId":12,"birthDate":20030224,"realName":"Choi Sua","idolId":161,"groupName":"Pixy","chineseZodiacId":8,"fandom":"Winxy","imageFileName":"SUA_PIXY","name":"Sua","age":19}
	,{"country":"South Korea","agency":"Grandline Group (GLG)","counter2":0,"city":"(none)","counter1":2,"zodiac":"Capricorn","chineseZodiac":"Monkey","groupNameUpper":"H1-KEY","positions":"Vocalist, Rapper, Maknae","counter":2,"nameUpper":"YEL","zodiacId":10,"birthDate":20041225,"realName":"Han Shinyoung","idolId":162,"groupName":"H1-KEY","chineseZodiacId":9,"fandom":"M1-KEY","imageFileName":"YEL_H1KEY","name":"Yel","age":17}
	,{"country":"South Korea","agency":"BlockBerryCreative","counter2":0,"city":"Chungju","counter1":3,"zodiac":"Libra","chineseZodiac":"Rabbit","groupNameUpper":"LOONA","positions":"Vocalist, Rapper, Face of the Group","counter":3,"nameUpper":"CHUU","zodiacId":7,"birthDate":19991020,"realName":"Kim Jiwoo","idolId":163,"groupName":"LOONA","chineseZodiacId":4,"fandom":"Orbit","imageFileName":"CHUU_LOONA","name":"Chuu","age":22}
	,{"country":"South Korea","agency":"FNC Entertainment","counter2":0,"city":"Seoul","counter1":1,"zodiac":"Virgo","chineseZodiac":"Dragon","groupNameUpper":"CHERRY BULLET","positions":"Lead Vocalist, Rapper, Visual, Center","counter":1,"nameUpper":"JIWON","zodiacId":6,"birthDate":20000904,"realName":"Heo Jiwon","idolId":164,"groupName":"Cherry Bullet","chineseZodiacId":5,"fandom":"Lullet","imageFileName":"JIWON_CHERRYBULLET","name":"Jiwon","age":22}
	,{"country":"South Korea","agency":"WAKEONE and Swing Entertainment","counter2":0,"city":"Yeonje-gu/Busan","counter1":1,"zodiac":"Taurus","chineseZodiac":"Horse","groupNameUpper":"KEP1ER","positions":"Center","counter":1,"nameUpper":"CHAEHYUN","zodiacId":2,"birthDate":20020426,"realName":"Kim Chaehyun","idolId":165,"groupName":"Kep1er","chineseZodiacId":7,"fandom":"Kep1ian","imageFileName":"CHAEHYUN_KEP1ER","name":"Chaehyun","age":20}
	,{"country":"South Korea","agency":"Yuehua Entertainment","counter2":0,"city":"Gil-dong/Gangdong/Seoul","counter1":1,"zodiac":"Libra","chineseZodiac":"Rabbit","groupNameUpper":"SOLOIST","positions":"(none)","counter":1,"nameUpper":"YENA","zodiacId":7,"birthDate":19990929,"realName":"Choi Yena","idolId":166,"groupName":"soloist","chineseZodiacId":4,"fandom":"JIGUMI","imageFileName":"YENA_SOLOIST","name":"Yena","age":23}
	,{"country":"South Korea","agency":"Grandline Group (GLG)","counter2":0,"city":"Dongjak-gu/Seoul","counter1":2,"zodiac":"Pisces","chineseZodiac":"Snake","groupNameUpper":"H1-KEY","positions":"Vocalist","counter":2,"nameUpper":"RIINA","zodiacId":12,"birthDate":20010221,"realName":"Lee Seunghyun","idolId":167,"groupName":"H1-KEY","chineseZodiacId":6,"fandom":"M1-KEY","imageFileName":"RIINA_H1KEY","name":"Riina","age":21}
	,{"country":"South Korea","agency":"JYP Entertainment","counter2":1,"city":"Yongin","counter1":5,"zodiac":"Gemini","chineseZodiac":"Snake","groupNameUpper":"ITZY","positions":"Main Dancer, Sub Vocalist, Sub Rapper","counter":6,"nameUpper":"CHAERYEONG","zodiacId":3,"birthDate":20010605,"realName":"Lee Chaeryeong","idolId":168,"groupName":"ITZY","chineseZodiacId":6,"fandom":"MIDZY","imageFileName":"CHAERYEONG_ITZY","name":"Chaeryeong","age":21}
	,{"country":"South Korea","agency":"A team Entertainment","counter2":1,"city":"Hwasun/South Jeolla","counter1":0,"zodiac":"Leo","chineseZodiac":"Snake","groupNameUpper":"BUGABOO","positions":"Leader, Main Dancer, Vocalist, Rapper","counter":1,"nameUpper":"CHOYEON","zodiacId":5,"birthDate":20010801,"realName":"Kim Choyeon","idolId":169,"groupName":"bugAboo","chineseZodiacId":6,"fandom":"RAINBOO","imageFileName":"CHOYEON_BUGABOO","name":"Choyeon","age":21}
	,{"country":"South Korea","agency":"Pop Music","counter2":1,"city":"(none)","counter1":1,"zodiac":"Taurus","chineseZodiac":"Rooster","groupNameUpper":"CSR","positions":"(none)","counter":2,"nameUpper":"DUNA","zodiacId":2,"birthDate":20050428,"realName":"Kang Duna","idolId":170,"groupName":"CSR","chineseZodiacId":10,"fandom":"(none)","imageFileName":"DUNA_CSR","name":"Duna","age":17}
	,{"country":"South Korea","agency":"Starship Entertainment","counter2":0,"city":"Seoul","counter1":2,"zodiac":"Pisces","chineseZodiac":"Ox","groupNameUpper":"WJSN","positions":"Vocalist, Rapper","counter":2,"nameUpper":"LUDA","zodiacId":12,"birthDate":19970306,"realName":"Lee Luda","idolId":171,"groupName":"WJSN","chineseZodiacId":2,"fandom":"Ujung","imageFileName":"LUDA_WJSN","name":"Luda","age":25}
	,{"country":"South Korea","agency":"M25","counter2":0,"city":"Beomseo-eup/Ulju-gun/Ulsan","counter1":2,"zodiac":"Aquarius","chineseZodiac":"Rat","groupNameUpper":"CLASS:Y","positions":"Lead Vocalist","counter":2,"nameUpper":"BOEUN","zodiacId":11,"birthDate":20080211,"realName":"Park Boeun","idolId":172,"groupName":"CLASS:y","chineseZodiacId":1,"fandom":"CLIKE:y","imageFileName":"BOEUN_CLASSY","name":"Boeun","age":14}
	,{"country":"South Korea","agency":"Pop Music","counter2":0,"city":"(none)","counter1":4,"zodiac":"Pisces","chineseZodiac":"Rooster","groupNameUpper":"CSR","positions":"(none)","counter":4,"nameUpper":"SIHYEON","zodiacId":12,"birthDate":20050312,"realName":"Hwang Sihyeon","idolId":173,"groupName":"CSR","chineseZodiacId":10,"fandom":"(none)","imageFileName":"SIHYEON_CSR","name":"Sihyeon","age":17}
	,{"country":"South Korea","agency":"KM Entertainment","counter2":0,"city":"Boryeong/Chungcheongnam-do","counter1":1,"zodiac":"Leo","chineseZodiac":"Rooster","groupNameUpper":"ICHILLIN","positions":"Main Dancer, Sub Vocalist, Maknae","counter":1,"nameUpper":"CHOWON","zodiacId":5,"birthDate":20050818,"realName":"Kim Chowon","idolId":174,"groupName":"ichillin","chineseZodiacId":10,"fandom":"Willing","imageFileName":"CHOWON_ICHILLIN","name":"Chowon","age":17}
	,{"country":"South Korea","agency":"MLD Entertainment","counter2":1,"city":"(none)","counter1":2,"zodiac":"Scorpius","chineseZodiac":"Rat","groupNameUpper":"LAPILLUS","positions":"Dancer, Vocalist, Center, Maknae","counter":3,"nameUpper":"HAEUN","zodiacId":8,"birthDate":20081102,"realName":"Lim Haeun","idolId":175,"groupName":"Lapillus","chineseZodiacId":1,"fandom":"(none)","imageFileName":"HAEUN_LAPILLUS","name":"Haeun","age":13}
	,{"country":"Japan","agency":"NV Entertainment","counter2":0,"city":"Fukuoka","counter1":1,"zodiac":"Virgo","chineseZodiac":"Goat","groupNameUpper":"WOO!AH!","positions":"Vocalist, Rapper","counter":1,"nameUpper":"SORA","zodiacId":6,"birthDate":20030830,"realName":"Sakata Sora","idolId":176,"groupName":"woo!ah!","chineseZodiacId":8,"fandom":"wow!","imageFileName":"SORA_WOOAH","name":"Sora","age":19}
	,{"country":"South Korea","agency":"KM Entertainment","counter2":0,"city":"Bupyeong-gu/Incheon","counter1":1,"zodiac":"Scorpius","chineseZodiac":"Dragon","groupNameUpper":"ICHILLIN","positions":"Leader, Main Dancer, Sub Vocalist","counter":1,"nameUpper":"E.JI","zodiacId":8,"birthDate":20001108,"realName":"Choi Jiwon","idolId":177,"groupName":"ichillin","chineseZodiacId":5,"fandom":"Willing","imageFileName":"EJI_ICHILLIN","name":"E.JI","age":21}
	,{"country":"South Korea","agency":"Pop Music","counter2":0,"city":"Anyang/Gyeonggi-do","counter1":1,"zodiac":"Leo","chineseZodiac":"Rooster","groupNameUpper":"CSR","positions":"Leader","counter":1,"nameUpper":"SUA","zodiacId":5,"birthDate":20050723,"realName":"Yoo Sua","idolId":178,"groupName":"CSR","chineseZodiacId":10,"fandom":"(none)","imageFileName":"SUA_CSR","name":"Sua","age":17}
	,{"country":"South Korea","agency":"YG Entertainment","counter2":5,"city":"Cheongdam-dong/Seoul","counter1":0,"zodiac":"Capricorn","chineseZodiac":"Rat","groupNameUpper":"BLACKPINK","positions":"Main Rapper, Lead Vocalist","counter":5,"nameUpper":"JENNIE","zodiacId":10,"birthDate":19960116,"realName":"Kim Jennie","idolId":179,"groupName":"Blackpink","chineseZodiacId":1,"fandom":"BLINK","imageFileName":"JENNIE_BLACKPINK","name":"Jennie","age":26}
	,{"country":"Taiwan","agency":"TR Entertainment","counter2":2,"city":"Kaohsiung","counter1":1,"zodiac":"Capricorn","chineseZodiac":"Horse","groupNameUpper":"TRI.BE","positions":"Lead Vocalist, Visual","counter":3,"nameUpper":"KELLY","zodiacId":10,"birthDate":20020116,"realName":"Lin Weixi","idolId":180,"groupName":"TRI.BE","chineseZodiacId":7,"fandom":"TRUE","imageFileName":"KELLY_TRIBE","name":"Kelly","age":20}
	,{"country":"South Korea","agency":"IST Entertainment","counter2":0,"city":"Bundang-gu/Seongnam/Gyeonggi-do","counter1":1,"zodiac":"Pisces","chineseZodiac":"Horse","groupNameUpper":"WEEEKLY","positions":"Lead Vocalist, Sub Rapper","counter":1,"nameUpper":"JIYOON","zodiacId":12,"birthDate":20020302,"realName":"Shin Jiyoon","idolId":181,"groupName":"Weeekly","chineseZodiacId":7,"fandom":"Daileee","imageFileName":"JIYOON_WEEEKLY","name":"Jiyoon","age":20}
	,{"country":"South Korea","agency":"A team Entertainment","counter2":0,"city":"Incheon","counter1":2,"zodiac":"Virgo","chineseZodiac":"Snake","groupNameUpper":"BUGABOO","positions":"Main Vocalist, Maknae","counter":2,"nameUpper":"ZIN","zodiacId":6,"birthDate":20010830,"realName":"Jin Hyunbin","idolId":182,"groupName":"bugAboo","chineseZodiacId":6,"fandom":"RAINBOO","imageFileName":"ZIN_BUGABOO","name":"Zin","age":21}
	,{"country":"South Korea","agency":"Woollim Entertainment","counter2":0,"city":"Bundang-gu/Seongnam-si","counter1":1,"zodiac":"Taurus","chineseZodiac":"Rooster","groupNameUpper":"ROCKET PUNCH","positions":"Vocalist, Dancer, Maknae","counter":1,"nameUpper":"DAHYUN","zodiacId":2,"birthDate":20050429,"realName":"Jeong Dahyun","idolId":183,"groupName":"Rocket Punch","chineseZodiacId":10,"fandom":"KETCHY","imageFileName":"DAHYUN_ROCKETPUNCH","name":"Dahyun","age":17}
	,{"country":"South Korea","agency":"Pledis Entertainment","counter2":0,"city":"Seoul","counter1":1,"zodiac":"Aquarius","chineseZodiac":"Dragon","groupNameUpper":"FROMIS_9","positions":"Main Rapper, Vocalist","counter":1,"nameUpper":"SEOYEON","zodiacId":11,"birthDate":20000122,"realName":"Lee Seoyeon","idolId":184,"groupName":"fromis_9","chineseZodiacId":5,"fandom":"Flover","imageFileName":"SEOYEON_FROMIS9","name":"Seoyeon","age":22}
	,{"country":"South Korea","agency":"WAKEONE and Swing Entertainment","counter2":1,"city":"(none)","counter1":0,"zodiac":"Leo","chineseZodiac":"Monkey","groupNameUpper":"KEP1ER","positions":"(none)","counter":1,"nameUpper":"BAHIYYIH","zodiacId":5,"birthDate":20040727,"realName":"Bahiyyih Jaleh Huening","idolId":185,"groupName":"Kep1er","chineseZodiacId":9,"fandom":"Kep1ian","imageFileName":"BAHIYYIH_KEP1ER","name":"Bahiyyih","age":18}
	,{"country":"South Korea","agency":"A team Entertainment","counter2":0,"city":"Pohang/Gyeongsangbuk-do","counter1":1,"zodiac":"Libra","chineseZodiac":"Rabbit","groupNameUpper":"BUGABOO","positions":"Main Rapper, Main Dancer, Vocalist","counter":1,"nameUpper":"EUNCHAE","zodiacId":7,"birthDate":19991006,"realName":"Son Eunchae","idolId":186,"groupName":"bugAboo","chineseZodiacId":4,"fandom":"RAINBOO","imageFileName":"EUNCHAE_BUGABOO","name":"Eunchae","age":23}
	,{"country":"USA","agency":"MLD Entertainment","counter2":0,"city":"California","counter1":2,"zodiac":"Cancer","chineseZodiac":"Monkey","groupNameUpper":"LAPILLUS","positions":"Vocalist, Dancer","counter":2,"nameUpper":"YUE","zodiacId":4,"birthDate":20040703,"realName":"Nancy Yang","idolId":187,"groupName":"Lapillus","chineseZodiacId":9,"fandom":"(none)","imageFileName":"YUE_LAPILLUS","name":"Yue","age":18}
	,{"country":"South Korea","agency":"Pop Music","counter2":0,"city":"(none)","counter1":1,"zodiac":"Pisces","chineseZodiac":"Rooster","groupNameUpper":"CSR","positions":"(none)","counter":1,"nameUpper":"GEUMHEE","zodiacId":12,"birthDate":20050304,"realName":"Han Geumhee","idolId":188,"groupName":"CSR","chineseZodiacId":10,"fandom":"(none)","imageFileName":"GEUMHEE_CSR","name":"Geumhee","age":17}
	,{"country":"South Korea","agency":"FC ENM","counter2":1,"city":"(none)","counter1":0,"zodiac":"Leo","chineseZodiac":"Horse","groupNameUpper":"ILY:1","positions":"Leader, Main Vocalist","counter":1,"nameUpper":"NAYU","zodiacId":5,"birthDate":20020723,"realName":"Kim Yewon","idolId":189,"groupName":"ily:1","chineseZodiacId":7,"fandom":"Only:1","imageFileName":"NAYU_ILY1","name":"Nayu","age":20}
	,{"country":"Vietnam","agency":"ADOR","counter2":0,"city":"(none)","counter1":1,"zodiac":"Libra","chineseZodiac":"Monkey","groupNameUpper":"NEWJEANS","positions":"(none)","counter":1,"nameUpper":"HANNI","zodiacId":7,"birthDate":20041006,"realName":"Hanni Pham/Pham Ngoc Han","idolId":190,"groupName":"NewJeans","chineseZodiacId":9,"fandom":"(none)","imageFileName":"HANNI_NEWJEANS","name":"Hanni","age":18}
	,{"country":"South Korea","agency":"ADOR","counter2":0,"city":"Incheon","counter1":2,"zodiac":"Taurus","chineseZodiac":"Rat","groupNameUpper":"NEWJEANS","positions":"Maknae","counter":2,"nameUpper":"HYEIN","zodiacId":2,"birthDate":20080421,"realName":"Lee Hyein","idolId":191,"groupName":"NewJeans","chineseZodiacId":1,"fandom":"(none)","imageFileName":"HYEIN_NEWJEANS","name":"Hyein","age":14}
	,{"country":"Australia","agency":"ADOR","counter2":1,"city":"(none)","counter1":2,"zodiac":"Aries","chineseZodiac":"Rooster","groupNameUpper":"NEWJEANS","positions":"(none)","counter":3,"nameUpper":"DANIELLE","zodiacId":1,"birthDate":20050411,"realName":"Danielle Marsh/Mo Jihye","idolId":192,"groupName":"NewJeans","chineseZodiacId":10,"fandom":"(none)","imageFileName":"DANIELLE_NEWJEANS","name":"Danielle","age":17}
	,{"country":"South Korea","agency":"ADOR","counter2":1,"city":"(none)","counter1":2,"zodiac":"Taurus","chineseZodiac":"Dog","groupNameUpper":"NEWJEANS","positions":"(none)","counter":3,"nameUpper":"HAERIN","zodiacId":2,"birthDate":20060515,"realName":"Kang Haerin","idolId":193,"groupName":"NewJeans","chineseZodiacId":11,"fandom":"(none)","imageFileName":"HAERIN_NEWJEANS","name":"Haerin","age":16}
	,{"country":"South Korea","agency":"ADOR","counter2":1,"city":"Yeongwol-gun/Gangwondo","counter1":2,"zodiac":"Taurus","chineseZodiac":"Monkey","groupNameUpper":"NEWJEANS","positions":"(none)","counter":3,"nameUpper":"MINJI","zodiacId":2,"birthDate":20040507,"realName":"Kim Minji","idolId":194,"groupName":"NewJeans","chineseZodiacId":9,"fandom":"(none)","imageFileName":"MINJI_NEWJEANS","name":"Minji","age":18}
	,{"country":"South Korea","agency":"FC ENM","counter2":0,"city":"(none)","counter1":1,"zodiac":"Aquarius","chineseZodiac":"Horse","groupNameUpper":"ILY:1","positions":"Vocalist","counter":1,"nameUpper":"ARA","zodiacId":11,"birthDate":20020123,"realName":"Lee Yunji","idolId":195,"groupName":"ily:1","chineseZodiacId":7,"fandom":"Only:1","imageFileName":"ARA_ILY1","name":"Ara","age":20}
	,{"country":"South Korea","agency":"JYP Entertainment","counter2":1,"city":"Seoul","counter1":0,"zodiac":"Aries","chineseZodiac":"Snake","groupNameUpper":"ITZY","positions":"Main Rapper, Lead Dancer, Sub Vocalist, Center","counter":1,"nameUpper":"RYUJIN","zodiacId":1,"birthDate":20010417,"realName":"Shin Ryujin","idolId":196,"groupName":"ITZY","chineseZodiacId":6,"fandom":"MIDZY","imageFileName":"RYUJIN_ITZY","name":"Ryujin","age":21}
	,{"country":"Canada","agency":"The Black Label","counter2":0,"city":"Ontario","counter1":1,"zodiac":"Pisces","chineseZodiac":"Snake","groupNameUpper":"SOLOIST","positions":"(none)","counter":1,"nameUpper":"SOMI","zodiacId":12,"birthDate":20010309,"realName":"Ennik Somi Douma","idolId":197,"groupName":"soloist","chineseZodiacId":6,"fandom":"(none)","imageFileName":"SOMI_SOLOIST","name":"Somi","age":21}
	,{"country":"Thailand","agency":"YG Entertainment","counter2":0,"city":"Buriram","counter1":1,"zodiac":"Aries","chineseZodiac":"Ox","groupNameUpper":"BLACKPINK","positions":"Main Dancer, Lead Rapper, Sub Vocalist, Maknae","counter":1,"nameUpper":"LISA","zodiacId":1,"birthDate":19970327,"realName":"Pranpriya Manoban","idolId":198,"groupName":"Blackpink","chineseZodiacId":2,"fandom":"BLINK","imageFileName":"LISA_BLACKPINK","name":"Lisa","age":25}
	,{"country":"Philippines","agency":"MLD Entertainment","counter2":0,"city":"Manila","counter1":1,"zodiac":"Sagittarius","chineseZodiac":"Horse","groupNameUpper":"LAPILLUS","positions":"Vocalist, Face of the Group","counter":1,"nameUpper":"CHANTY","zodiacId":9,"birthDate":20021215,"realName":"Maria Chantal Videla","idolId":199,"groupName":"Lapillus","chineseZodiacId":7,"fandom":"(none)","imageFileName":"CHANTY_LAPILLUS","name":"Chanty","age":19}
	,{"country":"South Korea","agency":"Grandline Group (GLG)","counter2":0,"city":"(none)","counter1":1,"zodiac":"Aquarius","chineseZodiac":"Dragon","groupNameUpper":"H1-KEY","positions":"Leader, Vocalist","counter":1,"nameUpper":"SEOI","zodiacId":11,"birthDate":20000212,"realName":"Lee Yejin","idolId":200,"groupName":"H1-KEY","chineseZodiacId":5,"fandom":"M1-KEY","imageFileName":"SEOI_H1KEY","name":"Seoi","age":22}
	,{"country":"South Korea","agency":"Grandline Group (GLG)","counter2":0,"city":"(none)","counter1":1,"zodiac":"Leo","chineseZodiac":"Horse","groupNameUpper":"H1-KEY","positions":"Vocalist","counter":1,"nameUpper":"HWISEO","zodiacId":5,"birthDate":20020731,"realName":"Jo Hwihyeon","idolId":201,"groupName":"H1-KEY","chineseZodiacId":7,"fandom":"M1-KEY","imageFileName":"HWISEO_H1KEY","name":"Hwiseo","age":20}
	]);
	