var artists = TAFFY([
	{"country":"South Korea","agency":"BPM Entertainment","counter2":8,"city":"Cheongju","zodiac":"Gemini","counter1":22,"chineseZodiac":"Tiger","groupNameUpper":"VIVIZ","positions":"Main Dancer,Vocalist","nameUpper":"SINB","zodiacId":3,"counter":30,"birthDate":19980603,"realName":"Hwang Eunbi","idolId":1,"chineseZodiacId":3,"groupName":"VIVIZ","imageFileName":"SINB_VIVIZ","fandom":"Na.V","name":"SinB","age":24}
	,{"country":"South Korea","agency":"Source Music","counter2":4,"city":"Seoul","zodiac":"Sagittarius","counter1":1,"chineseZodiac":"Pig","groupNameUpper":"GFRIEND","positions":"Leader,Vocalist,Visual","nameUpper":"SOWON","zodiacId":9,"counter":5,"birthDate":19951207,"realName":"Kim Sojung","idolId":2,"chineseZodiacId":12,"groupName":"Gfriend","imageFileName":"SOWON_GFRIEND","fandom":"BUDDY","name":"Sowon","age":26}
	,{"country":"South Korea","agency":"Dreamcatcher Company","counter2":3,"city":"Daejeon","zodiac":"Taurus","counter1":6,"chineseZodiac":"Dog","groupNameUpper":"DREAMCATCHER","positions":"Leader,Lead Vocalist,Lead Dancer,Visual","nameUpper":"JIU","zodiacId":2,"counter":9,"birthDate":19940517,"realName":"Kim Minji","idolId":3,"chineseZodiacId":11,"groupName":"Dreamcatcher","imageFileName":"JIU_DREAMCATCHER","fandom":"InSomnia","name":"Jiu","age":28}
	,{"country":"South Korea","agency":"WAKEONE and Swing Entertainment","counter2":14,"city":"Seoul","zodiac":"Pisces","counter1":10,"chineseZodiac":"Goat","groupNameUpper":"KEP1ER","positions":"---","nameUpper":"DAYEON","zodiacId":12,"counter":24,"birthDate":20030302,"realName":"Kim Dayeon","idolId":4,"chineseZodiacId":8,"groupName":"Kep1er","imageFileName":"DAYEON_KEP1ER","fandom":"Kep1ian","name":"Dayeon","age":19}
	,{"country":"South Korea","agency":"BlockBerryCreative","counter2":6,"city":"Bundang-gu","zodiac":"Libra","counter1":13,"chineseZodiac":"Dragon","groupNameUpper":"LOONA","positions":"Dancer,Vocalist,Rapper,Visual,Center","nameUpper":"HEEJIN","zodiacId":7,"counter":19,"birthDate":20001019,"realName":"Jeon Heejin","idolId":5,"chineseZodiacId":5,"groupName":"LOONA","imageFileName":"HEEJIN_LOONA","fandom":"Orbit","name":"Heejin","age":21}
	,{"country":"South Korea","agency":"RBW","counter2":2,"city":"Busan","zodiac":"Sagittarius","counter1":18,"chineseZodiac":"Horse","groupNameUpper":"PURPLE KISS","positions":"Main Vocalist,Lead Dancer,Rapper","nameUpper":"CHAEIN","zodiacId":9,"counter":20,"birthDate":20021205,"realName":"Lee Chaeyoung","idolId":6,"chineseZodiacId":7,"groupName":"Purple Kiss","imageFileName":"CHAEIN_PURPLEKISS","fandom":"PLORY","name":"Chaein","age":19}
	,{"country":"South Korea","agency":"iMe Entertainment","counter2":3,"city":"Seoul","zodiac":"Virgo","counter1":5,"chineseZodiac":"Snake","groupNameUpper":"DREAM NOTE","positions":"Main Rapper,Main Dancer,Vocalist,Center,Face of the Group","nameUpper":"SUMIN","zodiacId":6,"counter":8,"birthDate":20010907,"realName":"Park Sumin","idolId":7,"chineseZodiacId":6,"groupName":"Dream Note","imageFileName":"SUMIN_DREAMNOTE","fandom":"Page","name":"Sumin","age":21}
	,{"country":"South Korea","agency":"High Up Entertainment","counter2":2,"city":"Daejeon/Chungcheong","zodiac":"Sagittarius","counter1":9,"chineseZodiac":"Monkey","groupNameUpper":"STAYC","positions":"Vocalist,Rapper,Maknae","nameUpper":"J","zodiacId":9,"counter":11,"birthDate":20041209,"realName":"Jang Yeeun","idolId":8,"chineseZodiacId":9,"groupName":"Stayc","imageFileName":"J_STAYC","fandom":"SWITH","name":"J","age":17}
	,{"country":"South Korea","agency":"WAKEONE and Swing Entertainment","counter2":0,"city":"Uijeongbu/Gyeonggi-do","zodiac":"Capricorn","counter1":5,"chineseZodiac":"Monkey","groupNameUpper":"KEP1ER","positions":"---","nameUpper":"YOUNGEUN","zodiacId":10,"counter":5,"birthDate":20041227,"realName":"Seo Youngeun","idolId":9,"chineseZodiacId":9,"groupName":"Kep1er","imageFileName":"YOUNGEUN_KEP1ER","fandom":"Kep1ian","name":"Youngeun","age":17}
	,{"country":"South Korea","agency":"JYP Entertainment","counter2":1,"city":"Guti/Gyeonggi-do","zodiac":"Aquarius","counter1":0,"chineseZodiac":"Ox","groupNameUpper":"TWICE","positions":"Leader,Main Vocalist","nameUpper":"JIHYO","zodiacId":11,"counter":1,"birthDate":19970201,"realName":"Park Jihyo","idolId":10,"chineseZodiacId":2,"groupName":"Twice","imageFileName":"JIHYO_TWICE","fandom":"ONCE","name":"Jihyo","age":25}
	,{"country":"South Korea","agency":"Yuehua Entertainment","counter2":0,"city":"Gwonseon-gu/Suwon/Gyeonggi-do","zodiac":"Cancer","counter1":3,"chineseZodiac":"Dragon","groupNameUpper":"EVERGLOW","positions":"Lead Rapper,Sub Vocalist","nameUpper":"AISHA","zodiacId":4,"counter":3,"birthDate":20000721,"realName":"Heo Yoorim","idolId":11,"chineseZodiacId":5,"groupName":"Everglow","imageFileName":"AISHA_EVERGLOW","fandom":"For Ever","name":"Aisha","age":22}
	,{"country":"South Korea","agency":"Pledis Entertainment","counter2":1,"city":"Boseong-gun/South Jeolla","zodiac":"Aries","counter1":3,"chineseZodiac":"Goat","groupNameUpper":"FROMIS_9","positions":"Vocalist,Maknae","nameUpper":"JIHEON","zodiacId":1,"counter":4,"birthDate":20030417,"realName":"Baek Jiheon","idolId":12,"chineseZodiacId":8,"groupName":"fromis_9","imageFileName":"JIHEON_FROMIS9","fandom":"Flover","name":"Jiheon","age":19}
	,{"country":"South Korea","agency":"High Up Entertainment","counter2":3,"city":"Seoul","zodiac":"Leo","counter1":7,"chineseZodiac":"Snake","groupNameUpper":"STAYC","positions":"Main Vocalist","nameUpper":"SIEUN","zodiacId":5,"counter":10,"birthDate":20010801,"realName":"Park Sieun","idolId":13,"chineseZodiacId":6,"groupName":"Stayc","imageFileName":"SIEUN_STAYC","fandom":"SWITH","name":"Sieun","age":21}
	,{"country":"South Korea","agency":"iMe Entertainment","counter2":2,"city":"Incheon","zodiac":"Scorpius","counter1":6,"chineseZodiac":"Dragon","groupNameUpper":"DREAM NOTE","positions":"Main Vocalist,Rapper","nameUpper":"MISO","zodiacId":8,"counter":8,"birthDate":20001025,"realName":"Jeon Jimin","idolId":14,"chineseZodiacId":5,"groupName":"Dream Note","imageFileName":"MISO_DREAMNOTE","fandom":"Page","name":"Miso","age":21}
	,{"country":"South Korea","agency":"WM Entertainment","counter2":9,"city":"Busan/South Gyeongnam","zodiac":"Gemini","counter1":10,"chineseZodiac":"Rabbit","groupNameUpper":"OH MY GIRL","positions":"Lead Dancer,Sub Vocalist,Maknae","nameUpper":"ARIN","zodiacId":3,"counter":19,"birthDate":19990618,"realName":"Choi Yewon","idolId":15,"chineseZodiacId":4,"groupName":"Oh My Girl","imageFileName":"ARIN_OHMYGIRL","fandom":"Miracle","name":"Arin","age":23}
	,{"country":"South Korea","agency":"J9 Entertainment","counter2":1,"city":"Busan","zodiac":"Aries","counter1":1,"chineseZodiac":"Rabbit","groupNameUpper":"CIGNATURE","positions":"Vocalist,Center,Face of the Group","nameUpper":"JEEWON","zodiacId":1,"counter":2,"birthDate":19990401,"realName":"Kim jiwon","idolId":16,"chineseZodiacId":4,"groupName":"cignature","imageFileName":"JEEWON_CIGNATURE","fandom":"signfan","name":"Jeewon","age":23}
	,{"country":"South Korea","agency":"TR Entertainment","counter2":13,"city":"North Jeolla","zodiac":"Gemini","counter1":8,"chineseZodiac":"Monkey","groupNameUpper":"TRI.BE","positions":"Main Rapper,Main Dancer,Lead Vocalist","nameUpper":"HYUNBIN","zodiacId":3,"counter":21,"birthDate":20040526,"realName":"Kim Hyunbin","idolId":17,"chineseZodiacId":9,"groupName":"TRI.BE","imageFileName":"HYUNBIN_TRIBE","fandom":"TRUE","name":"Hyunbin","age":18}
	,{"country":"South Korea","agency":"IST Entertainment","counter2":7,"city":"Gwangju/Jeolla-do","zodiac":"Scorpius","counter1":18,"chineseZodiac":"Horse","groupNameUpper":"WEEEKLY","positions":"Main Dancer,Lead Vocalist,Center","nameUpper":"SOEUN","zodiacId":8,"counter":25,"birthDate":20021026,"realName":"Park Soeun","idolId":18,"chineseZodiacId":7,"groupName":"Weeekly","imageFileName":"SOEUN_WEEEKLY","fandom":"Daileee","name":"Soeun","age":19}
	,{"country":"South Korea","agency":"WM Entertainment","counter2":0,"city":"Seoul","zodiac":"Virgo","counter1":5,"chineseZodiac":"Pig","groupNameUpper":"OH MY GIRL","positions":"Main Dancer,Lead Vocalist,Face of the Group","nameUpper":"YOOA","zodiacId":6,"counter":5,"birthDate":19950917,"realName":"Yoo Shiah","idolId":19,"chineseZodiacId":12,"groupName":"Oh My Girl","imageFileName":"YOOA_OHMYGIRL","fandom":"Miracle","name":"Yooa","age":26}
	,{"country":"South Korea","agency":"IST Entertainment","counter2":5,"city":"Anyang/Gyeonggi-do","zodiac":"Cancer","counter1":3,"chineseZodiac":"Monkey","groupNameUpper":"WEEEKLY","positions":"Lead Vocalist,Visual,Center","nameUpper":"JIHAN","zodiacId":4,"counter":8,"birthDate":20040712,"realName":"Han Jihyo","idolId":20,"chineseZodiacId":9,"groupName":"Weeekly","imageFileName":"JIHAN_WEEEKLY","fandom":"Daileee","name":"Jihan","age":18}
	,{"country":"South Korea","agency":"Starship Entertainment","counter2":17,"city":"Seoul","zodiac":"Virgo","counter1":13,"chineseZodiac":"Monkey","groupNameUpper":"IVE","positions":"Vocalist,Visual","nameUpper":"WONYOUNG","zodiacId":6,"counter":30,"birthDate":20040831,"realName":"Jang Wongyoung","idolId":21,"chineseZodiacId":9,"groupName":"IVE","imageFileName":"WONYOUNG_IVE","fandom":"DIVE","name":"Wonyoung","age":18}
	,{"country":"Japan","agency":"TR Entertainment","counter2":1,"city":"Tokyo","zodiac":"Aries","counter1":1,"chineseZodiac":"Dog","groupNameUpper":"TRI.BE","positions":"Main Dancer,Sub Vocalist,Maknae","nameUpper":"MIRE","zodiacId":1,"counter":2,"birthDate":20060326,"realName":"Aoyagi Sumire","idolId":22,"chineseZodiacId":11,"groupName":"TRI.BE","imageFileName":"MIRE_TRIBE","fandom":"TRUE","name":"Mire","age":16}
	,{"country":"China","agency":"SM Entertainment","counter2":1,"city":"Harbin/Heilongjiang","zodiac":"Scorpius","counter1":2,"chineseZodiac":"Horse","groupNameUpper":"AESPA","positions":"Main Vocalist,Maknae","nameUpper":"NING NING","zodiacId":8,"counter":3,"birthDate":20021023,"realName":"Ning Yizhuo","idolId":23,"chineseZodiacId":7,"groupName":"aespa","imageFileName":"NINGNING_AESPA","fandom":"MY","name":"Ning Ning","age":19}
	,{"country":"South Korea","agency":"High Up Entertainment","counter2":13,"city":"Busan","zodiac":"Aquarius","counter1":14,"chineseZodiac":"Horse","groupNameUpper":"STAYC","positions":"Lead Vocalist","nameUpper":"ISA","zodiacId":11,"counter":27,"birthDate":20020123,"realName":"Lee Chaeyoung","idolId":24,"chineseZodiacId":7,"groupName":"Stayc","imageFileName":"ISA_STAYC","fandom":"SWITH","name":"ISA","age":20}
	,{"country":"South Korea","agency":"WM Entertainment","counter2":4,"city":"Anyang/Gyeonggi-do","zodiac":"Leo","counter1":9,"chineseZodiac":"Dog","groupNameUpper":"OH MY GIRL","positions":"Leader,Main Vocalist","nameUpper":"HYOJUNG","zodiacId":5,"counter":13,"birthDate":19940728,"realName":"Choi Hyojung","idolId":25,"chineseZodiacId":11,"groupName":"Oh My Girl","imageFileName":"HYOJUNG_OHMYGIRL","fandom":"Miracle","name":"Hyojung","age":28}
	,{"country":"South Korea","agency":"Starship Entertainment","counter2":3,"city":"Seogwipo/Jeju-do","zodiac":"Scorpius","counter1":2,"chineseZodiac":"Monkey","groupNameUpper":"IVE","positions":"Main Vocalist","nameUpper":"LIZ","zodiacId":8,"counter":5,"birthDate":20041121,"realName":"Kim Jiwon","idolId":26,"chineseZodiacId":9,"groupName":"IVE","imageFileName":"LIZ_IVE","fandom":"DIVE","name":"Liz","age":17}
	,{"country":"South Korea","agency":"NV Entertainment","counter2":0,"city":"Osan/Gyeonggi-do","zodiac":"Leo","counter1":2,"chineseZodiac":"Monkey","groupNameUpper":"WOO!AH!","positions":"Main Vocalist,Lead Dancer,Maknae","nameUpper":"MINSEO","zodiacId":5,"counter":2,"birthDate":20040812,"realName":"Kim Minseo","idolId":27,"chineseZodiacId":9,"groupName":"woo!ah!","imageFileName":"MINSEO_WOOAH","fandom":"wow!","name":"Minseo","age":18}
	,{"country":"South Korea","agency":"BlockBerryCreative","counter2":3,"city":"Jeonju/North Jeolla","zodiac":"Scorpius","counter1":3,"chineseZodiac":"Dragon","groupNameUpper":"LOONA","positions":"Dancer,Vocalist,Rapper,Visual","nameUpper":"HYUNJIN","zodiacId":8,"counter":6,"birthDate":20001115,"realName":"Kim Hyunjin","idolId":28,"chineseZodiacId":5,"groupName":"LOONA","imageFileName":"HYUNJIN_LOONA","fandom":"Orbit","name":"Hyunjin","age":21}
	,{"country":"South Korea","agency":"High Up Entertainment","counter2":1,"city":"Gwanju/Jeolla-do","zodiac":"Aries","counter1":13,"chineseZodiac":"Monkey","groupNameUpper":"STAYC","positions":"Lead Vocalist","nameUpper":"YOON","zodiacId":1,"counter":14,"birthDate":20040414,"realName":"Shim Jayun","idolId":29,"chineseZodiacId":9,"groupName":"Stayc","imageFileName":"YOON_STAYC","fandom":"SWITH","name":"Yoon","age":18}
	,{"country":"China","agency":"Yuehua Entertainment","counter2":3,"city":"Hangzhou/Zhejiang","zodiac":"Capricorn","counter1":4,"chineseZodiac":"Dragon","groupNameUpper":"EVERGLOW","positions":"Lead Dancer,Sub Vocalist,Sub Rapper,Visual,Center,Face of the Group,Maknae","nameUpper":"YIREN","zodiacId":10,"counter":7,"birthDate":20001229,"realName":"Wang Yiren","idolId":30,"chineseZodiacId":5,"groupName":"Everglow","imageFileName":"YIREN_EVERGLOW","fandom":"For Ever","name":"Yiren","age":21}
	,{"country":"South Korea","agency":"Starship Entertainment","counter2":1,"city":"Gapyeong/Gyeonggi-do","zodiac":"Pisces","counter1":6,"chineseZodiac":"Pig","groupNameUpper":"IVE","positions":"Vocalist,Visual,Maknae","nameUpper":"LEESEO","zodiacId":12,"counter":7,"birthDate":20070221,"realName":"Lee Hyunseo","idolId":31,"chineseZodiacId":12,"groupName":"IVE","imageFileName":"LEESEO_IVE","fandom":"DIVE","name":"Leeseo","age":15}
	,{"country":"South Korea","agency":"BPM Entertainment","counter2":2,"city":"Incheon","zodiac":"Leo","counter1":6,"chineseZodiac":"Tiger","groupNameUpper":"VIVIZ","positions":"Lead Dancer,Vocalist,Maknae","nameUpper":"UMJI","zodiacId":5,"counter":8,"birthDate":19980819,"realName":"Kim Yewon","idolId":32,"chineseZodiacId":3,"groupName":"VIVIZ","imageFileName":"UMJI_VIVIZ","fandom":"Na.V","name":"Umji","age":24}
	,{"country":"South Korea","agency":"Yuehua Entertainment","counter2":0,"city":"Bundang-gu/Seongnam/Gyeonggi-do","zodiac":"Leo","counter1":3,"chineseZodiac":"Rabbit","groupNameUpper":"EVERGLOW","positions":"Leader,Lead Vocalist,Visual,Face of the Group","nameUpper":"SIHYEON","zodiacId":5,"counter":3,"birthDate":19990805,"realName":"Kim Sihyeon","idolId":33,"chineseZodiacId":4,"groupName":"Everglow","imageFileName":"SIHYEON_EVERGLOW","fandom":"For Ever","name":"Sihyeon","age":23}
	,{"country":"South Korea","agency":"BlockBerryCreative","counter2":0,"city":"Bucheon","zodiac":"Gemini","counter1":5,"chineseZodiac":"Snake","groupNameUpper":"LOONA","positions":"Rapper,Dancer,Vocalist","nameUpper":"CHOERRY","zodiacId":3,"counter":5,"birthDate":20010604,"realName":"Choi Yerin","idolId":34,"chineseZodiacId":6,"groupName":"LOONA","imageFileName":"CHOERRY_LOONA","fandom":"Orbit","name":"Choerry","age":21}
	,{"country":"South Korea","agency":"JYP Entertainment","counter2":2,"city":"Incheon","zodiac":"Cancer","counter1":1,"chineseZodiac":"Dragon","groupNameUpper":"ITZY","positions":"Main Vocalist,Sub Rapper","nameUpper":"LIA","zodiacId":4,"counter":3,"birthDate":20000721,"realName":"Choi Jisoo","idolId":35,"chineseZodiacId":5,"groupName":"ITZY","imageFileName":"LIA_ITZY","fandom":"MIDZY","name":"Lia","age":22}
	,{"country":"South Korea","agency":"MYSTIC Story","counter2":7,"city":"Yeonsu-gu/Incheon","zodiac":"Aquarius","counter1":12,"chineseZodiac":"Goat","groupNameUpper":"BILLLIE","positions":"Main Dancer,Lead Rapper","nameUpper":"SHEON","zodiacId":11,"counter":19,"birthDate":20030128,"realName":"Kim Suyeon","idolId":36,"chineseZodiacId":8,"groupName":"Billlie","imageFileName":"SHEON_BILLLIE","fandom":"Belllie've","name":"Sheon","age":19}
	,{"country":"South Korea","agency":"BlockBerryCreative","counter2":6,"city":"Seoul","zodiac":"Scorpius","counter1":29,"chineseZodiac":"Horse","groupNameUpper":"LOONA","positions":"Vocalist,Rapper,Maknae","nameUpper":"YEOJIN","zodiacId":8,"counter":35,"birthDate":20021111,"realName":"Im Yeojin","idolId":37,"chineseZodiacId":7,"groupName":"LOONA","imageFileName":"YEOJIN_LOONA","fandom":"Orbit","name":"Yeojin","age":19}
	,{"country":"Japan","agency":"MYSTIC Story","counter2":1,"city":"Hyoge","zodiac":"Virgo","counter1":5,"chineseZodiac":"Horse","groupNameUpper":"BILLLIE","positions":"Main Dancer,Sub Vocalist","nameUpper":"TSUKI","zodiacId":6,"counter":6,"birthDate":20020921,"realName":"Fukutomi Tsuki","idolId":38,"chineseZodiacId":7,"groupName":"Billlie","imageFileName":"TSUKI_BILLLIE","fandom":"Belllie've","name":"Tsuki","age":19}
	,{"country":"South Korea","agency":"BlockBerryCreative","counter2":5,"city":"Chuncheon","zodiac":"Gemini","counter1":5,"chineseZodiac":"Ox","groupNameUpper":"LOONA","positions":"Rapper,Vocalist,Visual","nameUpper":"JINSOUL","zodiacId":3,"counter":10,"birthDate":19970613,"realName":"Jeong Jinsol","idolId":39,"chineseZodiacId":2,"groupName":"LOONA","imageFileName":"JINSOUL_LOONA","fandom":"Orbit","name":"Jinsoul","age":25}
	,{"country":"South Korea","agency":"Pledis Entertainment","counter2":0,"city":"Pohang","zodiac":"Taurus","counter1":5,"chineseZodiac":"Dragon","groupNameUpper":"FROMIS_9","positions":"Main Dancer,Lead Rapper,Vocalist","nameUpper":"CHAEYOUNG","zodiacId":2,"counter":5,"birthDate":20000514,"realName":"Lee Chaeyoung","idolId":40,"chineseZodiacId":5,"groupName":"fromis_9","imageFileName":"CHAEYOUNG_FROMIS9","fandom":"Flover","name":"Chaeyoung","age":22}
	,{"country":"South Korea","agency":"NV Entertainment","counter2":2,"city":"Nowon-gu/Seoul","zodiac":"Pisces","counter1":2,"chineseZodiac":"Snake","groupNameUpper":"WOO!AH!","positions":"Leader,Lead Vocalist,Lead Rapper,Main Dancer,Visual","nameUpper":"NANA","zodiacId":12,"counter":4,"birthDate":20010309,"realName":"Kwon Nayeon","idolId":41,"chineseZodiacId":6,"groupName":"woo!ah!","imageFileName":"NANA_WOOAH","fandom":"wow!","name":"Nana","age":21}
	,{"country":"South Korea","agency":"IST Entertainment","counter2":5,"city":"Bundang-gu/Seongnam/Gyeonggi-do","zodiac":"Taurus","counter1":5,"chineseZodiac":"Horse","groupNameUpper":"WEEEKLY","positions":"Main Vocalist,Main Dancer,Sub Rapper","nameUpper":"MONDAY","zodiacId":2,"counter":10,"birthDate":20020510,"realName":"Kim Jimin","idolId":42,"chineseZodiacId":7,"groupName":"Weeekly","imageFileName":"MONDAY_WEEEKLY","fandom":"Daileee","name":"Monday","age":20}
	,{"country":"South Korea","agency":"IST Entertainment","counter2":0,"city":"Songpa-gu/Seoul","zodiac":"Sagittarius","counter1":3,"chineseZodiac":"Snake","groupNameUpper":"WEEEKLY","positions":"Leader,Main Dancer,Sub Vocalist,Sub Rapper,Visual,Center","nameUpper":"SOOJIN","zodiacId":9,"counter":3,"birthDate":20011212,"realName":"Lee Soojin","idolId":43,"chineseZodiacId":6,"groupName":"Weeekly","imageFileName":"SOOJIN_WEEEKLY","fandom":"Daileee","name":"Soojin","age":20}
	,{"country":"South Korea","agency":"IST Entertainment","counter2":0,"city":"Ilsanseo-gu/Goyang/Gyeonggi-do","zodiac":"Pisces","counter1":3,"chineseZodiac":"Monkey","groupNameUpper":"WEEEKLY","positions":"Sub Vocalist,Sub Rapper","nameUpper":"JAEHEE","zodiacId":12,"counter":3,"birthDate":20040318,"realName":"Lee Jaehee","idolId":44,"chineseZodiacId":9,"groupName":"Weeekly","imageFileName":"JAEHEE_WEEEKLY","fandom":"Daileee","name":"Jaehee","age":18}
	,{"country":"South Korea","agency":"MYSTIC Story","counter2":4,"city":"Jeonju/Jeollabuk-do","zodiac":"Capricorn","counter1":18,"chineseZodiac":"Snake","groupNameUpper":"BILLLIE","positions":"Main Vocalist","nameUpper":"HARAM","zodiacId":10,"counter":22,"birthDate":20010113,"realName":"Kim Haram","idolId":45,"chineseZodiacId":6,"groupName":"Billlie","imageFileName":"HARAM_BILLLIE","fandom":"Belllie've","name":"Haram","age":21}
	,{"country":"South Korea","agency":"iMe Entertainment","counter2":0,"city":"Incheon","zodiac":"Scorpius","counter1":3,"chineseZodiac":"Rabbit","groupNameUpper":"DREAM NOTE","positions":"Lead Vocalist,Lead Dancer,Rapper","nameUpper":"BONI","zodiacId":8,"counter":3,"birthDate":19991030,"realName":"Choi Euijeong","idolId":46,"chineseZodiacId":4,"groupName":"Dream Note","imageFileName":"BONI_DREAMNOTE","fandom":"Page","name":"Boni","age":22}
	,{"country":"South Korea","agency":"SM Entertainment","counter2":3,"city":"Paldal-gu/Gyeonggi-do","zodiac":"Aries","counter1":1,"chineseZodiac":"Dragon","groupNameUpper":"AESPA","positions":"Leader,Main Dancer,Lead Rapper,Sub Vocalist,Visual,Face of the Group,Center","nameUpper":"KARINA","zodiacId":1,"counter":4,"birthDate":20000411,"realName":"Yoo Jimin","idolId":47,"chineseZodiacId":5,"groupName":"aespa","imageFileName":"KARINA_AESPA","fandom":"MY","name":"Karina","age":22}
	,{"country":"South Korea","agency":"FNC Entertainment","counter2":3,"city":"Gwangju","zodiac":"Pisces","counter1":6,"chineseZodiac":"Rabbit","groupNameUpper":"CHERRY BULLET","positions":"Main Vocalist","nameUpper":"BORA","zodiacId":12,"counter":9,"birthDate":19990303,"realName":"Kim Bora","idolId":48,"chineseZodiacId":4,"groupName":"Cherry Bullet","imageFileName":"BORA_CHERRYBULLET","fandom":"Lullet","name":"Bora","age":23}
	,{"country":"South Korea","agency":"Cube Entertainment","counter2":7,"city":"Incheon","zodiac":"Aquarius","counter1":12,"chineseZodiac":"Ox","groupNameUpper":"(G)I-DLE","positions":"Main Vocalist,Visual","nameUpper":"MIYEON","zodiacId":11,"counter":19,"birthDate":19970131,"realName":"Jo Miyeon","idolId":49,"chineseZodiacId":2,"groupName":"(g)i-dle","imageFileName":"MIYEON_GIDLE","fandom":"Neverland","name":"Miyeon","age":25}
	,{"country":"South Korea","agency":"ALLART Entertainment","counter2":1,"city":"---","zodiac":"Leo","counter1":4,"chineseZodiac":"Goat","groupNameUpper":"PIXY","positions":"Sub Vocalist,Maknae","nameUpper":"DAJEONG","zodiacId":5,"counter":5,"birthDate":20030731,"realName":"Jung Dajeong","idolId":50,"chineseZodiacId":8,"groupName":"Pixy","imageFileName":"DAJEONG_PIXY","fandom":"Winxy","name":"Dajeong","age":19}
	,{"country":"South Korea","agency":"Cube Entertainment","counter2":2,"city":"Incheon","zodiac":"Virgo","counter1":9,"chineseZodiac":"Horse","groupNameUpper":"LIGHTSUM","positions":"Lead Dancer,Rapper","nameUpper":"SANGAH","zodiacId":6,"counter":11,"birthDate":20020904,"realName":"Yoon Sangah","idolId":51,"chineseZodiacId":7,"groupName":"Lightsum","imageFileName":"SANGAH_LIGHTSUM","fandom":"SUMIT","name":"Sangah","age":20}
	,{"country":"South Korea","agency":"YG Entertainment","counter2":0,"city":"Gunpo/Gyeonggi-do","zodiac":"Capricorn","counter1":2,"chineseZodiac":"Pig","groupNameUpper":"BLACKPINK","positions":"Lead Vocalist,Visual","nameUpper":"JISOO","zodiacId":10,"counter":2,"birthDate":19950103,"realName":"Kim Jisoo","idolId":52,"chineseZodiacId":12,"groupName":"Blackpink","imageFileName":"JISOO_BLACKPINK","fandom":"BLINK","name":"Jisoo","age":27}
	,{"country":"South Korea","agency":"Cube Entertainment","counter2":0,"city":"Seoul","zodiac":"Virgo","counter1":1,"chineseZodiac":"Tiger","groupNameUpper":"(G)I-DLE","positions":"Leader,Main Rapper,Sub Vocalist,Center","nameUpper":"SOYEON","zodiacId":6,"counter":1,"birthDate":19980826,"realName":"Jeon Soyeon","idolId":53,"chineseZodiacId":3,"groupName":"(g)i-dle","imageFileName":"SOYEON_GIDLE","fandom":"Neverland","name":"Soyeon","age":24}
	,{"country":"USA","agency":"Vine Entertainment","counter2":2,"city":"Los Angeles/California","zodiac":"Aquarius","counter1":8,"chineseZodiac":"Tiger","groupNameUpper":"SECRET NUMBER","positions":"Main Rapper,Sub Vocalist","nameUpper":"JINNY","zodiacId":11,"counter":10,"birthDate":19980120,"realName":"Jinny Park","idolId":54,"chineseZodiacId":3,"groupName":"Secret Number","imageFileName":"JINNY_SECRETNUMBER","fandom":"LOCKEY","name":"Jinny","age":24}
	,{"country":"South Korea","agency":"IST Entertainment","counter2":3,"city":"Seoul","zodiac":"Gemini","counter1":4,"chineseZodiac":"Rooster","groupNameUpper":"WEEEKLY","positions":"Sub Vocalist,Sub Rapper,Visual,Maknae","nameUpper":"ZOA","zodiacId":3,"counter":7,"birthDate":20050531,"realName":"Cho Hyewon","idolId":55,"chineseZodiacId":10,"groupName":"Weeekly","imageFileName":"ZOA_WEEEKLY","fandom":"Daileee","name":"Zoa","age":17}
	,{"country":"South Korea","agency":"Source Music","counter2":0,"city":"Ilsan","zodiac":"Libra","counter1":1,"chineseZodiac":"Ox","groupNameUpper":"GFRIEND","positions":"Main Vocalist","nameUpper":"YUJU","zodiacId":7,"counter":1,"birthDate":19971004,"realName":"Choi Yuna","idolId":56,"chineseZodiacId":2,"groupName":"Gfriend","imageFileName":"YUJU_GFRIEND","fandom":"BUDDY","name":"Yuju","age":24}
	,{"country":"Japan","agency":"JYP Entertainment","counter2":4,"city":"Osaka","zodiac":"Capricorn","counter1":3,"chineseZodiac":"Rat","groupNameUpper":"TWICE","positions":"Sub Vocalist","nameUpper":"SANA","zodiacId":10,"counter":7,"birthDate":19961229,"realName":"Minatozaki Sana","idolId":57,"chineseZodiacId":1,"groupName":"Twice","imageFileName":"SANA_TWICE","fandom":"ONCE","name":"Sana","age":25}
	,{"country":"South Korea","agency":"J9 Entertainment","counter2":1,"city":"Yeosu","zodiac":"Cancer","counter1":6,"chineseZodiac":"Tiger","groupNameUpper":"CIGNATURE","positions":"Vocalist,Visual","nameUpper":"CHAESOL","zodiacId":4,"counter":7,"birthDate":19980714,"realName":"Moon Chaesol","idolId":58,"chineseZodiacId":3,"groupName":"cignature","imageFileName":"CHAESOL_CIGNATURE","fandom":"signfan","name":"Chaesol","age":24}
	,{"country":"South Korea","agency":"TR Entertainment","counter2":1,"city":"Siheung/Gyeonggi-do","zodiac":"Scorpius","counter1":1,"chineseZodiac":"Goat","groupNameUpper":"TRI.BE","positions":"Lead Vocalist,Lead Dancer","nameUpper":"JINHA","zodiacId":8,"counter":2,"birthDate":20031121,"realName":"Kim Jinha","idolId":59,"chineseZodiacId":8,"groupName":"TRI.BE","imageFileName":"JINHA_TRIBE","fandom":"TRUE","name":"Jinha","age":18}
	,{"country":"South Korea","agency":"JYP Entertainment","counter2":2,"city":"Jeonju","zodiac":"Gemini","counter1":4,"chineseZodiac":"Dragon","groupNameUpper":"ITZY","positions":"Leader,Main Dancer,Lead Vocalist,Sub Rapper","nameUpper":"YEJI","zodiacId":3,"counter":6,"birthDate":20000526,"realName":"Hwang Yeji","idolId":60,"chineseZodiacId":5,"groupName":"ITZY","imageFileName":"YEJI_ITZY","fandom":"MIDZY","name":"Yeji","age":22}
	,{"country":"South Korea","agency":"High Up Entertainment","counter2":9,"city":"Pohang/North Gyeongsang","zodiac":"Pisces","counter1":11,"chineseZodiac":"Snake","groupNameUpper":"STAYC","positions":"Leader,Vocalist,Rapper","nameUpper":"SUMIN","zodiacId":12,"counter":20,"birthDate":20010313,"realName":"Bae Sumin","idolId":61,"chineseZodiacId":6,"groupName":"Stayc","imageFileName":"SUMIN_STAYC","fandom":"SWITH","name":"Sumin","age":21}
	,{"country":"South Korea","agency":"MYSTIC Story","counter2":2,"city":"Daegu","zodiac":"Capricorn","counter1":1,"chineseZodiac":"Dragon","groupNameUpper":"BILLLIE","positions":"Main Vocalist,Lead Dancer","nameUpper":"SUHYEON","zodiacId":10,"counter":3,"birthDate":20000115,"realName":"Kim Suhyeon","idolId":62,"chineseZodiacId":5,"groupName":"Billlie","imageFileName":"SUHYEON_BILLLIE","fandom":"Belllie've","name":"Suhyeon","age":22}
	,{"country":"South Korea","agency":"MNH Entertainment","counter2":0,"city":"Ulsan","zodiac":"Aquarius","counter1":2,"chineseZodiac":"Rat","groupNameUpper":"SOLOIST","positions":"---","nameUpper":"CHUNGHA","zodiacId":11,"counter":2,"birthDate":19960209,"realName":"Kim Chanmi","idolId":63,"chineseZodiacId":1,"groupName":"soloist","imageFileName":"CHUNGHA_SOLOIST","fandom":"BYULHARANG","name":"Chungha","age":26}
	,{"country":"China","agency":"Dreamcatcher Company","counter2":3,"city":"Wuhan","zodiac":"Aries","counter1":7,"chineseZodiac":"Rat","groupNameUpper":"DREAMCATCHER","positions":"Sub Vocalist","nameUpper":"HANDONG","zodiacId":1,"counter":10,"birthDate":19960326,"realName":"Han Dong","idolId":64,"chineseZodiacId":1,"groupName":"Dreamcatcher","imageFileName":"HANDONG_DREAMCATCHER","fandom":"InSomnia","name":"Handong","age":26}
	,{"country":"South Korea","agency":"High Up Entertainment","counter2":0,"city":"Pyeongtaek","zodiac":"Gemini","counter1":2,"chineseZodiac":"Goat","groupNameUpper":"STAYC","positions":"Vocalist","nameUpper":"SEEUN","zodiacId":3,"counter":2,"birthDate":20030614,"realName":"Yoon Seeun","idolId":65,"chineseZodiacId":8,"groupName":"Stayc","imageFileName":"SEEUN_STAYC","fandom":"SWITH","name":"Seeun","age":19}
	,{"country":"Taiwan","agency":"Cube Entertainment","counter2":1,"city":"Taoyuan","zodiac":"Capricorn","counter1":4,"chineseZodiac":"Dragon","groupNameUpper":"(G)I-DLE","positions":"Sub Vocalist,Visual,Maknae","nameUpper":"SHUHUA","zodiacId":10,"counter":5,"birthDate":20000106,"realName":"Yeh Shuhua","idolId":66,"chineseZodiacId":5,"groupName":"(g)i-dle","imageFileName":"SHUHUA_GIDLE","fandom":"Neverland","name":"Shuhua","age":22}
	,{"country":"Japan","agency":"Starship Entertainment","counter2":2,"city":"Nagoya/Aichi","zodiac":"Aquarius","counter1":6,"chineseZodiac":"Monkey","groupNameUpper":"IVE","positions":"Rapper,Vocalist","nameUpper":"REI","zodiacId":11,"counter":8,"birthDate":20040203,"realName":"Naoi Rei","idolId":67,"chineseZodiacId":9,"groupName":"IVE","imageFileName":"REI_IVE","fandom":"DIVE","name":"Rei","age":18}
	,{"country":"South Korea","agency":"WM Entertainment","counter2":1,"city":"Yongin","zodiac":"Capricorn","counter1":3,"chineseZodiac":"Dragon","groupNameUpper":"SOLOIST","positions":"---","nameUpper":"CHAEYEON","zodiacId":10,"counter":4,"birthDate":20000111,"realName":"Lee Chaeyeon","idolId":68,"chineseZodiacId":5,"groupName":"soloist","imageFileName":"CHAEYEON_SOLOIST","fandom":"WIZ*ONE","name":"Chaeyeon","age":22}
	,{"country":"South Korea","agency":"Vine Entertainment","counter2":0,"city":"Seoul","zodiac":"Scorpius","counter1":2,"chineseZodiac":"Rabbit","groupNameUpper":"SECRET NUMBER","positions":"Lead Dancer,Sub Vocalist,Visual,Center","nameUpper":"SOODAM","zodiacId":8,"counter":2,"birthDate":19991109,"realName":"Lee Soodam","idolId":69,"chineseZodiacId":4,"groupName":"Secret Number","imageFileName":"SOODAM_SECRETNUMBER","fandom":"LOCKEY","name":"Soodam","age":22}
	,{"country":"South Korea","agency":"Woollim Entertainment","counter2":0,"city":"Gwangju","zodiac":"Scorpius","counter1":5,"chineseZodiac":"Snake","groupNameUpper":"ROCKET PUNCH","positions":"Vocalist,Rapper,Dancer","nameUpper":"YUNKYOUNG","zodiacId":8,"counter":5,"birthDate":20011101,"realName":"Seo Yunkyoung","idolId":70,"chineseZodiacId":6,"groupName":"Rocket Punch","imageFileName":"YUNKYOUNG_ROCKETPUNCH","fandom":"KETCHY","name":"Yunkyoung","age":20}
	,{"country":"South Korea","agency":"Brave Entertainment","counter2":1,"city":"Suwon","zodiac":"Taurus","counter1":0,"chineseZodiac":"Goat","groupNameUpper":"BRAVE GIRLS","positions":"Vocalist,Visual","nameUpper":"YUJEONG","zodiacId":2,"counter":1,"birthDate":19910502,"realName":"Nam Yujeong","idolId":71,"chineseZodiacId":8,"groupName":"Brave Girls","imageFileName":"YUJEONG_BRAVEGIRLS","fandom":"FEARLESS","name":"Yujeong","age":31}
	,{"country":"South Korea","agency":"JYP Entertainment","counter2":0,"city":"Daejeon","zodiac":"Aquarius","counter1":4,"chineseZodiac":"Monkey","groupNameUpper":"NMIXX","positions":"Vocalist,Dancer","nameUpper":"SULLYOON","zodiacId":11,"counter":4,"birthDate":20040126,"realName":"Seol Yoona","idolId":72,"chineseZodiacId":9,"groupName":"NMIXX","imageFileName":"SULLYOON_NMIXX","fandom":"NSWER","name":"Sullyoon","age":18}
	,{"country":"South Korea","agency":"Woollim Entertainment","counter2":0,"city":"Goyang","zodiac":"Pisces","counter1":2,"chineseZodiac":"Snake","groupNameUpper":"ROCKET PUNCH","positions":"Vocalist,Dancer","nameUpper":"SUYUN","zodiacId":12,"counter":2,"birthDate":20010317,"realName":"Kim Suyun","idolId":73,"chineseZodiacId":6,"groupName":"Rocket Punch","imageFileName":"SUYUN_ROCKETPUNCH","fandom":"KETCHY","name":"Suyun","age":21}
	,{"country":"South Korea","agency":"MYSTIC Story","counter2":0,"city":"Cheongju/Chungcheongbuk-do","zodiac":"Virgo","counter1":2,"chineseZodiac":"Rabbit","groupNameUpper":"BILLLIE","positions":"Main Rapper,Lead Vocalist","nameUpper":"MOON SUA","zodiacId":6,"counter":2,"birthDate":19990909,"realName":"Moon Sua","idolId":74,"chineseZodiacId":4,"groupName":"Billlie","imageFileName":"MOONSUA_BILLLIE","fandom":"Belllie've","name":"Moon Sua","age":22}
	,{"country":"South Korea","agency":"Woollim Entertainment","counter2":0,"city":"Buk-gu/Gwangju","zodiac":"Sagittarius","counter1":5,"chineseZodiac":"Dragon","groupNameUpper":"ROCKET PUNCH","positions":"Leader,Vocalist,Dancer,Rapper","nameUpper":"YEONHEE","zodiacId":9,"counter":5,"birthDate":20001206,"realName":"Kim Yeonhee","idolId":75,"chineseZodiacId":5,"groupName":"Rocket Punch","imageFileName":"YEONHEE_ROCKETPUNCH","fandom":"KETCHY","name":"Yeonhee","age":21}
	,{"country":"South Korea","agency":"Dreamcatcher Company","counter2":3,"city":"Incheon","zodiac":"Capricorn","counter1":2,"chineseZodiac":"Ox","groupNameUpper":"DREAMCATCHER","positions":"Lead Vocalist","nameUpper":"YOOHYEON","zodiacId":10,"counter":5,"birthDate":19970107,"realName":"Kim Yoohyeon","idolId":76,"chineseZodiacId":2,"groupName":"Dreamcatcher","imageFileName":"YOOHYEON_DREAMCATCHER","fandom":"InSomnia","name":"Yoohyeon","age":25}
	,{"country":"South Korea","agency":"BPM Entertainment","counter2":3,"city":"Seoul","zodiac":"Gemini","counter1":7,"chineseZodiac":"Ox","groupNameUpper":"VIVIZ","positions":"Main Vocalist","nameUpper":"EUNHA","zodiacId":3,"counter":10,"birthDate":19970530,"realName":"Jung Eunbi","idolId":77,"chineseZodiacId":2,"groupName":"VIVIZ","imageFileName":"EUNHA_VIVIZ","fandom":"Na.V","name":"Eunha","age":25}
	,{"country":"South Korea","agency":"Urban Works Entertainment","counter2":0,"city":"Seoul","zodiac":"Aquarius","counter1":2,"chineseZodiac":"Snake","groupNameUpper":"SOLOIST","positions":"---","nameUpper":"MINJU","zodiacId":11,"counter":2,"birthDate":20010205,"realName":"Kim Minju","idolId":78,"chineseZodiacId":6,"groupName":"soloist","imageFileName":"MINJU_SOLOIST","fandom":"WIZ*ONE","name":"Minju","age":21}
	,{"country":"South Korea","agency":"Pledis Entertainment","counter2":3,"city":"Chuncheon","zodiac":"Capricorn","counter1":0,"chineseZodiac":"Ox","groupNameUpper":"FROMIS_9","positions":"Leader,Lead Dancer,Vocalist,Rapper,Visual","nameUpper":"SAEROM","zodiacId":10,"counter":3,"birthDate":19970107,"realName":"Lee Saerom","idolId":79,"chineseZodiacId":2,"groupName":"fromis_9","imageFileName":"SAEROM_FROMIS9","fandom":"Flover","name":"Saerom","age":25}
	,{"country":"Japan","agency":"JYP Entertainment","counter2":3,"city":"Kyoto","zodiac":"Scorpius","counter1":0,"chineseZodiac":"Rat","groupNameUpper":"TWICE","positions":"Main Dancer,Sub Vocalist,Sub Rapper","nameUpper":"MOMO","zodiacId":8,"counter":3,"birthDate":19961109,"realName":"Hirai Momo","idolId":80,"chineseZodiacId":1,"groupName":"Twice","imageFileName":"MOMO_TWICE","fandom":"ONCE","name":"Momo","age":25}
	,{"country":"China","agency":"Cube Entertainment","counter2":5,"city":"Beijing","zodiac":"Libra","counter1":4,"chineseZodiac":"Rabbit","groupNameUpper":"(G)I-DLE","positions":"Lead Dancer,Sub Vocalist,Sub Rapper,Face of the group","nameUpper":"YUQI","zodiacId":7,"counter":9,"birthDate":19990923,"realName":"Song Yuqi","idolId":81,"chineseZodiacId":4,"groupName":"(g)i-dle","imageFileName":"YUQI_GIDLE","fandom":"Neverland","name":"Yuqi","age":22}
	,{"country":"South Korea","agency":"WM Entertainment","counter2":1,"city":"Okcheon/North Chungcheong","zodiac":"Aries","counter1":1,"chineseZodiac":"Ox","groupNameUpper":"OH MY GIRL","positions":"Lead Vocalist,Lead Dancer,Visual","nameUpper":"JIHO","zodiacId":1,"counter":2,"birthDate":19970404,"realName":"Kim Jiho","idolId":82,"chineseZodiacId":2,"groupName":"Oh My Girl","imageFileName":"JIHO_OHMYGIRL","fandom":"Miracle","name":"Jiho","age":25}
	,{"country":"South Korea","agency":"WAKEONE and Swing Entertainment","counter2":0,"city":"Incheon","zodiac":"Leo","counter1":3,"chineseZodiac":"Rooster","groupNameUpper":"KEP1ER","positions":"Maknae","nameUpper":"YESEO","zodiacId":5,"counter":3,"birthDate":20050822,"realName":"Kang Yeseo","idolId":83,"chineseZodiacId":10,"groupName":"Kep1er","imageFileName":"YESEO_KEP1ER","fandom":"Kep1ian","name":"Yeseo","age":17}
	,{"country":"Taiwan","agency":"JYP Entertainment","counter2":1,"city":"Tainan","zodiac":"Gemini","counter1":0,"chineseZodiac":"Rabbit","groupNameUpper":"TWICE","positions":"Lead Dancer,Sub Vocalist,Visual,Maknae","nameUpper":"TZUYU","zodiacId":3,"counter":1,"birthDate":19990614,"realName":"Chou Tzuyu","idolId":84,"chineseZodiacId":4,"groupName":"Twice","imageFileName":"TZUYU_TWICE","fandom":"ONCE","name":"Tzuyu","age":23}
	,{"country":"Japan","agency":"MYSTIC Story","counter2":0,"city":"Osaka","zodiac":"Aquarius","counter1":1,"chineseZodiac":"Dog","groupNameUpper":"BILLLIE","positions":"Sub Vocalist,Maknae","nameUpper":"HARUNA","zodiacId":11,"counter":1,"birthDate":20060130,"realName":"Osato Haruna","idolId":85,"chineseZodiacId":11,"groupName":"Billlie","imageFileName":"HARUNA_BILLLIE","fandom":"Belllie've","name":"Haruna","age":16}
	,{"country":"South Korea","agency":"Dreamcatcher Company","counter2":6,"city":"Seongnam","zodiac":"Aquarius","counter1":1,"chineseZodiac":"Rabbit","groupNameUpper":"DREAMCATCHER","positions":"Lead Rapper,Sub Vocalist,Maknae","nameUpper":"GAHYEON","zodiacId":11,"counter":7,"birthDate":19990203,"realName":"Lee Gahyeon","idolId":86,"chineseZodiacId":4,"groupName":"Dreamcatcher","imageFileName":"GAHYEON_DREAMCATCHER","fandom":"InSomnia","name":"Gahyeon","age":23}
	,{"country":"South Korea","agency":"JYP Entertainment","counter2":0,"city":"Namyangju/Gyeonggi-do","zodiac":"Aries","counter1":3,"chineseZodiac":"Rooster","groupNameUpper":"NMIXX","positions":"Vocalist,Dancer,Rapper","nameUpper":"JIWOO","zodiacId":1,"counter":3,"birthDate":20050413,"realName":"Kim Jiwoo","idolId":87,"chineseZodiacId":10,"groupName":"NMIXX","imageFileName":"JIWOO_NMIXX","fandom":"NSWER","name":"Jiwoo","age":17}
	,{"country":"South Korea","agency":"RBW","counter2":0,"city":"Nam-gu/Gwangji","zodiac":"Virgo","counter1":2,"chineseZodiac":"Rabbit","groupNameUpper":"PURPLE KISS","positions":"Main Vocalist,Lead Dancer","nameUpper":"GOEUN","zodiacId":6,"counter":2,"birthDate":19990903,"realName":"Na Goeun","idolId":88,"chineseZodiacId":4,"groupName":"Purple Kiss","imageFileName":"GOEUN_PURPLEKISS","fandom":"PLORY","name":"Goeun","age":23}
	,{"country":"South Korea","agency":"RBW","counter2":0,"city":"Busan","zodiac":"Aquarius","counter1":10,"chineseZodiac":"Dragon","groupNameUpper":"PURPLE KISS","positions":"Main Dancer,Vocalist","nameUpper":"DOSIE","zodiacId":11,"counter":10,"birthDate":20000211,"realName":"Jang Eunseong","idolId":89,"chineseZodiacId":5,"groupName":"Purple Kiss","imageFileName":"DOSIE_PURPLEKISS","fandom":"PLORY","name":"Dosie","age":22}
	,{"country":"South Korea","agency":"BlockBerryCreative","counter2":0,"city":"Busan","zodiac":"Gemini","counter1":6,"chineseZodiac":"Ox","groupNameUpper":"LOONA","positions":"Leader,Dancer,Vocalist,Rapper","nameUpper":"YVES","zodiacId":3,"counter":6,"birthDate":19970524,"realName":"Ha Sooyoung","idolId":90,"chineseZodiacId":2,"groupName":"LOONA","imageFileName":"YVES_LOONA","fandom":"Orbit","name":"Yves","age":25}
	,{"country":"Thailand","agency":"Cube Entertainment","counter2":0,"city":"Bangkok","zodiac":"Scorpius","counter1":1,"chineseZodiac":"Ox","groupNameUpper":"(G)I-DLE","positions":"Main Vocalist","nameUpper":"MINNIE","zodiacId":8,"counter":1,"birthDate":19971023,"realName":"Minnie Nicha Yontararak","idolId":91,"chineseZodiacId":2,"groupName":"(g)i-dle","imageFileName":"MINNIE_GIDLE","fandom":"Neverland","name":"Minnie","age":24}
	,{"country":"Japan","agency":"RBW","counter2":0,"city":"---","zodiac":"Scorpius","counter1":2,"chineseZodiac":"Horse","groupNameUpper":"PURPLE KISS","positions":"Main Rapper,Lead Dancer,Vocalist","nameUpper":"YUKI","zodiacId":8,"counter":2,"birthDate":20021106,"realName":"Mori Koyuki","idolId":92,"chineseZodiacId":7,"groupName":"Purple Kiss","imageFileName":"YUKI_PURPLEKISS","fandom":"PLORY","name":"Yuki","age":19}
	,{"country":"South Korea","agency":"RBW","counter2":0,"city":"Gangdong-gu/Seoul","zodiac":"Virgo","counter1":2,"chineseZodiac":"Ox","groupNameUpper":"PURPLE KISS","positions":"Vocalist","nameUpper":"JIEUN","zodiacId":6,"counter":2,"birthDate":19970904,"realName":"Park Jieun","idolId":93,"chineseZodiacId":2,"groupName":"Purple Kiss","imageFileName":"JIEUN_PURPLEKISS","fandom":"PLORY","name":"Jieun","age":25}
	,{"country":"South Korea","agency":"RBW","counter2":0,"city":"---","zodiac":"Taurus","counter1":1,"chineseZodiac":"Horse","groupNameUpper":"PURPLE KISS","positions":"Main Dancer,Vocalist","nameUpper":"IREH","zodiacId":2,"counter":1,"birthDate":20020430,"realName":"Cho Seoyoung","idolId":94,"chineseZodiacId":7,"groupName":"Purple Kiss","imageFileName":"IREH_PURPLEKISS","fandom":"PLORY","name":"Ireh","age":20}
	,{"country":"Japan","agency":"Woollim Entertainment","counter2":1,"city":"Kashima/Ibaraki","zodiac":"Libra","counter1":2,"chineseZodiac":"Ox","groupNameUpper":"ROCKET PUNCH","positions":"Vocalist,Dancer","nameUpper":"JURI","zodiacId":7,"counter":3,"birthDate":19971003,"realName":"Takahashi Juri","idolId":95,"chineseZodiacId":2,"groupName":"Rocket Punch","imageFileName":"JURI_ROCKETPUNCH","fandom":"KETCHY","name":"Juri","age":24}
	,{"country":"South Korea","agency":"8D Entertainment","counter2":1,"city":"Yangsan/South Gyeongsang","zodiac":"Cancer","counter1":2,"chineseZodiac":"Rabbit","groupNameUpper":"SOLOIST","positions":"---","nameUpper":"HYEWON","zodiacId":4,"counter":3,"birthDate":19990705,"realName":"Kang Hyewon","idolId":96,"chineseZodiacId":4,"groupName":"soloist","imageFileName":"HYEWON_SOLOIST","fandom":"WIZ*ONE","name":"Hyewon","age":23}
	,{"country":"South Korea","agency":"JYP Entertainment","counter2":1,"city":"Busan","zodiac":"Aries","counter1":6,"chineseZodiac":"Monkey","groupNameUpper":"NMIXX","positions":"Vocalist,Dancer,Rapper","nameUpper":"JINNI","zodiacId":1,"counter":7,"birthDate":20040416,"realName":"Choi Yunjin","idolId":97,"chineseZodiacId":9,"groupName":"NMIXX","imageFileName":"JINNI_NMIXX","fandom":"NSWER","name":"Jinni","age":18}
	,{"country":"South Korea","agency":"JYP Entertainment","counter2":3,"city":"Bundang-gu/Seongnam/Gyeonggi-do","zodiac":"Gemini","counter1":3,"chineseZodiac":"Dog","groupNameUpper":"NMIXX","positions":"Vocalist,Dancer,Rapper,Maknae","nameUpper":"KYUJIN","zodiacId":3,"counter":6,"birthDate":20060526,"realName":"Jang Kyujin","idolId":98,"chineseZodiacId":11,"groupName":"NMIXX","imageFileName":"KYUJIN_NMIXX","fandom":"NSWER","name":"Kyujin","age":16}
	,{"country":"South Korea","agency":"ALLART Entertainment","counter2":2,"city":"---","zodiac":"Cancer","counter1":6,"chineseZodiac":"Snake","groupNameUpper":"PIXY","positions":"Main Dancer,Lead Vocalist","nameUpper":"DIA","zodiacId":4,"counter":8,"birthDate":20010716,"realName":"Choi Eunji","idolId":99,"chineseZodiacId":6,"groupName":"Pixy","imageFileName":"DIA_PIXY","fandom":"Winxy","name":"Dia","age":21}
	,{"country":"Japan","agency":"Cube Entertainment","counter2":0,"city":"Kanagawa","zodiac":"Aries","counter1":1,"chineseZodiac":"Goat","groupNameUpper":"LIGHTSUM","positions":"Sub Vocalist","nameUpper":"HINA","zodiacId":1,"counter":1,"birthDate":20030407,"realName":"Nagai Hina","idolId":100,"chineseZodiacId":8,"groupName":"Lightsum","imageFileName":"HINA_LIGHTSUM","fandom":"SUMIT","name":"Hina","age":19}
	,{"country":"South Korea","agency":"iMe Entertainment","counter2":0,"city":"Icheon/Gyeonggi-do","zodiac":"Pisces","counter1":3,"chineseZodiac":"Horse","groupNameUpper":"DREAM NOTE","positions":"Vocalist,Rapper,Visual,Maknae","nameUpper":"EUNJO","zodiacId":12,"counter":3,"birthDate":20020307,"realName":"Park Eunjo","idolId":101,"chineseZodiacId":7,"groupName":"Dream Note","imageFileName":"EUNJO_DREAMNOTE","fandom":"Page","name":"Eunjo","age":20}
	,{"country":"South Korea","agency":"WM Entertainment","counter2":0,"city":"Chuncheon/Gangwon","zodiac":"Virgo","counter1":4,"chineseZodiac":"Ox","groupNameUpper":"OH MY GIRL","positions":"Sub Vocalist","nameUpper":"YUBIN","zodiacId":6,"counter":4,"birthDate":19970909,"realName":"Bae Yubin","idolId":102,"chineseZodiacId":2,"groupName":"Oh My Girl","imageFileName":"YUBIN_OHMYGIRL","fandom":"Miracle","name":"Yubin","age":24}
	,{"country":"South Korea","agency":"Source Music","counter2":3,"city":"Sangju/Gyeongsangbuk-do","zodiac":"Scorpius","counter1":1,"chineseZodiac":"Rooster","groupNameUpper":"LE SSERAFIM","positions":"Vocalist","nameUpper":"GARAM","zodiacId":8,"counter":4,"birthDate":20051116,"realName":"Kim Garam","idolId":103,"chineseZodiacId":10,"groupName":"LE SSERAFIM","imageFileName":"GARAM_LESSERAFIM","fandom":"FEARNOT","name":"Garam","age":16}
	,{"country":"South Korea","agency":"JYP Entertainment","counter2":1,"city":"Suwon","zodiac":"Sagittarius","counter1":3,"chineseZodiac":"Goat","groupNameUpper":"ITZY","positions":"Lead Rapper,Lead Dancer,Sub Vocalist,Visual,Maknae","nameUpper":"YUNA","zodiacId":9,"counter":4,"birthDate":20031209,"realName":"Shin Yuna","idolId":104,"chineseZodiacId":8,"groupName":"ITZY","imageFileName":"YUNA_ITZY","fandom":"MIDZY","name":"Yuna","age":18}
	,{"country":"South Korea","agency":"SM Entertainment","counter2":0,"city":"Busan","zodiac":"Capricorn","counter1":2,"chineseZodiac":"Snake","groupNameUpper":"AESPA","positions":"Lead Vocalist,Lead Dancer,Visual","nameUpper":"WINTER","zodiacId":10,"counter":2,"birthDate":20010101,"realName":"Kim Minjeong","idolId":105,"chineseZodiacId":6,"groupName":"aespa","imageFileName":"WINTER_AESPA","fandom":"MY","name":"Winter","age":21}
	,{"country":"Japan","agency":"Source Music","counter2":1,"city":"Kagoshima","zodiac":"Pisces","counter1":0,"chineseZodiac":"Tiger","groupNameUpper":"LE SSERAFIM","positions":"Vocalist","nameUpper":"SAKURA","zodiacId":12,"counter":1,"birthDate":19980319,"realName":"Miyawaki Sakura","idolId":106,"chineseZodiacId":3,"groupName":"LE SSERAFIM","imageFileName":"SAKURA_LESSERAFIM","fandom":"FEARNOT","name":"Sakura","age":24}
	,{"country":"South Korea","agency":"Source Music","counter2":1,"city":"Miryang/Gyeongsangnam-do","zodiac":"Scorpius","counter1":4,"chineseZodiac":"Dog","groupNameUpper":"LE SSERAFIM","positions":"Vocalist,Dancer,Maknae","nameUpper":"EUNCHAE","zodiacId":8,"counter":5,"birthDate":20061110,"realName":"Hong Eunchae","idolId":107,"chineseZodiacId":11,"groupName":"LE SSERAFIM","imageFileName":"EUNCHAE_LESSERAFIM","fandom":"FEARNOT","name":"Eunchae","age":15}
	,{"country":"China","agency":"WAKEONE and Swing Entertainment","counter2":6,"city":"Sichuan","zodiac":"Scorpius","counter1":11,"chineseZodiac":"Rabbit","groupNameUpper":"KEP1ER","positions":"---","nameUpper":"XIAOTING","zodiacId":8,"counter":17,"birthDate":19991112,"realName":"Shen Xiaoting","idolId":108,"chineseZodiacId":4,"groupName":"Kep1er","imageFileName":"XIAOTING_KEP1ER","fandom":"Kep1ian","name":"Xiaoting","age":22}
	,{"country":"South Korea","agency":"BlockBerryCreative","counter2":0,"city":"Cheongju","zodiac":"Aquarius","counter1":5,"chineseZodiac":"Rabbit","groupNameUpper":"LOONA","positions":"Leader,Vocalist,Dancer","nameUpper":"KIMLIP","zodiacId":11,"counter":5,"birthDate":19990210,"realName":"Kim Jungeun","idolId":109,"chineseZodiacId":4,"groupName":"LOONA","imageFileName":"KIMLIP_LOONA","fandom":"Orbit","name":"KimLip","age":23}
	,{"country":"South Korea","agency":"JYP Entertainment","counter2":0,"city":"Yangsan/Gyeongsangnam-do","zodiac":"Capricorn","counter1":2,"chineseZodiac":"Monkey","groupNameUpper":"NMIXX","positions":"Vocalist,Dancer","nameUpper":"BAE","zodiacId":10,"counter":2,"birthDate":20041228,"realName":"Bae Jinsol","idolId":110,"chineseZodiacId":9,"groupName":"NMIXX","imageFileName":"BAE_NMIXX","fandom":"NSWER","name":"Bae","age":17}
	,{"country":"China","agency":"FC ENM","counter2":13,"city":"---","zodiac":"Gemini","counter1":6,"chineseZodiac":"Horse","groupNameUpper":"ILY:1","positions":"Vocalist","nameUpper":"RONA","zodiacId":3,"counter":19,"birthDate":20020605,"realName":"Chang Ching","idolId":111,"chineseZodiacId":7,"groupName":"ily:1","imageFileName":"RONA_ILY1","fandom":"Only:1","name":"Rona","age":20}
	,{"country":"South Korea","agency":"WAKEONE and Swing Entertainment","counter2":0,"city":"Jeonju/North Jeolla","zodiac":"Leo","counter1":1,"chineseZodiac":"Rat","groupNameUpper":"KEP1ER","positions":"Leader","nameUpper":"YUJIN","zodiacId":5,"counter":1,"birthDate":19960812,"realName":"Choi Yujin","idolId":112,"chineseZodiacId":1,"groupName":"Kep1er","imageFileName":"YUJIN_KEP1ER","fandom":"Kep1ian","name":"Yujin","age":26}
	,{"country":"South Korea","agency":"BlockBerryCreative","counter2":0,"city":"Suncheon/South Jeolla","zodiac":"Leo","counter1":11,"chineseZodiac":"Ox","groupNameUpper":"LOONA","positions":"Leader,Vocalist,Rapper","nameUpper":"HASEUL","zodiacId":5,"counter":11,"birthDate":19970818,"realName":"Cho Haseul","idolId":113,"chineseZodiacId":2,"groupName":"LOONA","imageFileName":"HASEUL_LOONA","fandom":"Orbit","name":"Haseul","age":25}
	,{"country":"South Korea","agency":"MYSTIC Story","counter2":2,"city":"Gwangmyeong/Gyeonggi-do","zodiac":"Aquarius","counter1":1,"chineseZodiac":"Rooster","groupNameUpper":"BILLLIE","positions":"Main Rapper,Lead Dancer","nameUpper":"SIYOON","zodiacId":11,"counter":3,"birthDate":20050216,"realName":"Kim Siyoon","idolId":114,"chineseZodiacId":10,"groupName":"Billlie","imageFileName":"SIYOON_BILLLIE","fandom":"Belllie've","name":"Siyoon","age":17}
	,{"country":"Taiwan","agency":"FC ENM","counter2":0,"city":"---","zodiac":"Taurus","counter1":1,"chineseZodiac":"Goat","groupNameUpper":"ILY:1","positions":"Rapper,Maknae","nameUpper":"ELVA","zodiacId":2,"counter":1,"birthDate":20030505,"realName":"Lee Yonghwa","idolId":115,"chineseZodiacId":8,"groupName":"ily:1","imageFileName":"ELVA_ILY1","fandom":"Only:1","name":"Elva","age":19}
	,{"country":"South Korea","agency":"JYP Entertainment","counter2":0,"city":"Incheon","zodiac":"Pisces","counter1":5,"chineseZodiac":"Goat","groupNameUpper":"NMIXX","positions":"Leader,Vocalist","nameUpper":"HAEWON","zodiacId":12,"counter":5,"birthDate":20030225,"realName":"Oh Haewon","idolId":116,"chineseZodiacId":8,"groupName":"NMIXX","imageFileName":"HAEWON_NMIXX","fandom":"NSWER","name":"Haewon","age":19}
	,{"country":"South Korea","agency":"NV Entertainment","counter2":1,"city":"Seocho-gu/Seoul","zodiac":"Aquarius","counter1":2,"chineseZodiac":"Goat","groupNameUpper":"WOO!AH!","positions":"Lead Vocalist,Visual","nameUpper":"WOOYEON","zodiacId":11,"counter":3,"birthDate":20030211,"realName":"Park Jinkyung","idolId":117,"chineseZodiacId":8,"groupName":"woo!ah!","imageFileName":"WOOYEON_WOOAH","fandom":"wow!","name":"Wooyeon","age":19}
	,{"country":"South Korea","agency":"Starship Entertainment","counter2":2,"city":"Bupyeong-gu/Incheon","zodiac":"Libra","counter1":2,"chineseZodiac":"Horse","groupNameUpper":"IVE","positions":"Main Dancer,Rapper","nameUpper":"GAEUL","zodiacId":7,"counter":4,"birthDate":20020924,"realName":"Kim Gaeul","idolId":118,"chineseZodiacId":7,"groupName":"IVE","imageFileName":"GAEUL_IVE","fandom":"DIVE","name":"Gaeul","age":19}
	,{"country":"South Korea","agency":"Starship Entertainment","counter2":0,"city":"Cheongju/North Chungcheong","zodiac":"Virgo","counter1":7,"chineseZodiac":"Goat","groupNameUpper":"IVE","positions":"Leader,Main Dancer,Vocalist","nameUpper":"YUJIN","zodiacId":6,"counter":7,"birthDate":20030901,"realName":"Ahn Yujin","idolId":119,"chineseZodiacId":8,"groupName":"IVE","imageFileName":"YUJIN_IVE","fandom":"DIVE","name":"Yujin","age":19}
	,{"country":"South Korea","agency":"Woollim Entertainment","counter2":1,"city":"Seoul","zodiac":"Libra","counter1":3,"chineseZodiac":"Pig","groupNameUpper":"SOLOIST","positions":"---","nameUpper":"EUNBI","zodiacId":7,"counter":4,"birthDate":19950927,"realName":"Kwon Eunbi","idolId":120,"chineseZodiacId":12,"groupName":"soloist","imageFileName":"EUNBI_SOLOIST","fandom":"RUBI","name":"Eunbi","age":26}
	,{"country":"South Korea","agency":"M25","counter2":0,"city":"Sang-dong/Yeoju/Gyeonggi-do","zodiac":"Capricorn","counter1":2,"chineseZodiac":"Pig","groupNameUpper":"CLASS:Y","positions":"Lead Dancer,Vocalist","nameUpper":"RIWON","zodiacId":10,"counter":2,"birthDate":20070111,"realName":"Kim Riwon","idolId":121,"chineseZodiacId":12,"groupName":"CLASS:y","imageFileName":"RIWON_CLASSY","fandom":"CLIKE:y","name":"Riwon","age":15}
	,{"country":"South Korea","agency":"Yuehua Entertainment","counter2":1,"city":"Sambang-dong/Gimhae/Gyeongsangnam-do","zodiac":"Capricorn","counter1":0,"chineseZodiac":"Dragon","groupNameUpper":"EVERGLOW","positions":"Main Vocalist,Main Dancer,Sub Rapper","nameUpper":"MIA","zodiacId":10,"counter":1,"birthDate":20000113,"realName":"Han Eunji","idolId":122,"chineseZodiacId":5,"groupName":"Everglow","imageFileName":"MIA_EVERGLOW","fandom":"For Ever","name":"Mia","age":22}
	,{"country":"South Korea","agency":"Cube Entertainment","counter2":0,"city":"Chuncheon/Gangwon-do","zodiac":"Sagittarius","counter1":2,"chineseZodiac":"Horse","groupNameUpper":"LIGHTSUM","positions":"Main Vocalist,Lead Dancer,Center","nameUpper":"NAYOUNG","zodiacId":9,"counter":2,"birthDate":20021130,"realName":"Kim Nayoung","idolId":123,"chineseZodiacId":7,"groupName":"Lightsum","imageFileName":"NAYOUNG_LIGHTSUM","fandom":"SUMIT","name":"Nayoung","age":19}
	,{"country":"New Zeland","agency":"YG Entertainment","counter2":1,"city":"Auckland","zodiac":"Aquarius","counter1":0,"chineseZodiac":"Ox","groupNameUpper":"BLACKPINK","positions":"Main Vocalist,Lead Dancer","nameUpper":"ROSE","zodiacId":11,"counter":1,"birthDate":19970211,"realName":"Park Chaeyoung","idolId":124,"chineseZodiacId":2,"groupName":"Blackpink","imageFileName":"ROSE_BLACKPINK","fandom":"BLINK","name":"Rose","age":25}
	,{"country":"South Korea","agency":"RBW","counter2":0,"city":"---","zodiac":"Cancer","counter1":1,"chineseZodiac":"Goat","groupNameUpper":"PURPLE KISS","positions":"Main Vocalist,Maknae","nameUpper":"SWAN","zodiacId":4,"counter":1,"birthDate":20030711,"realName":"Park Sujin","idolId":125,"chineseZodiacId":8,"groupName":"Purple Kiss","imageFileName":"SWAN_PURPLEKISS","fandom":"PLORY","name":"Swan","age":19}
	,{"country":"South Korea","agency":"M25","counter2":0,"city":"Suwon/Gyeonggi-do","zodiac":"Cancer","counter1":3,"chineseZodiac":"Snake","groupNameUpper":"CLASS:Y","positions":"Lead Vocalist,Rapper,Visual","nameUpper":"HYUNGSEO","zodiacId":4,"counter":3,"birthDate":20010625,"realName":"Myeong Hyungseo","idolId":126,"chineseZodiacId":6,"groupName":"CLASS:y","imageFileName":"HYUNGSEO_CLASSY","fandom":"CLIKE:y","name":"Hyungseo","age":21}
	,{"country":"Japan","agency":"Source Music","counter2":1,"city":"Kochi","zodiac":"Leo","counter1":2,"chineseZodiac":"Goat","groupNameUpper":"LE SSERAFIM","positions":"Vocalist,Rapper,Dancer","nameUpper":"KAZUHA","zodiacId":5,"counter":3,"birthDate":20030809,"realName":"Nakamura Kazuha","idolId":127,"chineseZodiacId":8,"groupName":"LE SSERAFIM","imageFileName":"KAZUHA_LESSERAFIM","fandom":"FEARNOT","name":"Kazuha","age":19}
	,{"country":"South Korea","agency":"iMe Entertainment","counter2":1,"city":"Yeongju-si/North Gyeongsang","zodiac":"Taurus","counter1":3,"chineseZodiac":"Dragon","groupNameUpper":"DREAM NOTE","positions":"Leader,Lead Dancer,Lead Vocalist","nameUpper":"YOUI","zodiacId":2,"counter":4,"birthDate":20000424,"realName":"Kim Jihyeon","idolId":128,"chineseZodiacId":5,"groupName":"Dream Note","imageFileName":"YOUI_DREAMNOTE","fandom":"Page","name":"YOUI","age":22}
	,{"country":"South Korea","agency":"Starship Entertainment","counter2":3,"city":"Gwangmyung/Gyeonggi-do","zodiac":"Leo","counter1":1,"chineseZodiac":"Rabbit","groupNameUpper":"WJSN","positions":"Main Vocalist,Maknae","nameUpper":"YEONJUNG","zodiacId":5,"counter":4,"birthDate":19990803,"realName":"Yoo Yeonjung","idolId":129,"chineseZodiacId":4,"groupName":"WJSN","imageFileName":"YEONJUNG_WJSN","fandom":"Ujung","name":"Yeonjung","age":23}
	,{"country":"South Korea","agency":"Starship Entertainment","counter2":1,"city":"Seoul","zodiac":"Capricorn","counter1":2,"chineseZodiac":"Rabbit","groupNameUpper":"WJSN","positions":"Main Dancer,Vocalist,Rapper","nameUpper":"YEOREUM","zodiacId":10,"counter":3,"birthDate":19990110,"realName":"Lee Jinsuk","idolId":130,"chineseZodiacId":4,"groupName":"WJSN","imageFileName":"YEOREUM_WJSN","fandom":"Ujung","name":"Yeoreum","age":23}
	,{"country":"South Korea","agency":"Source Music","counter2":1,"city":"Gangnam-gu/Seoul","zodiac":"Scorpius","counter1":8,"chineseZodiac":"Snake","groupNameUpper":"LE SSERAFIM","positions":"Vocalist","nameUpper":"YUNJIN","zodiacId":8,"counter":9,"birthDate":20011108,"realName":"Huh Yunjin","idolId":131,"chineseZodiacId":6,"groupName":"LE SSERAFIM","imageFileName":"YUNJIN_LESSERAFIM","fandom":"FEARNOT","name":"Yunjin","age":20}
	,{"country":"South Korea","agency":"KM Entertainment","counter2":0,"city":"Wonju/Gangwon","zodiac":"Aquarius","counter1":4,"chineseZodiac":"Monkey","groupNameUpper":"ICHILLIN","positions":"Lead Dancer,Sub Vocalist,Center","nameUpper":"YEJU","zodiacId":11,"counter":4,"birthDate":20040201,"realName":"Kim Yeju","idolId":132,"chineseZodiacId":9,"groupName":"ichillin","imageFileName":"YEJU_ICHILLIN","fandom":"Willing","name":"Yeju","age":18}
	,{"country":"USA","agency":"KM Entertainment","counter2":0,"city":"Los Angeles/California","zodiac":"Scorpius","counter1":4,"chineseZodiac":"Snake","groupNameUpper":"ICHILLIN","positions":"Main Rapper,Lead Dancer","nameUpper":"JACKIE","zodiacId":8,"counter":4,"birthDate":20011117,"realName":"Kang Chaeyeon/Jackeline Kang","idolId":133,"chineseZodiacId":6,"groupName":"ichillin","imageFileName":"JACKIE_ICHILLIN","fandom":"Willing","name":"Jackie","age":20}
	,{"country":"South Korea","agency":"Source Music","counter2":1,"city":"Incheon","zodiac":"Leo","counter1":1,"chineseZodiac":"Rat","groupNameUpper":"GFRIEND","positions":"Lead Dancer,Vocalist,Center,Face of the Group","nameUpper":"YERIN","zodiacId":5,"counter":2,"birthDate":19960819,"realName":"Jung Yerin","idolId":134,"chineseZodiacId":1,"groupName":"Gfriend","imageFileName":"YERIN_GFRIEND","fandom":"BUDDY","name":"Yerin","age":26}
	,{"country":"South Korea","agency":"Dreamcatcher Company","counter2":5,"city":"Changwon","zodiac":"Leo","counter1":1,"chineseZodiac":"Dog","groupNameUpper":"DREAMCATCHER","positions":"Main Dancer,Sub Vocalist,Lead Rapper","nameUpper":"SUA","zodiacId":5,"counter":6,"birthDate":19940810,"realName":"Kim Bora","idolId":135,"chineseZodiacId":11,"groupName":"Dreamcatcher","imageFileName":"SUA_DREAMCATCHER","fandom":"InSomnia","name":"Sua","age":28}
	,{"country":"South Korea","agency":"KM Entertainment","counter2":0,"city":"Yeongwol/Gangwon-do","zodiac":"Capricorn","counter1":1,"chineseZodiac":"Monkey","groupNameUpper":"ICHILLIN","positions":"Sub Vocalist,Sub Dancer","nameUpper":"SOHEE","zodiacId":10,"counter":1,"birthDate":20040101,"realName":"Um Sohee","idolId":136,"chineseZodiacId":9,"groupName":"ichillin","imageFileName":"SOHEE_ICHILLIN","fandom":"Willing","name":"Sohee","age":18}
	,{"country":"South Korea","agency":"Cube Entertainment","counter2":0,"city":"Seoul","zodiac":"Aries","counter1":2,"chineseZodiac":"Monkey","groupNameUpper":"LIGHTSUM","positions":"Leader,Main Dancer,Lead Vocalist","nameUpper":"JUHYEON","zodiacId":1,"counter":2,"birthDate":20040408,"realName":"Lee Juhyeon","idolId":137,"chineseZodiacId":9,"groupName":"Lightsum","imageFileName":"JUHYEON_LIGHTSUM","fandom":"SUMIT","name":"Juhyeon","age":18}
	,{"country":"South Korea","agency":"M25","counter2":4,"city":"Deokpung-dong/Hanam","zodiac":"Gemini","counter1":3,"chineseZodiac":"Goat","groupNameUpper":"CLASS:Y","positions":"Main Vocalist","nameUpper":"CHAEWON","zodiacId":3,"counter":7,"birthDate":20030604,"realName":"Yoon Chaewon","idolId":138,"chineseZodiacId":8,"groupName":"CLASS:y","imageFileName":"CHAEWON_CLASSY","fandom":"CLIKE:y","name":"Chaewon","age":19}
	,{"country":"South Korea","agency":"M25","counter2":2,"city":"Bangok-dong/Wonju/Gangwon-do","zodiac":"Leo","counter1":5,"chineseZodiac":"Pig","groupNameUpper":"CLASS:Y","positions":"Main Vocalist,Center","nameUpper":"JIMIN","zodiacId":5,"counter":7,"birthDate":20070725,"realName":"Won Jimin","idolId":139,"chineseZodiacId":12,"groupName":"CLASS:y","imageFileName":"JIMIN_CLASSY","fandom":"CLIKE:y","name":"Jimin","age":15}
	,{"country":"South Korea","agency":"Source Music","counter2":5,"city":"Seoul","zodiac":"Leo","counter1":4,"chineseZodiac":"Dragon","groupNameUpper":"LE SSERAFIM","positions":"Leader,Vocalist","nameUpper":"CHAEWON","zodiacId":5,"counter":9,"birthDate":20000801,"realName":"Kim Chaewon","idolId":140,"chineseZodiacId":5,"groupName":"LE SSERAFIM","imageFileName":"CHAEWON_LESSERAFIM","fandom":"FEARNOT","name":"Chaewon","age":22}
	,{"country":"South Korea","agency":"iMe Entertainment","counter2":0,"city":"Gwangsan-gu/Gwangju","zodiac":"Leo","counter1":1,"chineseZodiac":"Dragon","groupNameUpper":"DREAM NOTE","positions":"Main Vocalist","nameUpper":"LARA","zodiacId":5,"counter":1,"birthDate":20000809,"realName":"Moon Sinae","idolId":141,"chineseZodiacId":5,"groupName":"Dream Note","imageFileName":"LARA_DREAMNOTE","fandom":"Page","name":"Lara","age":22}
	,{"country":"Japan","agency":"WAKEONE and Swing Entertainment","counter2":0,"city":"Fukuoka","zodiac":"Pisces","counter1":1,"chineseZodiac":"Monkey","groupNameUpper":"KEP1ER","positions":"---","nameUpper":"HIKARU","zodiacId":12,"counter":1,"birthDate":20040312,"realName":"Ezaki Hikaru","idolId":142,"chineseZodiacId":9,"groupName":"Kep1er","imageFileName":"HIKARU_KEP1ER","fandom":"Kep1ian","name":"Hikaru","age":18}
	,{"country":"South Korea","agency":"M25","counter2":0,"city":"Songpa-gu/Seoul","zodiac":"Sagittarius","counter1":2,"chineseZodiac":"Goat","groupNameUpper":"CLASS:Y","positions":"Leader,Main Dancer,Lead Rapper,Vocalist","nameUpper":"HYEJU","zodiacId":9,"counter":2,"birthDate":20031209,"realName":"Hong Hyeju","idolId":143,"chineseZodiacId":8,"groupName":"CLASS:y","imageFileName":"HYEJU_CLASSY","fandom":"CLIKE:y","name":"Hyeju","age":18}
	,{"country":"South Korea","agency":"Cube Entertainment","counter2":0,"city":"Eunpyeong-gu/Seoul","zodiac":"Virgo","counter1":1,"chineseZodiac":"Horse","groupNameUpper":"LIGHTSUM","positions":"Main Vocalist","nameUpper":"CHOWON","zodiacId":6,"counter":1,"birthDate":20020916,"realName":"Han Chowon","idolId":144,"chineseZodiacId":7,"groupName":"Lightsum","imageFileName":"CHOWON_LIGHTSUM","fandom":"SUMIT","name":"Chowon","age":19}
	,{"country":"Japan","agency":"FC ENM","counter2":0,"city":"Osaka","zodiac":"Cancer","counter1":1,"chineseZodiac":"Horse","groupNameUpper":"ILY:1","positions":"Lead Vocalist","nameUpper":"RIRIKA","zodiacId":4,"counter":1,"birthDate":20020702,"realName":"Kishida Ririka","idolId":145,"chineseZodiacId":7,"groupName":"ily:1","imageFileName":"RIRIKA_ILY1","fandom":"Only:1","name":"Ririka","age":20}
	,{"country":"South Korea","agency":"MLD Entertainment","counter2":1,"city":"Seoul","zodiac":"Leo","counter1":1,"chineseZodiac":"Rabbit","groupNameUpper":"MOMOLAND","positions":"Lead Vocalist,Lead Dancer,Rapper,Face of the Group","nameUpper":"JOOE","zodiacId":5,"counter":2,"birthDate":19990818,"realName":"Lee Joowon","idolId":146,"chineseZodiacId":4,"groupName":"Momoland","imageFileName":"JOOE_MOMOLAND","fandom":"Merry Go Round","name":"Jooe","age":23}
	,{"country":"South Korea","agency":"MLD Entertainment","counter2":1,"city":"Wonju","zodiac":"Libra","counter1":1,"chineseZodiac":"Rabbit","groupNameUpper":"MOMOLAND","positions":"Main Vocalist","nameUpper":"AHIN","zodiacId":7,"counter":2,"birthDate":19990927,"realName":"Lee Ahin","idolId":147,"chineseZodiacId":4,"groupName":"Momoland","imageFileName":"AHIN_MOMOLAND","fandom":"Merry Go Round","name":"Ahin","age":22}
	,{"country":"South Korea","agency":"MLD Entertainment","counter2":2,"city":"Daegu","zodiac":"Aries","counter1":2,"chineseZodiac":"Dragon","groupNameUpper":"MOMOLAND","positions":"Lead Vocalist,Lead Dancer,Visual,Center,Maknae","nameUpper":"NANCY","zodiacId":1,"counter":4,"birthDate":20000413,"realName":"Nancy Jewel Mcdonie","idolId":148,"chineseZodiacId":5,"groupName":"Momoland","imageFileName":"NANCY_MOMOLAND","fandom":"Merry Go Round","name":"Nancy","age":22}
	,{"country":"South Korea","agency":"BlockBerryCreative","counter2":0,"city":"Incheon","zodiac":"Scorpius","counter1":2,"chineseZodiac":"Dragon","groupNameUpper":"LOONA","positions":"Rapper,Dancer,Vocalist","nameUpper":"GOWON","zodiacId":8,"counter":2,"birthDate":20001119,"realName":"Park Chaewon","idolId":149,"chineseZodiacId":5,"groupName":"LOONA","imageFileName":"GOWON_LOONA","fandom":"Orbit","name":"Gowon","age":21}
	,{"country":"South Korea","agency":"ALLART Entertainment","counter2":1,"city":"Busan","zodiac":"Pisces","counter1":1,"chineseZodiac":"Snake","groupNameUpper":"PIXY","positions":"Main Rapper,Visual","nameUpper":"LOLA","zodiacId":12,"counter":2,"birthDate":20010222,"realName":"Choi Yoojung","idolId":150,"chineseZodiacId":6,"groupName":"Pixy","imageFileName":"LOLA_PIXY","fandom":"Winxy","name":"Lola","age":21}
	,{"country":"South Korea","agency":"Pledis Entertainment","counter2":0,"city":"Seoul","zodiac":"Sagittarius","counter1":2,"chineseZodiac":"Tiger","groupNameUpper":"FROMIS_9","positions":"Lead Dancer,Vocalist,Center","nameUpper":"JISUN","zodiacId":9,"counter":2,"birthDate":19981122,"realName":"Roh Jisun","idolId":151,"chineseZodiacId":3,"groupName":"fromis_9","imageFileName":"JISUN_FROMIS9","fandom":"Flover","name":"Jisun","age":23}
	,{"country":"South Korea","agency":"WAKEONE Entertainment","counter2":0,"city":"Busan","zodiac":"Libra","counter1":2,"chineseZodiac":"Snake","groupNameUpper":"SOLOIST","positions":"---","nameUpper":"YURI","zodiacId":7,"counter":2,"birthDate":20011022,"realName":"Jo Yuri","idolId":152,"chineseZodiacId":6,"groupName":"soloist","imageFileName":"YURI_SOLOIST","fandom":"GLASSY","name":"Yuri","age":20}
	,{"country":"South Korea","agency":"M25","counter2":1,"city":"Gangneung/Gangwon-do","zodiac":"Pisces","counter1":0,"chineseZodiac":"Rat","groupNameUpper":"CLASS:Y","positions":"Main Rapper,Lead Dancer,Vocalist,Maknae","nameUpper":"SEONYU","zodiacId":12,"counter":1,"birthDate":20080320,"realName":"Kim Seonyu","idolId":153,"chineseZodiacId":1,"groupName":"CLASS:y","imageFileName":"SEONYU_CLASSY","fandom":"CLIKE:y","name":"Seonyu","age":14}
	,{"country":"South Korea","agency":"JYP Entertainment","counter2":0,"city":"Seoul","zodiac":"Virgo","counter1":2,"chineseZodiac":"Pig","groupNameUpper":"TWICE","positions":"Lead Vocalist,Lead Dancer,Center,Face of the Group","nameUpper":"NAYEON","zodiacId":6,"counter":2,"birthDate":19950922,"realName":"Im Nayeon","idolId":154,"chineseZodiacId":12,"groupName":"Twice","imageFileName":"NAYEON_TWICE","fandom":"ONCE","name":"Nayeon","age":26}
	,{"country":"South Korea","agency":"BlockBerryCreative","counter2":0,"city":"Uijeongbu","zodiac":"Scorpius","counter1":3,"chineseZodiac":"Snake","groupNameUpper":"LOONA","positions":"Dancer,Rapper,Vocalist","nameUpper":"OLIVIA HYE","zodiacId":8,"counter":3,"birthDate":20011113,"realName":"Son Hyeju","idolId":155,"chineseZodiacId":6,"groupName":"LOONA","imageFileName":"OLIVIAHYE_LOONA","fandom":"Orbit","name":"Olivia Hye","age":20}
	,{"country":"China","agency":"BlockBerryCreative","counter2":0,"city":"Tuen Mun/Hong Kong","zodiac":"Sagittarius","counter1":1,"chineseZodiac":"Rat","groupNameUpper":"LOONA","positions":"Vocalist,Rapper","nameUpper":"VIVI","zodiacId":9,"counter":1,"birthDate":19961209,"realName":"Wong Gaahei","idolId":156,"chineseZodiacId":1,"groupName":"LOONA","imageFileName":"VIVI_LOONA","fandom":"Orbit","name":"Vivi","age":25}
	,{"country":"South Korea","agency":"Starship Entertainment","counter2":0,"city":"Incheon","zodiac":"Gemini","counter1":1,"chineseZodiac":"Tiger","groupNameUpper":"WJSN","positions":"Vocalist,Rapper","nameUpper":"EUNSEO","zodiacId":3,"counter":1,"birthDate":19980527,"realName":"Son Juyeon","idolId":157,"chineseZodiacId":3,"groupName":"WJSN","imageFileName":"EUNSEO_WJSN","fandom":"Ujung","name":"Eunseo","age":24}
	,{"country":"South Korea","agency":"Starship Entertainment","counter2":0,"city":"Seoul","zodiac":"Capricorn","counter1":1,"chineseZodiac":"Dog","groupNameUpper":"WJSN","positions":"Lead Vocalist","nameUpper":"SEOLA","zodiacId":10,"counter":1,"birthDate":19941224,"realName":"Kim Hyunjung","idolId":158,"chineseZodiacId":11,"groupName":"WJSN","imageFileName":"SEOLA_WJSN","fandom":"Ujung","name":"Seola","age":27}
	,{"country":"Japan","agency":"MLD Entertainment","counter2":2,"city":"Kochi","zodiac":"Pisces","counter1":0,"chineseZodiac":"Goat","groupNameUpper":"LAPILLUS","positions":"Leader,Vocalist","nameUpper":"SHANA","zodiacId":12,"counter":2,"birthDate":20030313,"realName":"Nonaka Shana","idolId":159,"chineseZodiacId":8,"groupName":"Lapillus","imageFileName":"SHANA_LAPILLUS","fandom":"---","name":"Shana","age":19}
	,{"country":"South Korea","agency":"Yuehua Entertainment","counter2":0,"city":"Hanam/Gyeonggi-do","zodiac":"Taurus","counter1":1,"chineseZodiac":"Tiger","groupNameUpper":"EVERGLOW","positions":"Main Rapper,Main Dancer","nameUpper":"E:U","zodiacId":2,"counter":1,"birthDate":19980519,"realName":"Park Jiwon","idolId":160,"chineseZodiacId":3,"groupName":"Everglow","imageFileName":"EU_EVERGLOW","fandom":"For Ever","name":"E:U","age":24}
	,{"country":"South Korea","agency":"ALLART Entertainment","counter2":0,"city":"Busan","zodiac":"Pisces","counter1":1,"chineseZodiac":"Goat","groupNameUpper":"PIXY","positions":"Sub Vocalist","nameUpper":"SUA","zodiacId":12,"counter":1,"birthDate":20030224,"realName":"Choi Sua","idolId":161,"chineseZodiacId":8,"groupName":"Pixy","imageFileName":"SUA_PIXY","fandom":"Winxy","name":"Sua","age":19}
	,{"country":"South Korea","agency":"Grandline Group (GLG)","counter2":0,"city":"---","zodiac":"Capricorn","counter1":2,"chineseZodiac":"Monkey","groupNameUpper":"H1-KEY","positions":"Vocalist,Rapper,Maknae","nameUpper":"YEL","zodiacId":10,"counter":2,"birthDate":20041225,"realName":"Han Shinyoung","idolId":162,"chineseZodiacId":9,"groupName":"H1-KEY","imageFileName":"YEL_H1KEY","fandom":"M1-KEY","name":"Yel","age":17}
	,{"country":"South Korea","agency":"BlockBerryCreative","counter2":0,"city":"Chungju","zodiac":"Libra","counter1":3,"chineseZodiac":"Rabbit","groupNameUpper":"LOONA","positions":"Vocalist,Rapper,Face of the Group","nameUpper":"CHUU","zodiacId":7,"counter":3,"birthDate":19991020,"realName":"Kim Jiwoo","idolId":163,"chineseZodiacId":4,"groupName":"LOONA","imageFileName":"CHUU_LOONA","fandom":"Orbit","name":"Chuu","age":22}
	,{"country":"South Korea","agency":"FNC Entertainment","counter2":0,"city":"Seoul","zodiac":"Virgo","counter1":1,"chineseZodiac":"Dragon","groupNameUpper":"CHERRY BULLET","positions":"Lead Vocalist,Rapper,Visual,Center","nameUpper":"JIWON","zodiacId":6,"counter":1,"birthDate":20000904,"realName":"Heo Jiwon","idolId":164,"chineseZodiacId":5,"groupName":"Cherry Bullet","imageFileName":"JIWON_CHERRYBULLET","fandom":"Lullet","name":"Jiwon","age":22}
	,{"country":"South Korea","agency":"WAKEONE and Swing Entertainment","counter2":0,"city":"Yeonje-gu/Busan","zodiac":"Taurus","counter1":1,"chineseZodiac":"Horse","groupNameUpper":"KEP1ER","positions":"Center","nameUpper":"CHAEHYUN","zodiacId":2,"counter":1,"birthDate":20020426,"realName":"Kim Chaehyun","idolId":165,"chineseZodiacId":7,"groupName":"Kep1er","imageFileName":"CHAEHYUN_KEP1ER","fandom":"Kep1ian","name":"Chaehyun","age":20}
	,{"country":"South Korea","agency":"Yuehua Entertainment","counter2":0,"city":"Gil-dong/Gangdong/Seoul","zodiac":"Libra","counter1":1,"chineseZodiac":"Rabbit","groupNameUpper":"SOLOIST","positions":"---","nameUpper":"YENA","zodiacId":7,"counter":1,"birthDate":19990929,"realName":"Choi Yena","idolId":166,"chineseZodiacId":4,"groupName":"soloist","imageFileName":"YENA_SOLOIST","fandom":"JIGUMI","name":"Yena","age":22}
	,{"country":"South Korea","agency":"Grandline Group (GLG)","counter2":0,"city":"Dongjak-gu/Seoul","zodiac":"Pisces","counter1":1,"chineseZodiac":"Snake","groupNameUpper":"H1-KEY","positions":"Vocalist","nameUpper":"RIINA","zodiacId":12,"counter":1,"birthDate":20010221,"realName":"Lee Seunghyun","idolId":167,"chineseZodiacId":6,"groupName":"H1-KEY","imageFileName":"RIINA_H1KEY","fandom":"M1-KEY","name":"Riina","age":21}
	,{"country":"South Korea","agency":"JYP Entertainment","counter2":0,"city":"Yongin","zodiac":"Gemini","counter1":3,"chineseZodiac":"Snake","groupNameUpper":"ITZY","positions":"Main Dancer,Sub Vocalist,Sub Rapper","nameUpper":"CHAERYEONG","zodiacId":3,"counter":3,"birthDate":20010605,"realName":"Lee Chaeryeong","idolId":168,"chineseZodiacId":6,"groupName":"ITZY","imageFileName":"CHAERYEONG_ITZY","fandom":"MIDZY","name":"Chaeryeong","age":21}
	,{"country":"South Korea","agency":"A team Entertainment","counter2":1,"city":"Hwasun/South Jeolla","zodiac":"Leo","counter1":0,"chineseZodiac":"Snake","groupNameUpper":"BUGABOO","positions":"Leader,Main Dancer,Vocalist,Rapper","nameUpper":"CHOYEON","zodiacId":5,"counter":1,"birthDate":20010801,"realName":"Kim Choyeon","idolId":169,"chineseZodiacId":6,"groupName":"bugAboo","imageFileName":"CHOYEON_BUGABOO","fandom":"RAINBOO","name":"Choyeon","age":21}
	,{"country":"South Korea","agency":"Pop Music","counter2":1,"city":"---","zodiac":"Taurus","counter1":1,"chineseZodiac":"Rooster","groupNameUpper":"CSR","positions":"---","nameUpper":"DUNA","zodiacId":2,"counter":2,"birthDate":20050428,"realName":"Kang Duna","idolId":170,"chineseZodiacId":10,"groupName":"CSR","imageFileName":"DUNA_CSR","fandom":"---","name":"Duna","age":17}
	,{"country":"South Korea","agency":"Starship Entertainment","counter2":0,"city":"Seoul","zodiac":"Pisces","counter1":1,"chineseZodiac":"Ox","groupNameUpper":"WJSN","positions":"Vocalist,Rapper","nameUpper":"LUDA","zodiacId":12,"counter":1,"birthDate":19970306,"realName":"Lee Luda","idolId":171,"chineseZodiacId":2,"groupName":"WJSN","imageFileName":"LUDA_WJSN","fandom":"Ujung","name":"Luda","age":25}
	,{"country":"South Korea","agency":"M25","counter2":0,"city":"Beomseo-eup/Ulju-gun/Ulsan","zodiac":"Aquarius","counter1":2,"chineseZodiac":"Rat","groupNameUpper":"CLASS:Y","positions":"Lead Vocalist","nameUpper":"BOEUN","zodiacId":11,"counter":2,"birthDate":20080211,"realName":"Park Boeun","idolId":172,"chineseZodiacId":1,"groupName":"CLASS:y","imageFileName":"BOEUN_CLASSY","fandom":"CLIKE:y","name":"Boeun","age":14}
	,{"country":"South Korea","agency":"Pop Music","counter2":0,"city":"---","zodiac":"Pisces","counter1":2,"chineseZodiac":"Rooster","groupNameUpper":"CSR","positions":"---","nameUpper":"SIHYEON","zodiacId":12,"counter":2,"birthDate":20050312,"realName":"Hwang Sihyeon","idolId":173,"chineseZodiacId":10,"groupName":"CSR","imageFileName":"SIHYEON_CSR","fandom":"---","name":"Sihyeon","age":17}
	,{"country":"South Korea","agency":"KM Entertainment","counter2":0,"city":"Boryeong/Chungcheongnam-do","zodiac":"Leo","counter1":1,"chineseZodiac":"Rooster","groupNameUpper":"ICHILLIN","positions":"Main Dancer,Sub Vocalist,Maknae","nameUpper":"CHOWON","zodiacId":5,"counter":1,"birthDate":20050818,"realName":"Kim Chowon","idolId":174,"chineseZodiacId":10,"groupName":"ichillin","imageFileName":"CHOWON_ICHILLIN","fandom":"Willing","name":"Chowon","age":17}
	,{"country":"South Korea","agency":"MLD Entertainment","counter2":0,"city":"---","zodiac":"Scorpius","counter1":1,"chineseZodiac":"Rat","groupNameUpper":"LAPILLUS","positions":"Dancer,Vocalist,Center,Maknae","nameUpper":"HAEUN","zodiacId":8,"counter":1,"birthDate":20081102,"realName":"Lim Haeun","idolId":175,"chineseZodiacId":1,"groupName":"Lapillus","imageFileName":"HAEUN_LAPILLUS","fandom":"---","name":"Haeun","age":13}
	,{"country":"Japan","agency":"NV Entertainment","counter2":0,"city":"Fukuoka","zodiac":"Virgo","counter1":1,"chineseZodiac":"Goat","groupNameUpper":"WOO!AH!","positions":"Vocalist,Rapper","nameUpper":"SORA","zodiacId":6,"counter":1,"birthDate":20030830,"realName":"Sakata Sora","idolId":176,"chineseZodiacId":8,"groupName":"woo!ah!","imageFileName":"SORA_WOOAH","fandom":"wow!","name":"Sora","age":19}
	,{"country":"South Korea","agency":"KM Entertainment","counter2":0,"city":"Bupyeong-gu/Incheon","zodiac":"Scorpius","counter1":1,"chineseZodiac":"Dragon","groupNameUpper":"ICHILLIN","positions":"Leader,Main Dancer,Sub Vocalist","nameUpper":"E.JI","zodiacId":8,"counter":1,"birthDate":20001108,"realName":"Choi Jiwon","idolId":177,"chineseZodiacId":5,"groupName":"ichillin","imageFileName":"EJI_ICHILLIN","fandom":"Willing","name":"E.JI","age":21}
	,{"country":"South Korea","agency":"Pop Music","counter2":0,"city":"Anyang/Gyeonggi-do","zodiac":"Leo","counter1":1,"chineseZodiac":"Rooster","groupNameUpper":"CSR","positions":"Leader","nameUpper":"SUA","zodiacId":5,"counter":1,"birthDate":20050723,"realName":"Yoo Sua","idolId":178,"chineseZodiacId":10,"groupName":"CSR","imageFileName":"SUA_CSR","fandom":"---","name":"Sua","age":17}
	,{"country":"South Korea","agency":"YG Entertainment","counter2":1,"city":"Cheongdam-dong/Seoul","zodiac":"Capricorn","counter1":0,"chineseZodiac":"Rat","groupNameUpper":"BLACKPINK","positions":"Main Rapper,Lead Vocalist","nameUpper":"JENNIE","zodiacId":10,"counter":1,"birthDate":19960116,"realName":"Kim Jennie","idolId":179,"chineseZodiacId":1,"groupName":"Blackpink","imageFileName":"JENNIE_BLACKPINK","fandom":"BLINK","name":"Jennie","age":26}
	,{"country":"Taiwan","agency":"TR Entertainment","counter2":2,"city":"Kaohsiung","zodiac":"Capricorn","counter1":1,"chineseZodiac":"Horse","groupNameUpper":"TRI.BE","positions":"Lead Vocalist,Visual","nameUpper":"KELLY","zodiacId":10,"counter":3,"birthDate":20020116,"realName":"Lin Weixi","idolId":180,"chineseZodiacId":7,"groupName":"TRI.BE","imageFileName":"KELLY_TRIBE","fandom":"TRUE","name":"Kelly","age":20}
	,{"country":"South Korea","agency":"IST Entertainment","counter2":0,"city":"Bundang-gu/Seongnam/Gyeonggi-do","zodiac":"Pisces","counter1":1,"chineseZodiac":"Horse","groupNameUpper":"WEEEKLY","positions":"Lead Vocalist,Sub Rapper","nameUpper":"JIYOON","zodiacId":12,"counter":1,"birthDate":20020302,"realName":"Shin Jiyoon","idolId":181,"chineseZodiacId":7,"groupName":"Weeekly","imageFileName":"JIYOON_WEEEKLY","fandom":"Daileee","name":"Jiyoon","age":20}
	,{"country":"South Korea","agency":"A team Entertainment","counter2":0,"city":"Incheon","zodiac":"Virgo","counter1":2,"chineseZodiac":"Snake","groupNameUpper":"BUGABOO","positions":"Main Vocalist,Maknae","nameUpper":"ZIN","zodiacId":6,"counter":2,"birthDate":20010830,"realName":"Jin Hyunbin","idolId":182,"chineseZodiacId":6,"groupName":"bugAboo","imageFileName":"ZIN_BUGABOO","fandom":"RAINBOO","name":"Zin","age":21}
	,{"country":"South Korea","agency":"Woollim Entertainment","counter2":0,"city":"Bundang-gu/Seongnam-si","zodiac":"Taurus","counter1":1,"chineseZodiac":"Rooster","groupNameUpper":"ROCKET PUNCH","positions":"Vocalist,Dancer,Maknae","nameUpper":"DAHYUN","zodiacId":2,"counter":1,"birthDate":20050429,"realName":"Jeong Dahyun","idolId":183,"chineseZodiacId":10,"groupName":"Rocket Punch","imageFileName":"DAHYUN_ROCKETPUNCH","fandom":"KETCHY","name":"Dahyun","age":17}
	]);
	