var biases = TAFFY([
	{"country":"South Korea","biasId":1,"city":"Cheongju","artistId":1,"bloodType":"AB","heightStr":"1.66 m.","fandom":"Na.V","weightStr":"47.00 kg.","height":166,"agency":"BPM Entertainment","zodiac":"Gemini","chineseZodiac":"Tiger","weight":47,"groupNameUpper":"VIVIZ","positions":"Main Dancer, Vocalist","nameUpper":"SINB","zodiacId":3,"birthDate":19980603,"realName":"Hwang Eunbi","groupName":"VIVIZ","chineseZodiacId":3,"person":1,"imageFileName":"SINB_VIVIZ","name":"SinB","age":24}
	,{"country":"South Korea","biasId":3,"city":"Daejeon","artistId":3,"bloodType":"B","heightStr":"1.67 m.","fandom":"InSomnia","weightStr":"49.00 kg.","height":167,"agency":"Dreamcatcher Company","zodiac":"Taurus","chineseZodiac":"Dog","weight":49,"groupNameUpper":"DREAMCATCHER","positions":"Leader, Lead Vocalist, Lead Dancer, Visual","nameUpper":"JIU","zodiacId":2,"birthDate":19940517,"realName":"Kim Minji","groupName":"Dreamcatcher","chineseZodiacId":11,"person":2,"imageFileName":"JIU_DREAMCATCHER","name":"Jiu","age":28}
	,{"country":"South Korea","biasId":4,"city":"Seoul","artistId":4,"bloodType":"A","heightStr":"1.58 m.","fandom":"Kep1ian","weightStr":"41.00 kg.","height":158,"agency":"WAKEONE and Swing Entertainment","zodiac":"Pisces","chineseZodiac":"Goat","weight":41,"groupNameUpper":"KEP1ER","positions":"---","nameUpper":"DAYEON","zodiacId":12,"birthDate":20030302,"realName":"Kim Dayeon","groupName":"Kep1er","chineseZodiacId":8,"person":2,"imageFileName":"DAYEON_KEP1ER","name":"Dayeon","age":19}
	,{"country":"South Korea","biasId":5,"city":"Bundang-gu","artistId":5,"bloodType":"A","heightStr":"1.61 m.","fandom":"Orbit","weightStr":"43.00 kg.","height":161,"agency":"BlockBerryCreative","zodiac":"Libra","chineseZodiac":"Dragon","weight":43,"groupNameUpper":"LOONA","positions":"Dancer, Vocalist, Rapper, Visual, Center","nameUpper":"HEEJIN","zodiacId":7,"birthDate":20001019,"realName":"Jeon Heejin","groupName":"LOONA","chineseZodiacId":5,"person":1,"imageFileName":"HEEJIN_LOONA","name":"Heejin","age":21}
	,{"country":"South Korea","agency":"RBW","biasId":6,"city":"Busan","zodiac":"Sagittarius","chineseZodiac":"Horse","groupNameUpper":"PURPLE KISS","positions":"Main Vocalist, Lead Dancer, Rapper","artistId":6,"nameUpper":"CHAEIN","zodiacId":9,"bloodType":"---","birthDate":20021205,"heightStr":"1.60 m.","realName":"Lee Chaeyoung","groupName":"Purple Kiss","chineseZodiacId":7,"person":2,"imageFileName":"CHAEIN_PURPLEKISS","fandom":"PLORY","name":"Chaein","age":19,"height":160}
	,{"country":"South Korea","biasId":7,"city":"Seoul","artistId":7,"bloodType":"B","heightStr":"1.66 m.","fandom":"Page","weightStr":"46.00 kg.","height":166,"agency":"iMe Entertainment","zodiac":"Virgo","chineseZodiac":"Snake","weight":46,"groupNameUpper":"DREAM NOTE","positions":"Main Rapper, Main Dancer, Vocalist, Center, Face of the Group","nameUpper":"SUMIN","zodiacId":6,"birthDate":20010907,"realName":"Park Sumin","groupName":"Dream Note","chineseZodiacId":6,"person":2,"imageFileName":"SUMIN_DREAMNOTE","name":"Sumin","age":21}
	,{"country":"South Korea","biasId":8,"city":"Daejeon/Chungcheong","artistId":8,"bloodType":"O","heightStr":"1.70 m.","fandom":"SWITH","weightStr":"50.00 kg.","height":170,"agency":"High Up Entertainment","zodiac":"Sagittarius","chineseZodiac":"Monkey","weight":50,"groupNameUpper":"STAYC","positions":"Vocalist, Rapper, Maknae","nameUpper":"J","zodiacId":9,"birthDate":20041209,"realName":"Jang Yeeun","groupName":"Stayc","chineseZodiacId":9,"person":1,"imageFileName":"J_STAYC","name":"J","age":17}
	,{"country":"South Korea","biasId":9,"city":"Uijeongbu/Gyeonggi-do","artistId":9,"bloodType":"A","heightStr":"1.58 m.","fandom":"Kep1ian","weightStr":"42.00 kg.","height":158,"agency":"WAKEONE and Swing Entertainment","zodiac":"Capricorn","chineseZodiac":"Monkey","weight":42,"groupNameUpper":"KEP1ER","positions":"---","nameUpper":"YOUNGEUN","zodiacId":10,"birthDate":20041227,"realName":"Seo Youngeun","groupName":"Kep1er","chineseZodiacId":9,"person":1,"imageFileName":"YOUNGEUN_KEP1ER","name":"Youngeun","age":17}
	,{"country":"South Korea","biasId":11,"city":"Gwonseon-gu/Suwon/Gyeonggi-do","artistId":11,"bloodType":"B","heightStr":"1.77 m.","fandom":"For Ever","weightStr":"55.00 kg.","height":177,"agency":"Yuehua Entertainment","zodiac":"Cancer","chineseZodiac":"Dragon","weight":55,"groupNameUpper":"EVERGLOW","positions":"Lead Rapper, Sub Vocalist","nameUpper":"AISHA","zodiacId":4,"birthDate":20000721,"realName":"Heo Yoorim","groupName":"Everglow","chineseZodiacId":5,"person":1,"imageFileName":"AISHA_EVERGLOW","name":"Aisha","age":22}
	,{"country":"South Korea","biasId":13,"city":"Seoul","artistId":13,"bloodType":"A","heightStr":"1.60 m.","fandom":"SWITH","weightStr":"43.00 kg.","height":160,"agency":"High Up Entertainment","zodiac":"Leo","chineseZodiac":"Snake","weight":43,"groupNameUpper":"STAYC","positions":"Main Vocalist","nameUpper":"SIEUN","zodiacId":5,"birthDate":20010801,"realName":"Park Sieun","groupName":"Stayc","chineseZodiacId":6,"person":2,"imageFileName":"SIEUN_STAYC","name":"Sieun","age":21}
	,{"country":"South Korea","biasId":14,"city":"Incheon","artistId":14,"bloodType":"AB","heightStr":"1.60 m.","fandom":"Page","weightStr":"43.00 kg.","height":160,"agency":"iMe Entertainment","zodiac":"Scorpius","chineseZodiac":"Dragon","weight":43,"groupNameUpper":"DREAM NOTE","positions":"Main Vocalist, Rapper","nameUpper":"MISO","zodiacId":8,"birthDate":20001025,"realName":"Jeon Jimin","groupName":"Dream Note","chineseZodiacId":5,"person":1,"imageFileName":"MISO_DREAMNOTE","name":"Miso","age":21}
	,{"country":"South Korea","biasId":15,"city":"Busan/South Gyeongnam","artistId":15,"bloodType":"O","heightStr":"1.67 m.","fandom":"Miracle","weightStr":"50.00 kg.","height":167,"agency":"WM Entertainment","zodiac":"Gemini","chineseZodiac":"Rabbit","weight":50,"groupNameUpper":"OH MY GIRL","positions":"Lead Dancer, Sub Vocalist, Maknae","nameUpper":"ARIN","zodiacId":3,"birthDate":19990618,"realName":"Choi Yewon","groupName":"Oh My Girl","chineseZodiacId":4,"person":2,"imageFileName":"ARIN_OHMYGIRL","name":"Arin","age":23}
	,{"country":"South Korea","biasId":16,"city":"Busan","artistId":16,"bloodType":"O","heightStr":"1.66 m.","fandom":"signfan","weightStr":"46.00 kg.","height":166,"agency":"J9 Entertainment","zodiac":"Aries","chineseZodiac":"Rabbit","weight":46,"groupNameUpper":"CIGNATURE","positions":"Vocalist, Center, Face of the Group","nameUpper":"JEEWON","zodiacId":1,"birthDate":19990401,"realName":"Kim jiwon","groupName":"cignature","chineseZodiacId":4,"person":2,"imageFileName":"JEEWON_CIGNATURE","name":"Jeewon","age":23}
	,{"country":"South Korea","biasId":17,"city":"North Jeolla","artistId":17,"bloodType":"B","heightStr":"1.64 m.","fandom":"TRUE","weightStr":"46.00 kg.","height":164,"agency":"TR Entertainment","zodiac":"Gemini","chineseZodiac":"Monkey","weight":46,"groupNameUpper":"TRI.BE","positions":"Main Rapper, Main Dancer, Lead Vocalist","nameUpper":"HYUNBIN","zodiacId":3,"birthDate":20040526,"realName":"Kim Hyunbin","groupName":"TRI.BE","chineseZodiacId":9,"person":1,"imageFileName":"HYUNBIN_TRIBE","name":"Hyunbin","age":18}
	,{"country":"South Korea","biasId":18,"city":"Gwangju/Jeolla-do","artistId":18,"bloodType":"B","heightStr":"1.72 m.","fandom":"Daileee","weightStr":"53.00 kg.","height":172,"agency":"IST Entertainment","zodiac":"Scorpius","chineseZodiac":"Horse","weight":53,"groupNameUpper":"WEEEKLY","positions":"Main Dancer, Lead Vocalist, Center","nameUpper":"SOEUN","zodiacId":8,"birthDate":20021026,"realName":"Park Soeun","groupName":"Weeekly","chineseZodiacId":7,"person":1,"imageFileName":"SOEUN_WEEEKLY","name":"Soeun","age":19}
	,{"country":"South Korea","biasId":20,"city":"Anyang/Gyeonggi-do","artistId":20,"bloodType":"A","heightStr":"1.63 m.","fandom":"Daileee","weightStr":"47.00 kg.","height":163,"agency":"IST Entertainment","zodiac":"Cancer","chineseZodiac":"Monkey","weight":47,"groupNameUpper":"WEEEKLY","positions":"Lead Vocalist, Visual, Center","nameUpper":"JIHAN","zodiacId":4,"birthDate":20040712,"realName":"Han Jihyo","groupName":"Weeekly","chineseZodiacId":9,"person":2,"imageFileName":"JIHAN_WEEEKLY","name":"Jihan","age":18}
	,{"country":"South Korea","biasId":21,"city":"Seoul","artistId":21,"bloodType":"O","heightStr":"1.73 m.","fandom":"DIVE","weightStr":"49.00 kg.","height":173,"agency":"Starship Entertainment","zodiac":"Virgo","chineseZodiac":"Monkey","weight":49,"groupNameUpper":"IVE","positions":"Vocalist, Visual","nameUpper":"WONYOUNG","zodiacId":6,"birthDate":20040831,"realName":"Jang Wongyoung","groupName":"IVE","chineseZodiacId":9,"person":2,"imageFileName":"WONYOUNG_IVE","name":"Wonyoung","age":18}
	,{"country":"Japan","biasId":22,"city":"Tokyo","artistId":22,"bloodType":"AB","heightStr":"1.66 m.","fandom":"TRUE","weightStr":"49.00 kg.","height":166,"agency":"TR Entertainment","zodiac":"Aries","chineseZodiac":"Dog","weight":49,"groupNameUpper":"TRI.BE","positions":"Main Dancer, Sub Vocalist, Maknae","nameUpper":"MIRE","zodiacId":1,"birthDate":20060326,"realName":"Aoyagi Sumire","groupName":"TRI.BE","chineseZodiacId":11,"person":2,"imageFileName":"MIRE_TRIBE","name":"Mire","age":16}
	,{"country":"China","biasId":23,"city":"Harbin/Heilongjiang","artistId":23,"bloodType":"O","heightStr":"1.62 m.","fandom":"MY","weightStr":"44.00 kg.","height":162,"agency":"SM Entertainment","zodiac":"Scorpius","chineseZodiac":"Horse","weight":44,"groupNameUpper":"AESPA","positions":"Main Vocalist, Maknae","nameUpper":"NING NING","zodiacId":8,"birthDate":20021023,"realName":"Ning Yizhuo","groupName":"aespa","chineseZodiacId":7,"person":1,"imageFileName":"NINGNING_AESPA","name":"Ning Ning","age":19}
	,{"country":"South Korea","biasId":24,"city":"Busan","artistId":24,"bloodType":"O","heightStr":"1.66 m.","fandom":"SWITH","weightStr":"46.00 kg.","height":166,"agency":"High Up Entertainment","zodiac":"Aquarius","chineseZodiac":"Horse","weight":46,"groupNameUpper":"STAYC","positions":"Lead Vocalist","nameUpper":"ISA","zodiacId":11,"birthDate":20020123,"realName":"Lee Chaeyoung","groupName":"Stayc","chineseZodiacId":7,"person":2,"imageFileName":"ISA_STAYC","name":"ISA","age":20}
	,{"country":"South Korea","biasId":25,"city":"Anyang/Gyeonggi-do","artistId":25,"bloodType":"AB","heightStr":"1.58 m.","fandom":"Miracle","weightStr":"42.00 kg.","height":158,"agency":"WM Entertainment","zodiac":"Leo","chineseZodiac":"Dog","weight":42,"groupNameUpper":"OH MY GIRL","positions":"Leader, Main Vocalist","nameUpper":"HYOJUNG","zodiacId":5,"birthDate":19940728,"realName":"Choi Hyojung","groupName":"Oh My Girl","chineseZodiacId":11,"person":1,"imageFileName":"HYOJUNG_OHMYGIRL","name":"Hyojung","age":28}
	,{"country":"South Korea","biasId":26,"city":"Seogwipo/Jeju-do","artistId":26,"bloodType":"B","heightStr":"1.71 m.","fandom":"DIVE","weightStr":"49.00 kg.","height":171,"agency":"Starship Entertainment","zodiac":"Scorpius","chineseZodiac":"Monkey","weight":49,"groupNameUpper":"IVE","positions":"Main Vocalist","nameUpper":"LIZ","zodiacId":8,"birthDate":20041121,"realName":"Kim Jiwon","groupName":"IVE","chineseZodiacId":9,"person":2,"imageFileName":"LIZ_IVE","name":"Liz","age":17}
	,{"country":"South Korea","agency":"NV Entertainment","biasId":27,"city":"Osan/Gyeonggi-do","zodiac":"Leo","chineseZodiac":"Monkey","groupNameUpper":"WOO!AH!","positions":"Main Vocalist, Lead Dancer, Maknae","artistId":27,"nameUpper":"MINSEO","zodiacId":5,"bloodType":"B","birthDate":20040812,"heightStr":"1.62 m.","realName":"Kim Minseo","groupName":"woo!ah!","chineseZodiacId":9,"person":2,"imageFileName":"MINSEO_WOOAH","fandom":"wow!","name":"Minseo","age":18,"height":162}
	,{"country":"South Korea","biasId":28,"city":"Jeonju/North Jeolla","artistId":28,"bloodType":"AB","heightStr":"1.64 m.","fandom":"Orbit","weightStr":"45.00 kg.","height":164,"agency":"BlockBerryCreative","zodiac":"Scorpius","chineseZodiac":"Dragon","weight":45,"groupNameUpper":"LOONA","positions":"Dancer, Vocalist, Rapper, Visual","nameUpper":"HYUNJIN","zodiacId":8,"birthDate":20001115,"realName":"Kim Hyunjin","groupName":"LOONA","chineseZodiacId":5,"person":2,"imageFileName":"HYUNJIN_LOONA","name":"Hyunjin","age":21}
	,{"country":"South Korea","biasId":29,"city":"Gwanju/Jeolla-do","artistId":29,"bloodType":"A","heightStr":"1.72 m.","fandom":"SWITH","weightStr":"51.00 kg.","height":172,"agency":"High Up Entertainment","zodiac":"Aries","chineseZodiac":"Monkey","weight":51,"groupNameUpper":"STAYC","positions":"Lead Vocalist","nameUpper":"YOON","zodiacId":1,"birthDate":20040414,"realName":"Shim Jayun","groupName":"Stayc","chineseZodiacId":9,"person":1,"imageFileName":"YOON_STAYC","name":"Yoon","age":18}
	,{"country":"China","biasId":30,"city":"Hangzhou/Zhejiang","artistId":30,"bloodType":"AB","heightStr":"1.63 m.","fandom":"For Ever","weightStr":"42.00 kg.","height":163,"agency":"Yuehua Entertainment","zodiac":"Capricorn","chineseZodiac":"Dragon","weight":42,"groupNameUpper":"EVERGLOW","positions":"Lead Dancer, Sub Vocalist, Sub Rapper, Visual, Center, Face of the Group, Maknae","nameUpper":"YIREN","zodiacId":10,"birthDate":20001229,"realName":"Wang Yiren","groupName":"Everglow","chineseZodiacId":5,"person":2,"imageFileName":"YIREN_EVERGLOW","name":"Yiren","age":21}
	,{"country":"South Korea","biasId":32,"city":"Incheon","artistId":32,"bloodType":"O","heightStr":"1.65 m.","fandom":"Na.V","weightStr":"48.00 kg.","height":165,"agency":"BPM Entertainment","zodiac":"Leo","chineseZodiac":"Tiger","weight":48,"groupNameUpper":"VIVIZ","positions":"Lead Dancer, Vocalist, Maknae","nameUpper":"UMJI","zodiacId":5,"birthDate":19980819,"realName":"Kim Yewon","groupName":"VIVIZ","chineseZodiacId":3,"person":2,"imageFileName":"UMJI_VIVIZ","name":"Umji","age":24}
	,{"country":"South Korea","biasId":33,"city":"Bundang-gu/Seongnam/Gyeonggi-do","artistId":33,"bloodType":"B","heightStr":"1.70 m.","fandom":"For Ever","weightStr":"51.00 kg.","height":170,"agency":"Yuehua Entertainment","zodiac":"Leo","chineseZodiac":"Rabbit","weight":51,"groupNameUpper":"EVERGLOW","positions":"Leader, Lead Vocalist, Visual, Face of the Group","nameUpper":"SIHYEON","zodiacId":5,"birthDate":19990805,"realName":"Kim Sihyeon","groupName":"Everglow","chineseZodiacId":4,"person":1,"imageFileName":"SIHYEON_EVERGLOW","name":"Sihyeon","age":23}
	,{"country":"South Korea","biasId":34,"city":"Bucheon","artistId":34,"bloodType":"O","heightStr":"1.61 m.","fandom":"Orbit","weightStr":"48.00 kg.","height":161,"agency":"BlockBerryCreative","zodiac":"Gemini","chineseZodiac":"Snake","weight":48,"groupNameUpper":"LOONA","positions":"Rapper, Dancer, Vocalist","nameUpper":"CHOERRY","zodiacId":3,"birthDate":20010604,"realName":"Choi Yerin","groupName":"LOONA","chineseZodiacId":6,"person":1,"imageFileName":"CHOERRY_LOONA","name":"Choerry","age":21}
	,{"country":"South Korea","biasId":36,"city":"Yeonsu-gu/Incheon","artistId":36,"bloodType":"AB","heightStr":"1.62 m.","fandom":"Belllie've","weightStr":"41.00 kg.","height":162,"agency":"MYSTIC Story","zodiac":"Aquarius","chineseZodiac":"Goat","weight":41,"groupNameUpper":"BILLLIE","positions":"Main Dancer, Lead Rapper","nameUpper":"SHEON","zodiacId":11,"birthDate":20030128,"realName":"Kim Suyeon","groupName":"Billlie","chineseZodiacId":8,"person":1,"imageFileName":"SHEON_BILLLIE","name":"Sheon","age":19}
	,{"country":"South Korea","biasId":37,"city":"Seoul","artistId":37,"bloodType":"O","heightStr":"1.48 m.","fandom":"Orbit","weightStr":"35.00 kg.","height":148,"agency":"BlockBerryCreative","zodiac":"Scorpius","chineseZodiac":"Horse","weight":35,"groupNameUpper":"LOONA","positions":"Vocalist, Rapper, Maknae","nameUpper":"YEOJIN","zodiacId":8,"birthDate":20021111,"realName":"Im Yeojin","groupName":"LOONA","chineseZodiacId":7,"person":1,"imageFileName":"YEOJIN_LOONA","name":"Yeojin","age":19}
	,{"country":"South Korea","biasId":39,"city":"Chuncheon","artistId":39,"bloodType":"B","heightStr":"1.65 m.","fandom":"Orbit","weightStr":"47.00 kg.","height":165,"agency":"BlockBerryCreative","zodiac":"Gemini","chineseZodiac":"Ox","weight":47,"groupNameUpper":"LOONA","positions":"Rapper, Vocalist, Visual","nameUpper":"JINSOUL","zodiacId":3,"birthDate":19970613,"realName":"Jeong Jinsol","groupName":"LOONA","chineseZodiacId":2,"person":2,"imageFileName":"JINSOUL_LOONA","name":"Jinsoul","age":25}
	,{"country":"South Korea","biasId":40,"city":"Pohang","artistId":40,"bloodType":"B","heightStr":"1.69 m.","fandom":"Flover","weightStr":"48.00 kg.","height":169,"agency":"Pledis Entertainment","zodiac":"Taurus","chineseZodiac":"Dragon","weight":48,"groupNameUpper":"FROMIS_9","positions":"Main Dancer, Lead Rapper, Vocalist","nameUpper":"CHAEYOUNG","zodiacId":2,"birthDate":20000514,"realName":"Lee Chaeyoung","groupName":"fromis_9","chineseZodiacId":5,"person":1,"imageFileName":"CHAEYOUNG_FROMIS9","name":"Chaeyoung","age":22}
	,{"country":"South Korea","biasId":43,"city":"Songpa-gu/Seoul","artistId":43,"bloodType":"A","heightStr":"1.65 m.","fandom":"Daileee","weightStr":"47.00 kg.","height":165,"agency":"IST Entertainment","zodiac":"Sagittarius","chineseZodiac":"Snake","weight":47,"groupNameUpper":"WEEEKLY","positions":"Leader, Main Dancer, Sub Vocalist, Sub Rapper, Visual, Center","nameUpper":"SOOJIN","zodiacId":9,"birthDate":20011212,"realName":"Lee Soojin","groupName":"Weeekly","chineseZodiacId":6,"person":1,"imageFileName":"SOOJIN_WEEEKLY","name":"Soojin","age":20}
	,{"country":"South Korea","biasId":45,"city":"Jeonju/Jeollabuk-do","artistId":45,"bloodType":"A","heightStr":"1.63 m.","fandom":"Belllie've","weightStr":"45.00 kg.","height":163,"agency":"MYSTIC Story","zodiac":"Capricorn","chineseZodiac":"Snake","weight":45,"groupNameUpper":"BILLLIE","positions":"Main Vocalist","nameUpper":"HARAM","zodiacId":10,"birthDate":20010113,"realName":"Kim Haram","groupName":"Billlie","chineseZodiacId":6,"person":1,"imageFileName":"HARAM_BILLLIE","name":"Haram","age":21}
	,{"country":"South Korea","biasId":47,"city":"Paldal-gu/Gyeonggi-do","artistId":47,"bloodType":"B","heightStr":"1.68 m.","fandom":"MY","weightStr":"45.00 kg.","height":168,"agency":"SM Entertainment","zodiac":"Aries","chineseZodiac":"Dragon","weight":45,"groupNameUpper":"AESPA","positions":"Leader, Main Dancer, Lead Rapper, Sub Vocalist, Visual, Face of the Group, Center","nameUpper":"KARINA","zodiacId":1,"birthDate":20000411,"realName":"Yoo Jimin","groupName":"aespa","chineseZodiacId":5,"person":2,"imageFileName":"KARINA_AESPA","name":"Karina","age":22}
	,{"country":"South Korea","biasId":48,"city":"Gwangju","artistId":48,"bloodType":"A","heightStr":"1.58 m.","fandom":"Lullet","weightStr":"42.00 kg.","height":158,"agency":"FNC Entertainment","zodiac":"Pisces","chineseZodiac":"Rabbit","weight":42,"groupNameUpper":"CHERRY BULLET","positions":"Main Vocalist","nameUpper":"BORA","zodiacId":12,"birthDate":19990303,"realName":"Kim Bora","groupName":"Cherry Bullet","chineseZodiacId":4,"person":1,"imageFileName":"BORA_CHERRYBULLET","name":"Bora","age":23}
	,{"country":"South Korea","biasId":49,"city":"Incheon","artistId":49,"bloodType":"B","heightStr":"1.61 m.","fandom":"Neverland","weightStr":"45.00 kg.","height":161,"agency":"Cube Entertainment","zodiac":"Aquarius","chineseZodiac":"Ox","weight":45,"groupNameUpper":"(G)I-DLE","positions":"Main Vocalist, Visual","nameUpper":"MIYEON","zodiacId":11,"birthDate":19970131,"realName":"Jo Miyeon","groupName":"(g)i-dle","chineseZodiacId":2,"person":1,"imageFileName":"MIYEON_GIDLE","name":"Miyeon","age":25}
	,{"country":"South Korea","biasId":50,"city":"---","artistId":50,"bloodType":"AB","heightStr":"1.58 m.","fandom":"Winxy","weightStr":"41.00 kg.","height":158,"agency":"ALLART Entertainment","zodiac":"Leo","chineseZodiac":"Goat","weight":41,"groupNameUpper":"PIXY","positions":"Sub Vocalist, Maknae","nameUpper":"DAJEONG","zodiacId":5,"birthDate":20030731,"realName":"Jung Dajeong","groupName":"Pixy","chineseZodiacId":8,"person":2,"imageFileName":"DAJEONG_PIXY","name":"Dajeong","age":19}
	,{"country":"South Korea","biasId":51,"city":"Incheon","artistId":51,"bloodType":"B","heightStr":"1.68 m.","fandom":"SUMIT","weightStr":"48.00 kg.","height":168,"agency":"Cube Entertainment","zodiac":"Virgo","chineseZodiac":"Horse","weight":48,"groupNameUpper":"LIGHTSUM","positions":"Lead Dancer, Rapper","nameUpper":"SANGAH","zodiacId":6,"birthDate":20020904,"realName":"Yoon Sangah","groupName":"Lightsum","chineseZodiacId":7,"person":2,"imageFileName":"SANGAH_LIGHTSUM","name":"Sangah","age":20}
	,{"country":"USA","biasId":54,"city":"Los Angeles/California","artistId":54,"bloodType":"B","heightStr":"1.65 m.","fandom":"LOCKEY","weightStr":"46.00 kg.","height":165,"agency":"Vine Entertainment","zodiac":"Aquarius","chineseZodiac":"Tiger","weight":46,"groupNameUpper":"SECRET NUMBER","positions":"Main Rapper, Sub Vocalist","nameUpper":"JINNY","zodiacId":11,"birthDate":19980120,"realName":"Jinny Park","groupName":"Secret Number","chineseZodiacId":3,"person":1,"imageFileName":"JINNY_SECRETNUMBER","name":"Jinny","age":24}
	,{"country":"South Korea","biasId":58,"city":"Yeosu","artistId":58,"bloodType":"A","heightStr":"1.70 m.","fandom":"signfan","weightStr":"48.00 kg.","height":170,"agency":"J9 Entertainment","zodiac":"Cancer","chineseZodiac":"Tiger","weight":48,"groupNameUpper":"CIGNATURE","positions":"Vocalist, Visual","nameUpper":"CHAESOL","zodiacId":4,"birthDate":19980714,"realName":"Moon Chaesol","groupName":"cignature","chineseZodiacId":3,"person":1,"imageFileName":"CHAESOL_CIGNATURE","name":"Chaesol","age":24}
	,{"country":"South Korea","biasId":59,"city":"Siheung/Gyeonggi-do","artistId":59,"bloodType":"O","heightStr":"1.66 m.","fandom":"TRUE","weightStr":"50.00 kg.","height":166,"agency":"TR Entertainment","zodiac":"Scorpius","chineseZodiac":"Goat","weight":50,"groupNameUpper":"TRI.BE","positions":"Lead Vocalist, Lead Dancer","nameUpper":"JINHA","zodiacId":8,"birthDate":20031121,"realName":"Kim Jinha","groupName":"TRI.BE","chineseZodiacId":8,"person":2,"imageFileName":"JINHA_TRIBE","name":"Jinha","age":18}
	,{"country":"South Korea","biasId":60,"city":"Jeonju","artistId":60,"bloodType":"A","heightStr":"1.67 m.","fandom":"MIDZY","weightStr":"46.00 kg.","height":167,"agency":"JYP Entertainment","zodiac":"Gemini","chineseZodiac":"Dragon","weight":46,"groupNameUpper":"ITZY","positions":"Leader, Main Dancer, Lead Vocalist, Sub Rapper","nameUpper":"YEJI","zodiacId":3,"birthDate":20000526,"realName":"Hwang Yeji","groupName":"ITZY","chineseZodiacId":5,"person":1,"imageFileName":"YEJI_ITZY","name":"Yeji","age":22}
	,{"country":"South Korea","biasId":61,"city":"Pohang/North Gyeongsang","artistId":61,"bloodType":"O","heightStr":"1.59 m.","fandom":"SWITH","weightStr":"44.00 kg.","height":159,"agency":"High Up Entertainment","zodiac":"Pisces","chineseZodiac":"Snake","weight":44,"groupNameUpper":"STAYC","positions":"Leader, Vocalist, Rapper","nameUpper":"SUMIN","zodiacId":12,"birthDate":20010313,"realName":"Bae Sumin","groupName":"Stayc","chineseZodiacId":6,"person":2,"imageFileName":"SUMIN_STAYC","name":"Sumin","age":21}
	,{"country":"China","biasId":64,"city":"Wuhan","artistId":64,"bloodType":"A","heightStr":"1.65 m.","fandom":"InSomnia","weightStr":"46.00 kg.","height":165,"agency":"Dreamcatcher Company","zodiac":"Aries","chineseZodiac":"Rat","weight":46,"groupNameUpper":"DREAMCATCHER","positions":"Sub Vocalist","nameUpper":"HANDONG","zodiacId":1,"birthDate":19960326,"realName":"Han Dong","groupName":"Dreamcatcher","chineseZodiacId":1,"person":1,"imageFileName":"HANDONG_DREAMCATCHER","name":"Handong","age":26}
	,{"country":"Japan","biasId":67,"city":"Nagoya/Aichi","artistId":67,"bloodType":"AB","heightStr":"1.70 m.","fandom":"DIVE","weightStr":"47.00 kg.","height":170,"agency":"Starship Entertainment","zodiac":"Aquarius","chineseZodiac":"Monkey","weight":47,"groupNameUpper":"IVE","positions":"Rapper, Vocalist","nameUpper":"REI","zodiacId":11,"birthDate":20040203,"realName":"Naoi Rei","groupName":"IVE","chineseZodiacId":9,"person":1,"imageFileName":"REI_IVE","name":"Rei","age":18}
	,{"country":"South Korea","biasId":70,"city":"Gwangju","artistId":70,"bloodType":"O","heightStr":"1.58 m.","fandom":"KETCHY","weightStr":"46.00 kg.","height":158,"agency":"Woollim Entertainment","zodiac":"Scorpius","chineseZodiac":"Snake","weight":46,"groupNameUpper":"ROCKET PUNCH","positions":"Vocalist, Rapper, Dancer","nameUpper":"YUNKYOUNG","zodiacId":8,"birthDate":20011101,"realName":"Seo Yunkyoung","groupName":"Rocket Punch","chineseZodiacId":6,"person":1,"imageFileName":"YUNKYOUNG_ROCKETPUNCH","name":"Yunkyoung","age":20}
	,{"country":"South Korea","agency":"JYP Entertainment","biasId":72,"city":"Daejeon","zodiac":"Aquarius","chineseZodiac":"Monkey","groupNameUpper":"NMIXX","positions":"Vocalist, Dancer","artistId":72,"nameUpper":"SULLYOON","zodiacId":11,"bloodType":"A","birthDate":20040126,"heightStr":"1.68 m.","realName":"Seol Yoona","groupName":"NMIXX","chineseZodiacId":9,"person":1,"imageFileName":"SULLYOON_NMIXX","fandom":"NSWER","name":"Sullyoon","age":18,"height":168}
	,{"country":"South Korea","biasId":73,"city":"Goyang","artistId":73,"bloodType":"A","heightStr":"1.70 m.","fandom":"KETCHY","weightStr":"52.00 kg.","height":170,"agency":"Woollim Entertainment","zodiac":"Pisces","chineseZodiac":"Snake","weight":52,"groupNameUpper":"ROCKET PUNCH","positions":"Vocalist, Dancer","nameUpper":"SUYUN","zodiacId":12,"birthDate":20010317,"realName":"Kim Suyun","groupName":"Rocket Punch","chineseZodiacId":6,"person":1,"imageFileName":"SUYUN_ROCKETPUNCH","name":"Suyun","age":21}
	,{"country":"South Korea","biasId":74,"city":"Cheongju/Chungcheongbuk-do","artistId":74,"bloodType":"B","heightStr":"1.64 m.","fandom":"Belllie've","weightStr":"45.00 kg.","height":164,"agency":"MYSTIC Story","zodiac":"Virgo","chineseZodiac":"Rabbit","weight":45,"groupNameUpper":"BILLLIE","positions":"Main Rapper, Lead Vocalist","nameUpper":"MOON SUA","zodiacId":6,"birthDate":19990909,"realName":"Moon Sua","groupName":"Billlie","chineseZodiacId":4,"person":2,"imageFileName":"MOONSUA_BILLLIE","name":"Moon Sua","age":23}
	,{"country":"South Korea","biasId":75,"city":"Buk-gu/Gwangju","artistId":75,"bloodType":"B","heightStr":"1.61 m.","fandom":"KETCHY","weightStr":"44.00 kg.","height":161,"agency":"Woollim Entertainment","zodiac":"Sagittarius","chineseZodiac":"Dragon","weight":44,"groupNameUpper":"ROCKET PUNCH","positions":"Leader, Vocalist, Dancer, Rapper","nameUpper":"YEONHEE","zodiacId":9,"birthDate":20001206,"realName":"Kim Yeonhee","groupName":"Rocket Punch","chineseZodiacId":5,"person":2,"imageFileName":"YEONHEE_ROCKETPUNCH","name":"Yeonhee","age":21}
	,{"country":"South Korea","biasId":76,"city":"Incheon","artistId":76,"bloodType":"O","heightStr":"1.68 m.","fandom":"InSomnia","weightStr":"49.00 kg.","height":168,"agency":"Dreamcatcher Company","zodiac":"Capricorn","chineseZodiac":"Ox","weight":49,"groupNameUpper":"DREAMCATCHER","positions":"Lead Vocalist","nameUpper":"YOOHYEON","zodiacId":10,"birthDate":19970107,"realName":"Kim Yoohyeon","groupName":"Dreamcatcher","chineseZodiacId":2,"person":1,"imageFileName":"YOOHYEON_DREAMCATCHER","name":"Yoohyeon","age":25}
	,{"country":"South Korea","biasId":78,"city":"Seoul","artistId":78,"bloodType":"AB","heightStr":"1.64 m.","fandom":"WIZ*ONE","weightStr":"45.00 kg.","height":164,"agency":"Urban Works Entertainment","zodiac":"Aquarius","chineseZodiac":"Snake","weight":45,"groupNameUpper":"SOLOIST","positions":"---","nameUpper":"MINJU","zodiacId":11,"birthDate":20010205,"realName":"Kim Minju","groupName":"soloist","chineseZodiacId":6,"person":1,"imageFileName":"MINJU_SOLOIST","name":"Minju","age":21}
	,{"country":"South Korea","biasId":79,"city":"Chuncheon","artistId":79,"bloodType":"B","heightStr":"1.63 m.","fandom":"Flover","weightStr":"41.00 kg.","height":163,"agency":"Pledis Entertainment","zodiac":"Capricorn","chineseZodiac":"Ox","weight":41,"groupNameUpper":"FROMIS_9","positions":"Leader, Lead Dancer, Vocalist, Rapper, Visual","nameUpper":"SAEROM","zodiacId":10,"birthDate":19970107,"realName":"Lee Saerom","groupName":"fromis_9","chineseZodiacId":2,"person":2,"imageFileName":"SAEROM_FROMIS9","name":"Saerom","age":25}
	,{"country":"China","biasId":81,"city":"Beijing","artistId":81,"bloodType":"O","heightStr":"1.63 m.","fandom":"Neverland","weightStr":"47.00 kg.","height":163,"agency":"Cube Entertainment","zodiac":"Libra","chineseZodiac":"Rabbit","weight":47,"groupNameUpper":"(G)I-DLE","positions":"Lead Dancer, Sub Vocalist, Sub Rapper, Face of the group","nameUpper":"YUQI","zodiacId":7,"birthDate":19990923,"realName":"Song Yuqi","groupName":"(g)i-dle","chineseZodiacId":4,"person":2,"imageFileName":"YUQI_GIDLE","name":"Yuqi","age":23}
	,{"country":"South Korea","biasId":86,"city":"Seongnam","artistId":86,"bloodType":"AB","heightStr":"1.60 m.","fandom":"InSomnia","weightStr":"45.00 kg.","height":160,"agency":"Dreamcatcher Company","zodiac":"Aquarius","chineseZodiac":"Rabbit","weight":45,"groupNameUpper":"DREAMCATCHER","positions":"Lead Rapper, Sub Vocalist, Maknae","nameUpper":"GAHYEON","zodiacId":11,"birthDate":19990203,"realName":"Lee Gahyeon","groupName":"Dreamcatcher","chineseZodiacId":4,"person":2,"imageFileName":"GAHYEON_DREAMCATCHER","name":"Gahyeon","age":23}
	,{"country":"South Korea","agency":"RBW","biasId":89,"city":"Busan","zodiac":"Aquarius","chineseZodiac":"Dragon","groupNameUpper":"PURPLE KISS","positions":"Main Dancer, Vocalist","artistId":89,"nameUpper":"DOSIE","zodiacId":11,"bloodType":"---","birthDate":20000211,"heightStr":"1.65 m.","realName":"Jang Eunseong","groupName":"Purple Kiss","chineseZodiacId":5,"person":1,"imageFileName":"DOSIE_PURPLEKISS","fandom":"PLORY","name":"Dosie","age":22,"height":165}
	,{"country":"Japan","agency":"RBW","biasId":92,"city":"---","zodiac":"Scorpius","chineseZodiac":"Horse","groupNameUpper":"PURPLE KISS","positions":"Main Rapper, Lead Dancer, Vocalist","artistId":92,"nameUpper":"YUKI","zodiacId":8,"bloodType":"O","birthDate":20021106,"heightStr":"1.64 m.","realName":"Mori Koyuki","groupName":"Purple Kiss","chineseZodiacId":7,"person":1,"imageFileName":"YUKI_PURPLEKISS","fandom":"PLORY","name":"Yuki","age":19,"height":164}
	,{"country":"South Korea","biasId":96,"city":"Yangsan/South Gyeongsang","artistId":96,"bloodType":"B","heightStr":"1.63 m.","fandom":"WIZ*ONE","weightStr":"43.00 kg.","height":163,"agency":"8D Entertainment","zodiac":"Cancer","chineseZodiac":"Rabbit","weight":43,"groupNameUpper":"SOLOIST","positions":"---","nameUpper":"HYEWON","zodiacId":4,"birthDate":19990705,"realName":"Kang Hyewon","groupName":"soloist","chineseZodiacId":4,"person":1,"imageFileName":"HYEWON_SOLOIST","name":"Hyewon","age":23}
	,{"country":"South Korea","agency":"JYP Entertainment","biasId":97,"city":"Busan","zodiac":"Aries","chineseZodiac":"Monkey","groupNameUpper":"NMIXX","positions":"Vocalist, Dancer, Rapper","artistId":97,"nameUpper":"JINNI","zodiacId":1,"bloodType":"A","birthDate":20040416,"heightStr":"1.65 m.","realName":"Choi Yunjin","groupName":"NMIXX","chineseZodiacId":9,"person":1,"imageFileName":"JINNI_NMIXX","fandom":"NSWER","name":"Jinni","age":18,"height":165}
	,{"country":"South Korea","agency":"JYP Entertainment","biasId":98,"city":"Bundang-gu/Seongnam/Gyeonggi-do","zodiac":"Gemini","chineseZodiac":"Dog","groupNameUpper":"NMIXX","positions":"Vocalist, Dancer, Rapper, Maknae","artistId":98,"nameUpper":"KYUJIN","zodiacId":3,"bloodType":"A","birthDate":20060526,"heightStr":"1.66 m.","realName":"Jang Kyujin","groupName":"NMIXX","chineseZodiacId":11,"person":2,"imageFileName":"KYUJIN_NMIXX","fandom":"NSWER","name":"Kyujin","age":16,"height":166}
	,{"country":"South Korea","biasId":102,"city":"Chuncheon/Gangwon","artistId":102,"bloodType":"O","heightStr":"1.61 m.","fandom":"Miracle","weightStr":"43.00 kg.","height":161,"agency":"WM Entertainment","zodiac":"Virgo","chineseZodiac":"Ox","weight":43,"groupNameUpper":"OH MY GIRL","positions":"Sub Vocalist","nameUpper":"YUBIN","zodiacId":6,"birthDate":19970909,"realName":"Bae Yubin","groupName":"Oh My Girl","chineseZodiacId":2,"person":1,"imageFileName":"YUBIN_OHMYGIRL","name":"Yubin","age":25}
	,{"country":"South Korea","biasId":107,"city":"Miryang/Gyeongsangnam-do","artistId":107,"bloodType":"---","heightStr":"1.69 m.","fandom":"FEARNOT","weightStr":"46.00 kg.","height":169,"agency":"Source Music","zodiac":"Scorpius","chineseZodiac":"Dog","weight":46,"groupNameUpper":"LE SSERAFIM","positions":"Vocalist, Dancer, Maknae","nameUpper":"EUNCHAE","zodiacId":8,"birthDate":20061110,"realName":"Hong Eunchae","groupName":"LE SSERAFIM","chineseZodiacId":11,"person":1,"imageFileName":"EUNCHAE_LESSERAFIM","name":"Eunchae","age":15}
	,{"country":"China","biasId":108,"city":"Sichuan","artistId":108,"bloodType":"AB","heightStr":"1.68 m.","fandom":"Kep1ian","weightStr":"47.00 kg.","height":168,"agency":"WAKEONE and Swing Entertainment","zodiac":"Scorpius","chineseZodiac":"Rabbit","weight":47,"groupNameUpper":"KEP1ER","positions":"---","nameUpper":"XIAOTING","zodiacId":8,"birthDate":19991112,"realName":"Shen Xiaoting","groupName":"Kep1er","chineseZodiacId":4,"person":1,"imageFileName":"XIAOTING_KEP1ER","name":"Xiaoting","age":22}
	,{"country":"South Korea","agency":"JYP Entertainment","biasId":110,"city":"Yangsan/Gyeongsangnam-do","zodiac":"Capricorn","chineseZodiac":"Monkey","groupNameUpper":"NMIXX","positions":"Vocalist, Dancer","artistId":110,"nameUpper":"BAE","zodiacId":10,"bloodType":"A","birthDate":20041228,"heightStr":"1.71 m.","realName":"Bae Jinsol","groupName":"NMIXX","chineseZodiacId":9,"person":1,"imageFileName":"BAE_NMIXX","fandom":"NSWER","name":"Bae","age":17,"height":171}
	,{"country":"China","agency":"FC ENM","biasId":111,"city":"---","zodiac":"Gemini","chineseZodiac":"Horse","groupNameUpper":"ILY:1","positions":"Vocalist","artistId":111,"nameUpper":"RONA","zodiacId":3,"bloodType":"---","birthDate":20020605,"heightStr":"1.65 m.","realName":"Chang Ching","groupName":"ily:1","chineseZodiacId":7,"person":2,"imageFileName":"RONA_ILY1","fandom":"Only:1","name":"Rona","age":20,"height":165}
	,{"country":"South Korea","biasId":113,"city":"Suncheon/South Jeolla","artistId":113,"bloodType":"O","heightStr":"1.60 m.","fandom":"Orbit","weightStr":"45.00 kg.","height":160,"agency":"BlockBerryCreative","zodiac":"Leo","chineseZodiac":"Ox","weight":45,"groupNameUpper":"LOONA","positions":"Leader, Vocalist, Rapper","nameUpper":"HASEUL","zodiacId":5,"birthDate":19970818,"realName":"Cho Haseul","groupName":"LOONA","chineseZodiacId":2,"person":1,"imageFileName":"HASEUL_LOONA","name":"Haseul","age":25}
	,{"country":"South Korea","biasId":114,"city":"Gwangmyeong/Gyeonggi-do","artistId":114,"bloodType":"B","heightStr":"1.71 m.","fandom":"Belllie've","weightStr":"48.00 kg.","height":171,"agency":"MYSTIC Story","zodiac":"Aquarius","chineseZodiac":"Rooster","weight":48,"groupNameUpper":"BILLLIE","positions":"Main Rapper, Lead Dancer","nameUpper":"SIYOON","zodiacId":11,"birthDate":20050216,"realName":"Kim Siyoon","groupName":"Billlie","chineseZodiacId":10,"person":2,"imageFileName":"SIYOON_BILLLIE","name":"Siyoon","age":17}
	,{"country":"South Korea","agency":"JYP Entertainment","biasId":116,"city":"Incheon","zodiac":"Pisces","chineseZodiac":"Goat","groupNameUpper":"NMIXX","positions":"Leader, Vocalist","artistId":116,"nameUpper":"HAEWON","zodiacId":12,"bloodType":"---","birthDate":20030225,"heightStr":"1.63 m.","realName":"Oh Haewon","groupName":"NMIXX","chineseZodiacId":8,"person":2,"imageFileName":"HAEWON_NMIXX","fandom":"NSWER","name":"Haewon","age":19,"height":163}
	,{"country":"South Korea","agency":"NV Entertainment","biasId":117,"city":"Seocho-gu/Seoul","zodiac":"Aquarius","chineseZodiac":"Goat","groupNameUpper":"WOO!AH!","positions":"Lead Vocalist, Visual","artistId":117,"nameUpper":"WOOYEON","zodiacId":11,"bloodType":"AB","birthDate":20030211,"heightStr":"1.67 m.","realName":"Park Jinkyung","groupName":"woo!ah!","chineseZodiacId":8,"person":1,"imageFileName":"WOOYEON_WOOAH","fandom":"wow!","name":"Wooyeon","age":19,"height":167}
	,{"country":"South Korea","biasId":119,"city":"Cheongju/North Chungcheong","artistId":119,"bloodType":"A","heightStr":"1.72 m.","fandom":"DIVE","weightStr":"50.00 kg.","height":172,"agency":"Starship Entertainment","zodiac":"Virgo","chineseZodiac":"Goat","weight":50,"groupNameUpper":"IVE","positions":"Leader, Main Dancer, Vocalist","nameUpper":"YUJIN","zodiacId":6,"birthDate":20030901,"realName":"Ahn Yujin","groupName":"IVE","chineseZodiacId":8,"person":2,"imageFileName":"YUJIN_IVE","name":"Yujin","age":19}
	,{"country":"South Korea","biasId":121,"city":"Sang-dong/Yeoju/Gyeonggi-do","artistId":121,"bloodType":"AB","heightStr":"1.56 m.","fandom":"CLIKE:y","weightStr":"40.00 kg.","height":156,"agency":"M25","zodiac":"Capricorn","chineseZodiac":"Pig","weight":40,"groupNameUpper":"CLASS:Y","positions":"Lead Dancer, Vocalist","nameUpper":"RIWON","zodiacId":10,"birthDate":20070111,"realName":"Kim Riwon","groupName":"CLASS:y","chineseZodiacId":12,"person":1,"imageFileName":"RIWON_CLASSY","name":"Riwon","age":15}
	,{"country":"South Korea","biasId":122,"city":"Sambang-dong/Gimhae/Gyeongsangnam-do","artistId":122,"bloodType":"A","heightStr":"1.63 m.","fandom":"For Ever","weightStr":"45.00 kg.","height":163,"agency":"Yuehua Entertainment","zodiac":"Capricorn","chineseZodiac":"Dragon","weight":45,"groupNameUpper":"EVERGLOW","positions":"Main Vocalist, Main Dancer, Sub Rapper","nameUpper":"MIA","zodiacId":10,"birthDate":20000113,"realName":"Han Eunji","groupName":"Everglow","chineseZodiacId":5,"person":2,"imageFileName":"MIA_EVERGLOW","name":"Mia","age":22}
	,{"country":"South Korea","biasId":123,"city":"Chuncheon/Gangwon-do","artistId":123,"bloodType":"---","heightStr":"1.55 m.","fandom":"SUMIT","weightStr":"43.00 kg.","height":155,"agency":"Cube Entertainment","zodiac":"Sagittarius","chineseZodiac":"Horse","weight":43,"groupNameUpper":"LIGHTSUM","positions":"Main Vocalist, Lead Dancer, Center","nameUpper":"NAYOUNG","zodiacId":9,"birthDate":20021130,"realName":"Kim Nayoung","groupName":"Lightsum","chineseZodiacId":7,"person":1,"imageFileName":"NAYOUNG_LIGHTSUM","name":"Nayoung","age":19}
	,{"country":"Japan","biasId":127,"city":"Kochi","artistId":127,"bloodType":"---","heightStr":"1.70 m.","fandom":"FEARNOT","weightStr":"51.00 kg.","height":170,"agency":"Source Music","zodiac":"Leo","chineseZodiac":"Goat","weight":51,"groupNameUpper":"LE SSERAFIM","positions":"Vocalist, Rapper, Dancer","nameUpper":"KAZUHA","zodiacId":5,"birthDate":20030809,"realName":"Nakamura Kazuha","groupName":"LE SSERAFIM","chineseZodiacId":8,"person":2,"imageFileName":"KAZUHA_LESSERAFIM","name":"Kazuha","age":19}
	,{"country":"South Korea","biasId":128,"city":"Yeongju-si/North Gyeongsang","artistId":128,"bloodType":"B","heightStr":"1.63 m.","fandom":"Page","weightStr":"45.00 kg.","height":163,"agency":"iMe Entertainment","zodiac":"Taurus","chineseZodiac":"Dragon","weight":45,"groupNameUpper":"DREAM NOTE","positions":"Leader, Lead Dancer, Lead Vocalist","nameUpper":"YOUI","zodiacId":2,"birthDate":20000424,"realName":"Kim Jihyeon","groupName":"Dream Note","chineseZodiacId":5,"person":1,"imageFileName":"YOUI_DREAMNOTE","name":"YOUI","age":22}
	,{"country":"South Korea","biasId":130,"city":"Seoul","artistId":130,"bloodType":"A","heightStr":"1.62 m.","fandom":"Ujung","weightStr":"44.00 kg.","height":162,"agency":"Starship Entertainment","zodiac":"Capricorn","chineseZodiac":"Rabbit","weight":44,"groupNameUpper":"WJSN","positions":"Main Dancer, Vocalist, Rapper","nameUpper":"YEOREUM","zodiacId":10,"birthDate":19990110,"realName":"Lee Jinsuk","groupName":"WJSN","chineseZodiacId":4,"person":2,"imageFileName":"YEOREUM_WJSN","name":"Yeoreum","age":23}
	,{"country":"South Korea","biasId":131,"city":"Gangnam-gu/Seoul","artistId":131,"bloodType":"B","heightStr":"1.72 m.","fandom":"FEARNOT","weightStr":"54.00 kg.","height":172,"agency":"Source Music","zodiac":"Scorpius","chineseZodiac":"Snake","weight":54,"groupNameUpper":"LE SSERAFIM","positions":"Vocalist","nameUpper":"YUNJIN","zodiacId":8,"birthDate":20011108,"realName":"Huh Yunjin","groupName":"LE SSERAFIM","chineseZodiacId":6,"person":1,"imageFileName":"YUNJIN_LESSERAFIM","name":"Yunjin","age":20}
	,{"country":"South Korea","agency":"KM Entertainment","biasId":132,"city":"Wonju/Gangwon","zodiac":"Aquarius","chineseZodiac":"Monkey","groupNameUpper":"ICHILLIN","positions":"Lead Dancer, Sub Vocalist, Center","artistId":132,"nameUpper":"YEJU","zodiacId":11,"bloodType":"A","birthDate":20040201,"heightStr":"1.66 m.","realName":"Kim Yeju","groupName":"ichillin","chineseZodiacId":9,"person":1,"imageFileName":"YEJU_ICHILLIN","fandom":"Willing","name":"Yeju","age":18,"height":166}
	,{"country":"USA","agency":"KM Entertainment","biasId":133,"city":"Los Angeles/California","zodiac":"Scorpius","chineseZodiac":"Snake","groupNameUpper":"ICHILLIN","positions":"Main Rapper, Lead Dancer","artistId":133,"nameUpper":"JACKIE","zodiacId":8,"bloodType":"B","birthDate":20011117,"heightStr":"1.61 m.","realName":"Kang Chaeyeon/Jackeline Kang","groupName":"ichillin","chineseZodiacId":6,"person":1,"imageFileName":"JACKIE_ICHILLIN","fandom":"Willing","name":"Jackie","age":20,"height":161}
	,{"country":"South Korea","biasId":137,"city":"Seoul","artistId":137,"bloodType":"AB","heightStr":"1.71 m.","fandom":"SUMIT","weightStr":"48.00 kg.","height":171,"agency":"Cube Entertainment","zodiac":"Aries","chineseZodiac":"Monkey","weight":48,"groupNameUpper":"LIGHTSUM","positions":"Leader, Main Dancer, Lead Vocalist","nameUpper":"JUHYEON","zodiacId":1,"birthDate":20040408,"realName":"Lee Juhyeon","groupName":"Lightsum","chineseZodiacId":9,"person":1,"imageFileName":"JUHYEON_LIGHTSUM","name":"Juhyeon","age":18}
	,{"country":"South Korea","biasId":138,"city":"Deokpung-dong/Hanam","artistId":138,"bloodType":"O","heightStr":"1.63 m.","fandom":"CLIKE:y","weightStr":"41.00 kg.","height":163,"agency":"M25","zodiac":"Gemini","chineseZodiac":"Goat","weight":41,"groupNameUpper":"CLASS:Y","positions":"Main Vocalist","nameUpper":"CHAEWON","zodiacId":3,"birthDate":20030604,"realName":"Yoon Chaewon","groupName":"CLASS:y","chineseZodiacId":8,"person":1,"imageFileName":"CHAEWON_CLASSY","name":"Chaewon","age":19}
	,{"country":"South Korea","biasId":139,"city":"Bangok-dong/Wonju/Gangwon-do","artistId":139,"bloodType":"AB","heightStr":"1.72 m.","fandom":"CLIKE:y","weightStr":"51.00 kg.","height":172,"agency":"M25","zodiac":"Leo","chineseZodiac":"Pig","weight":51,"groupNameUpper":"CLASS:Y","positions":"Main Vocalist, Center","nameUpper":"JIMIN","zodiacId":5,"birthDate":20070725,"realName":"Won Jimin","groupName":"CLASS:y","chineseZodiacId":12,"person":1,"imageFileName":"JIMIN_CLASSY","name":"Jimin","age":15}
	,{"country":"South Korea","biasId":140,"city":"Seoul","artistId":140,"bloodType":"B","heightStr":"1.62 m.","fandom":"FEARNOT","weightStr":"43.00 kg.","height":162,"agency":"Source Music","zodiac":"Leo","chineseZodiac":"Dragon","weight":43,"groupNameUpper":"LE SSERAFIM","positions":"Leader, Vocalist","nameUpper":"CHAEWON","zodiacId":5,"birthDate":20000801,"realName":"Kim Chaewon","groupName":"LE SSERAFIM","chineseZodiacId":5,"person":2,"imageFileName":"CHAEWON_LESSERAFIM","name":"Chaewon","age":22}
	,{"country":"Japan","biasId":142,"city":"Fukuoka","artistId":142,"bloodType":"---","heightStr":"1.55 m.","fandom":"Kep1ian","weightStr":"39.00 kg.","height":155,"agency":"WAKEONE and Swing Entertainment","zodiac":"Pisces","chineseZodiac":"Monkey","weight":39,"groupNameUpper":"KEP1ER","positions":"---","nameUpper":"HIKARU","zodiacId":12,"birthDate":20040312,"realName":"Ezaki Hikaru","groupName":"Kep1er","chineseZodiacId":9,"person":2,"imageFileName":"HIKARU_KEP1ER","name":"Hikaru","age":18}
	,{"country":"South Korea","biasId":143,"city":"Songpa-gu/Seoul","artistId":143,"bloodType":"O","heightStr":"1.65 m.","fandom":"CLIKE:y","weightStr":"45.00 kg.","height":165,"agency":"M25","zodiac":"Sagittarius","chineseZodiac":"Goat","weight":45,"groupNameUpper":"CLASS:Y","positions":"Leader, Main Dancer, Lead Rapper, Vocalist","nameUpper":"HYEJU","zodiacId":9,"birthDate":20031209,"realName":"Hong Hyeju","groupName":"CLASS:y","chineseZodiacId":8,"person":2,"imageFileName":"HYEJU_CLASSY","name":"Hyeju","age":18}
	,{"country":"Japan","agency":"FC ENM","biasId":145,"city":"Osaka","zodiac":"Cancer","chineseZodiac":"Horse","groupNameUpper":"ILY:1","positions":"Lead Vocalist","artistId":145,"nameUpper":"RIRIKA","zodiacId":4,"bloodType":"---","birthDate":20020702,"heightStr":"1.62 m.","realName":"Kishida Ririka","groupName":"ily:1","chineseZodiacId":7,"person":1,"imageFileName":"RIRIKA_ILY1","fandom":"Only:1","name":"Ririka","age":20,"height":162}
	,{"country":"South Korea","biasId":150,"city":"Busan","artistId":150,"bloodType":"---","heightStr":"1.71 m.","fandom":"Winxy","weightStr":"50.00 kg.","height":171,"agency":"ALLART Entertainment","zodiac":"Pisces","chineseZodiac":"Snake","weight":50,"groupNameUpper":"PIXY","positions":"Main Rapper, Visual","nameUpper":"LOLA","zodiacId":12,"birthDate":20010222,"realName":"Choi Yoojung","groupName":"Pixy","chineseZodiacId":6,"person":1,"imageFileName":"LOLA_PIXY","name":"Lola","age":21}
	,{"country":"South Korea","biasId":152,"city":"Busan","artistId":152,"bloodType":"AB","heightStr":"1.63 m.","fandom":"GLASSY","weightStr":"43.00 kg.","height":163,"agency":"WAKEONE Entertainment","zodiac":"Libra","chineseZodiac":"Snake","weight":43,"groupNameUpper":"SOLOIST","positions":"---","nameUpper":"YURI","zodiacId":7,"birthDate":20011022,"realName":"Jo Yuri","groupName":"soloist","chineseZodiacId":6,"person":2,"imageFileName":"YURI_SOLOIST","name":"Yuri","age":20}
	,{"country":"South Korea","biasId":153,"city":"Gangneung/Gangwon-do","artistId":153,"bloodType":"B","heightStr":"1.60 m.","fandom":"CLIKE:y","weightStr":"43.00 kg.","height":160,"agency":"M25","zodiac":"Pisces","chineseZodiac":"Rat","weight":43,"groupNameUpper":"CLASS:Y","positions":"Main Rapper, Lead Dancer, Vocalist, Maknae","nameUpper":"SEONYU","zodiacId":12,"birthDate":20080320,"realName":"Kim Seonyu","groupName":"CLASS:y","chineseZodiacId":1,"person":2,"imageFileName":"SEONYU_CLASSY","name":"Seonyu","age":14}
	,{"country":"South Korea","biasId":155,"city":"Uijeongbu","artistId":155,"bloodType":"B","heightStr":"1.65 m.","fandom":"Orbit","weightStr":"46.00 kg.","height":165,"agency":"BlockBerryCreative","zodiac":"Scorpius","chineseZodiac":"Snake","weight":46,"groupNameUpper":"LOONA","positions":"Dancer, Rapper, Vocalist","nameUpper":"OLIVIA HYE","zodiacId":8,"birthDate":20011113,"realName":"Son Hyeju","groupName":"LOONA","chineseZodiacId":6,"person":1,"imageFileName":"OLIVIAHYE_LOONA","name":"Olivia Hye","age":20}
	,{"country":"South Korea","biasId":157,"city":"Incheon","artistId":157,"bloodType":"B","heightStr":"1.70 m.","fandom":"Ujung","weightStr":"49.00 kg.","height":170,"agency":"Starship Entertainment","zodiac":"Gemini","chineseZodiac":"Tiger","weight":49,"groupNameUpper":"WJSN","positions":"Vocalist, Rapper","nameUpper":"EUNSEO","zodiacId":3,"birthDate":19980527,"realName":"Son Juyeon","groupName":"WJSN","chineseZodiacId":3,"person":1,"imageFileName":"EUNSEO_WJSN","name":"Eunseo","age":24}
	,{"country":"Japan","agency":"MLD Entertainment","biasId":159,"city":"Kochi","zodiac":"Pisces","chineseZodiac":"Goat","groupNameUpper":"LAPILLUS","positions":"Leader, Vocalist","artistId":159,"nameUpper":"SHANA","zodiacId":12,"bloodType":"B","birthDate":20030313,"heightStr":"1.58 m.","realName":"Nonaka Shana","groupName":"Lapillus","chineseZodiacId":8,"person":2,"imageFileName":"SHANA_LAPILLUS","fandom":"---","name":"Shana","age":19,"height":158}
	,{"country":"South Korea","agency":"Grandline Group (GLG)","biasId":162,"city":"---","zodiac":"Capricorn","chineseZodiac":"Monkey","groupNameUpper":"H1-KEY","positions":"Vocalist, Rapper, Maknae","artistId":162,"nameUpper":"YEL","zodiacId":10,"bloodType":"---","birthDate":20041225,"heightStr":"1.72 m.","realName":"Han Shinyoung","groupName":"H1-KEY","chineseZodiacId":9,"person":1,"imageFileName":"YEL_H1KEY","fandom":"M1-KEY","name":"Yel","age":17,"height":172}
	,{"country":"South Korea","biasId":163,"city":"Chungju","artistId":163,"bloodType":"A","heightStr":"1.61 m.","fandom":"Orbit","weightStr":"44.00 kg.","height":161,"agency":"BlockBerryCreative","zodiac":"Libra","chineseZodiac":"Rabbit","weight":44,"groupNameUpper":"LOONA","positions":"Vocalist, Rapper, Face of the Group","nameUpper":"CHUU","zodiacId":7,"birthDate":19991020,"realName":"Kim Jiwoo","groupName":"LOONA","chineseZodiacId":4,"person":2,"imageFileName":"CHUU_LOONA","name":"Chuu","age":22}
	,{"country":"South Korea","biasId":164,"city":"Seoul","artistId":164,"bloodType":"AB","heightStr":"1.64 m.","fandom":"Lullet","weightStr":"48.00 kg.","height":164,"agency":"FNC Entertainment","zodiac":"Virgo","chineseZodiac":"Dragon","weight":48,"groupNameUpper":"CHERRY BULLET","positions":"Lead Vocalist, Rapper, Visual, Center","nameUpper":"JIWON","zodiacId":6,"birthDate":20000904,"realName":"Heo Jiwon","groupName":"Cherry Bullet","chineseZodiacId":5,"person":2,"imageFileName":"JIWON_CHERRYBULLET","name":"Jiwon","age":22}
	,{"country":"South Korea","biasId":165,"city":"Yeonje-gu/Busan","artistId":165,"bloodType":"B","heightStr":"1.61 m.","fandom":"Kep1ian","weightStr":"43.00 kg.","height":161,"agency":"WAKEONE and Swing Entertainment","zodiac":"Taurus","chineseZodiac":"Horse","weight":43,"groupNameUpper":"KEP1ER","positions":"Center","nameUpper":"CHAEHYUN","zodiacId":2,"birthDate":20020426,"realName":"Kim Chaehyun","groupName":"Kep1er","chineseZodiacId":7,"person":2,"imageFileName":"CHAEHYUN_KEP1ER","name":"Chaehyun","age":20}
	,{"country":"South Korea","biasId":168,"city":"Yongin","artistId":168,"bloodType":"B","heightStr":"1.68 m.","fandom":"MIDZY","weightStr":"46.00 kg.","height":168,"agency":"JYP Entertainment","zodiac":"Gemini","chineseZodiac":"Snake","weight":46,"groupNameUpper":"ITZY","positions":"Main Dancer, Sub Vocalist, Sub Rapper","nameUpper":"CHAERYEONG","zodiacId":3,"birthDate":20010605,"realName":"Lee Chaeryeong","groupName":"ITZY","chineseZodiacId":6,"person":1,"imageFileName":"CHAERYEONG_ITZY","name":"Chaeryeong","age":21}
	,{"country":"South Korea","biasId":169,"city":"Hwasun/South Jeolla","artistId":169,"bloodType":"B","heightStr":"1.65 m.","fandom":"RAINBOO","weightStr":"44.00 kg.","height":165,"agency":"A team Entertainment","zodiac":"Leo","chineseZodiac":"Snake","weight":44,"groupNameUpper":"BUGABOO","positions":"Leader, Main Dancer, Vocalist, Rapper","nameUpper":"CHOYEON","zodiacId":5,"birthDate":20010801,"realName":"Kim Choyeon","groupName":"bugAboo","chineseZodiacId":6,"person":2,"imageFileName":"CHOYEON_BUGABOO","name":"Choyeon","age":21}
	,{"country":"South Korea","agency":"Pop Music","biasId":170,"city":"---","zodiac":"Taurus","chineseZodiac":"Rooster","groupNameUpper":"CSR","positions":"---","artistId":170,"nameUpper":"DUNA","zodiacId":2,"bloodType":"A","birthDate":20050428,"heightStr":"1.64 m.","realName":"Kang Duna","groupName":"CSR","chineseZodiacId":10,"person":2,"imageFileName":"DUNA_CSR","fandom":"---","name":"Duna","age":17,"height":164}
	,{"country":"South Korea","agency":"Pop Music","biasId":173,"city":"---","zodiac":"Pisces","chineseZodiac":"Rooster","groupNameUpper":"CSR","positions":"---","artistId":173,"nameUpper":"SIHYEON","zodiacId":12,"bloodType":"B","birthDate":20050312,"realName":"Hwang Sihyeon","groupName":"CSR","chineseZodiacId":10,"person":1,"imageFileName":"SIHYEON_CSR","fandom":"---","name":"Sihyeon","age":17}
	,{"country":"South Korea","agency":"MLD Entertainment","biasId":175,"city":"---","zodiac":"Scorpius","chineseZodiac":"Rat","groupNameUpper":"LAPILLUS","positions":"Dancer, Vocalist, Center, Maknae","artistId":175,"nameUpper":"HAEUN","zodiacId":8,"bloodType":"---","birthDate":20081102,"heightStr":"1.60 m.","realName":"Lim Haeun","groupName":"Lapillus","chineseZodiacId":1,"person":2,"imageFileName":"HAEUN_LAPILLUS","fandom":"---","name":"Haeun","age":13,"height":160}
	,{"country":"South Korea","agency":"Pop Music","biasId":178,"city":"Anyang/Gyeonggi-do","zodiac":"Leo","chineseZodiac":"Rooster","groupNameUpper":"CSR","positions":"Leader","artistId":178,"nameUpper":"SUA","zodiacId":5,"bloodType":"B","birthDate":20050723,"realName":"Yoo Sua","groupName":"CSR","chineseZodiacId":10,"person":1,"imageFileName":"SUA_CSR","fandom":"---","name":"Sua","age":17}
	,{"country":"Taiwan","biasId":180,"city":"Kaohsiung","artistId":180,"bloodType":"A","heightStr":"1.70 m.","fandom":"TRUE","weightStr":"49.00 kg.","height":170,"agency":"TR Entertainment","zodiac":"Capricorn","chineseZodiac":"Horse","weight":49,"groupNameUpper":"TRI.BE","positions":"Lead Vocalist, Visual","nameUpper":"KELLY","zodiacId":10,"birthDate":20020116,"realName":"Lin Weixi","groupName":"TRI.BE","chineseZodiacId":7,"person":1,"imageFileName":"KELLY_TRIBE","name":"Kelly","age":20}
	,{"country":"South Korea","biasId":182,"city":"Incheon","artistId":182,"bloodType":"B","heightStr":"1.66 m.","fandom":"RAINBOO","weightStr":"45.00 kg.","height":166,"agency":"A team Entertainment","zodiac":"Virgo","chineseZodiac":"Snake","weight":45,"groupNameUpper":"BUGABOO","positions":"Main Vocalist, Maknae","nameUpper":"ZIN","zodiacId":6,"birthDate":20010830,"realName":"Jin Hyunbin","groupName":"bugAboo","chineseZodiacId":6,"person":1,"imageFileName":"ZIN_BUGABOO","name":"Zin","age":21}
	,{"country":"USA","biasId":186,"city":"California","artistId":186,"bloodType":"---","heightStr":"1.63 m.","fandom":"---","weightStr":"48.00 kg.","height":163,"agency":"MLD Entertainment","zodiac":"Cancer","chineseZodiac":"Monkey","weight":48,"groupNameUpper":"LAPILLUS","positions":"Vocalist, Dancer","nameUpper":"YUE","zodiacId":4,"birthDate":20040703,"realName":"Nancy Yang","groupName":"Lapillus","chineseZodiacId":9,"person":1,"imageFileName":"YUE_LAPILLUS","name":"Yue","age":18}
	,{"country":"South Korea","biasId":195,"city":"Seoul","artistId":195,"bloodType":"B","heightStr":"1.65 m.","fandom":"MIDZY","weightStr":"45.00 kg.","height":165,"agency":"JYP Entertainment","zodiac":"Aries","chineseZodiac":"Snake","weight":45,"groupNameUpper":"ITZY","positions":"Main Rapper, Lead Dancer, Sub Vocalist, Center","nameUpper":"RYUJIN","zodiacId":1,"birthDate":20010417,"realName":"Shin Ryujin","groupName":"ITZY","chineseZodiacId":6,"person":2,"imageFileName":"RYUJIN_ITZY","name":"Ryujin","age":21}
	,{"country":"South Korea","biasId":198,"city":"Naju","artistId":198,"bloodType":"A","heightStr":"1.62 m.","fandom":"signfan","weightStr":"48.00 kg.","height":162,"agency":"J9 Entertainment","zodiac":"Scorpius","chineseZodiac":"Snake","weight":48,"groupNameUpper":"CIGNATURE","positions":"Lead Vocalist","nameUpper":"BELLE","zodiacId":8,"birthDate":20011103,"realName":"Jin Hyeonju","groupName":"cignature","chineseZodiacId":6,"person":2,"imageFileName":"BELLE_CIGNATURE","name":"Belle","age":20}
	,{"country":"South Korea","biasId":201,"city":"Goyang/Gyeonggi-do","artistId":201,"bloodType":"A","heightStr":"1.67 m.","fandom":"Lullet","weightStr":"45.00 kg.","height":167,"agency":"FNC Entertainment","zodiac":"Pisces","chineseZodiac":"Horse","weight":45,"groupNameUpper":"CHERRY BULLET","positions":"Main Dancer, Vocalist, Rapper","nameUpper":"CHAERIN","zodiacId":12,"birthDate":20020313,"realName":"Park Chaerin","groupName":"Cherry Bullet","chineseZodiacId":7,"person":1,"imageFileName":"CHAERIN_CHERRYBULLET","name":"Chaerin","age":20}
	,{"country":"South Korea","biasId":216,"city":"Busan","artistId":216,"bloodType":"A","heightStr":"1.66 m.","fandom":"Ujung","weightStr":"48.00 kg.","height":166,"agency":"Starship Entertainment","zodiac":"Scorpius","chineseZodiac":"Pig","weight":48,"groupNameUpper":"WJSN","positions":"Leader, Main Rapper, Vocalist","nameUpper":"EXY","zodiacId":8,"birthDate":19951106,"realName":"Chu Sojung","groupName":"WJSN","chineseZodiacId":12,"person":2,"imageFileName":"EXY_WJSN","name":"Exy","age":26}
	,{"country":"South Korea","biasId":217,"city":"Garosu-gil/Seoul","artistId":217,"bloodType":"O","heightStr":"1.64 m.","fandom":"MY","weightStr":"47.00 kg.","height":164,"agency":"SM Entertainment","zodiac":"Scorpius","chineseZodiac":"Dragon","weight":47,"groupNameUpper":"AESPA","positions":"Main Rapper, Sub Vocalist","nameUpper":"GISELLE","zodiacId":8,"birthDate":20001030,"realName":"Uchinaga Aeri","groupName":"aespa","chineseZodiacId":5,"person":2,"imageFileName":"GISELLE_AESPA","name":"Giselle","age":21}
	,{"country":"South Korea","biasId":218,"city":"Seongdong-gu/Seoul","artistId":218,"bloodType":"B","heightStr":"1.68 m.","fandom":"Flover","weightStr":"50.00 kg.","height":168,"agency":"Pledis Entertainment","zodiac":"Capricorn","chineseZodiac":"Ox","weight":50,"groupNameUpper":"FROMIS_9","positions":"Lead Vocalist, Face of the Group","nameUpper":"GYURI","zodiacId":10,"birthDate":19971227,"realName":"Jang Gyuri","groupName":"fromis_9","chineseZodiacId":2,"person":1,"imageFileName":"GYURI_FROMIS9","name":"Gyuri","age":24}
	,{"country":"South Korea","biasId":227,"city":"Seoul","artistId":227,"bloodType":"B","heightStr":"1.63 m.","fandom":"MVP","weightStr":"43.00 kg.","height":163,"agency":"ANS Entertainment","zodiac":"Aquarius","chineseZodiac":"Snake","weight":43,"groupNameUpper":"MAJORS","positions":"Leader, Sub Vocalist","nameUpper":"IDA","zodiacId":11,"birthDate":20010212,"realName":"Ko Chaeyoung","groupName":"Majors","chineseZodiacId":6,"person":2,"imageFileName":"IDA_MAJORS","name":"Ida","age":21}
	,{"country":"South Korea","biasId":232,"city":"Busan","artistId":232,"bloodType":"A","heightStr":"1.58 m.","fandom":"Flover","weightStr":"44.00 kg.","height":158,"agency":"Pledis Entertainment","zodiac":"Pisces","chineseZodiac":"Tiger","weight":44,"groupNameUpper":"FROMIS_9","positions":"Main Vocalist","nameUpper":"JIWON","zodiacId":12,"birthDate":19980320,"realName":"Park Jiwon","groupName":"fromis_9","chineseZodiacId":3,"person":2,"imageFileName":"JIWON_FROMIS9","name":"Jiwon","age":24}
	,{"country":"USA","agency":"KM Entertainment","biasId":234,"city":"Los Angeles/California","zodiac":"Gemini","chineseZodiac":"Horse","groupNameUpper":"ICHILLIN","positions":"Lead Vocalist, Sub Rapper","artistId":234,"nameUpper":"JOONIE","zodiacId":3,"bloodType":"A","birthDate":20020524,"heightStr":"1.65 m.","realName":"Park Junhee","groupName":"ichillin","chineseZodiacId":7,"person":2,"imageFileName":"JOONIE_ICHILLIN","fandom":"Willing","name":"Joonie","age":20,"height":165}
	,{"country":"Japan","biasId":235,"city":"Tokyo","artistId":235,"bloodType":"B","heightStr":"1.67 m.","fandom":"LOCKEY","weightStr":"47.00 kg.","height":167,"agency":"Vine Entertainment","zodiac":"Leo","chineseZodiac":"Pig","weight":47,"groupNameUpper":"SECRET NUMBER","positions":"Leader, Lead Vocalist","nameUpper":"LEA","zodiacId":5,"birthDate":19950812,"realName":"Ogawa Misuki","groupName":"Secret Number","chineseZodiacId":12,"person":2,"imageFileName":"LEA_SECRETNUMBER","name":"Lea","age":27}
	,{"country":"Australia","agency":"JYP Entertainment","biasId":237,"city":"Victoria","zodiac":"Libra","chineseZodiac":"Horse","groupNameUpper":"NMIXX","positions":"Vocalist","artistId":237,"nameUpper":"LILY","zodiacId":7,"bloodType":"---","birthDate":20021017,"heightStr":"1.65 m.","realName":"Lily Jin Morrow","groupName":"NMIXX","chineseZodiacId":7,"person":2,"imageFileName":"LILY_NMIXX","fandom":"NSWER","name":"Lily","age":19,"height":165}
	,{"country":"South Korea","biasId":246,"city":"Incheon","artistId":246,"bloodType":"AB","heightStr":"1.68 m.","fandom":"FEARLESS","weightStr":"45.00 kg.","height":168,"agency":"Brave Entertainment","zodiac":"Virgo","chineseZodiac":"Horse","weight":45,"groupNameUpper":"BRAVE GIRLS","positions":"Leader, Main Vocalist, Lead Dancer","nameUpper":"MINYOUNG","zodiacId":6,"birthDate":19900912,"realName":"Kim Minyoung","groupName":"Brave Girls","chineseZodiacId":7,"person":2,"imageFileName":"MINYOUNG_BRAVEGIRLS","name":"Minyoung","age":32}
	,{"country":"South Korea","biasId":253,"city":"Goyang/Gyeonggi-do","artistId":253,"bloodType":"---","heightStr":"1.65 m.","fandom":"Winxy","weightStr":"54.00 kg.","height":165,"agency":"ALLART Entertainment","zodiac":"Pisces","chineseZodiac":"Snake","weight":54,"groupNameUpper":"PIXY","positions":"Lead Rapper","nameUpper":"SATBYEOL","zodiacId":12,"birthDate":20010227,"realName":"Jeon Yoojin","groupName":"Pixy","chineseZodiacId":6,"person":1,"imageFileName":"SATBYEOL_PIXY","name":"Satbyeol","age":21}
	,{"country":"South Korea","agency":"Grandline Group (GLG)","biasId":256,"city":"---","zodiac":"Aquarius","chineseZodiac":"Dragon","groupNameUpper":"H1-KEY","positions":"Leader, Vocalist","artistId":256,"nameUpper":"SEOI","zodiacId":11,"bloodType":"---","birthDate":20000212,"heightStr":"1.69 m.","realName":"Lee Yejin","groupName":"H1-KEY","chineseZodiacId":5,"person":1,"imageFileName":"SEOI_H1KEY","fandom":"M1-KEY","name":"Seoi","age":22,"height":169}
	,{"country":"South Korea","agency":"MLD Entertainment","biasId":257,"city":"---","zodiac":"Sagittarius","chineseZodiac":"Dog","groupNameUpper":"LAPILLUS","positions":"Rapper","artistId":257,"nameUpper":"SEOWON","zodiacId":9,"bloodType":"---","birthDate":20061205,"heightStr":"1.65 m.","realName":"Jang Seowon","groupName":"Lapillus","chineseZodiacId":11,"person":1,"imageFileName":"SEOWON_LAPILLUS","fandom":"---","name":"Seowon","age":15,"height":165}
	,{"country":"South Korea","biasId":259,"city":"Seoul","artistId":259,"bloodType":"A","heightStr":"1.58 m.","fandom":"Flover","weightStr":"42.00 kg.","height":158,"agency":"Pledis Entertainment","zodiac":"Aquarius","chineseZodiac":"Dragon","weight":42,"groupNameUpper":"FROMIS_9","positions":"Main Rapper, Vocalist","nameUpper":"SEOYEON","zodiacId":11,"birthDate":20000122,"realName":"Lee Seoyeon","groupName":"fromis_9","chineseZodiacId":5,"person":2,"imageFileName":"SEOYEON_FROMIS9","name":"Seoyeon","age":22}
	,{"country":"South Korea","biasId":262,"city":"Daegu","artistId":262,"bloodType":"A","heightStr":"1.66 m.","fandom":"InSomnia","weightStr":"49.00 kg.","height":166,"agency":"Dreamcatcher Company","zodiac":"Libra","chineseZodiac":"Pig","weight":49,"groupNameUpper":"DREAMCATCHER","positions":"Main Vocalist","nameUpper":"SIYEON","zodiacId":7,"birthDate":19951001,"realName":"Lee Siyeon","groupName":"Dreamcatcher","chineseZodiacId":12,"person":2,"imageFileName":"SIYEON_DREAMCATCHER","name":"Siyeon","age":26}
	,{"country":"South Korea","agency":"Pop Music","biasId":269,"city":"Yeoksam-dong/Gangnam/Seoul","zodiac":"Libra","chineseZodiac":"Rooster","groupNameUpper":"CSR","positions":"Main Vocalist, Maknae","artistId":269,"nameUpper":"YEHAM","zodiacId":7,"bloodType":"A","birthDate":20051007,"realName":"Goo Yeham","groupName":"CSR","chineseZodiacId":10,"person":2,"imageFileName":"YEHAM_CSR","fandom":"---","name":"Yeham","age":16}
	,{"country":"South Korea","biasId":273,"city":"Gwanak-gu/Seoul","artistId":273,"bloodType":"AB","heightStr":"1.62 m.","fandom":"SUMIT","weightStr":"41.00 kg.","height":162,"agency":"Cube Entertainment","zodiac":"Gemini","chineseZodiac":"Monkey","weight":41,"groupNameUpper":"LIGHTSUM","positions":"Sub Vocalist","nameUpper":"YUJEONG","zodiacId":3,"birthDate":20040614,"realName":"Lee Yujeong","groupName":"Lightsum","chineseZodiacId":9,"person":1,"imageFileName":"YUJEONG_LIGHTSUM","name":"Yujeong","age":18}
	]);
	