var artist = TAFFY([
    {"chineseZodiacId":4,"groupName":"Momoland","counter2":1,"zodiac":"Libra","counter1":1,"chineseZodiac":"Rabbit","name":"Ahin","zodiacId":7,"birthDate":19990927},
{"chineseZodiacId":5,"groupName":"Everglow","counter2":0,"zodiac":"Cancer","counter1":3,"chineseZodiac":"Dragon","name":"Aisha","zodiacId":4,"birthDate":20000721},
{"chineseZodiacId":5,"groupName":"Majors","counter2":0,"zodiac":"Taurus","counter1":0,"chineseZodiac":"Dragon","name":"Aki","zodiacId":2,"birthDate":20000519},
{"chineseZodiacId":7,"groupName":"ily:1","counter2":0,"zodiac":"Aquarius","counter1":0,"chineseZodiac":"Horse","name":"Ara","zodiacId":11,"birthDate":20020123},
{"chineseZodiacId":4,"groupName":"Oh My Girl","counter2":5,"zodiac":"Gemini","counter1":4,"chineseZodiac":"Rabbit","name":"Arin","zodiacId":3,"birthDate":19990618},
{"chineseZodiacId":9,"groupName":"NMIXX","counter2":0,"zodiac":"Capricorn","counter1":1,"chineseZodiac":"Monkey","name":"Bae","zodiacId":10,"birthDate":20041228},
{"chineseZodiacId":9,"groupName":"Kep1er","counter2":0,"zodiac":"Leo","counter1":0,"chineseZodiac":"Monkey","name":"Bahiyyih","zodiacId":5,"birthDate":20040727},
{"chineseZodiacId":6,"groupName":"cignature","counter2":0,"zodiac":"Scorpius","counter1":0,"chineseZodiac":"Snake","name":"Belle","zodiacId":8,"birthDate":20011103},
{"chineseZodiacId":1,"groupName":"CLASS:y","counter2":0,"zodiac":"Aquarius","counter1":0,"chineseZodiac":"Rat","name":"Boeun","zodiacId":11,"birthDate":20080211},
{"chineseZodiacId":12,"groupName":"WJSN","counter2":0,"zodiac":"Leo","counter1":0,"chineseZodiac":"Pig","name":"Bona","zodiacId":5,"birthDate":19950819},
{"chineseZodiacId":4,"groupName":"Dream Note","counter2":0,"zodiac":"Scorpius","counter1":2,"chineseZodiac":"Rabbit","name":"Boni","zodiacId":8,"birthDate":19991030},
{"chineseZodiacId":4,"groupName":"Cherry Bullet","counter2":3,"zodiac":"Pisces","counter1":4,"chineseZodiac":"Rabbit","name":"Bora","zodiacId":12,"birthDate":19990303},
{"chineseZodiacId":7,"groupName":"Kep1er","counter2":0,"zodiac":"Taurus","counter1":0,"chineseZodiac":"Horse","name":"Chaehyun","zodiacId":2,"birthDate":20020426},
{"chineseZodiacId":7,"groupName":"Purple Kiss","counter2":2,"zodiac":"Sagittarius","counter1":18,"chineseZodiac":"Horse","name":"Chaein","zodiacId":9,"birthDate":20021205},
{"chineseZodiacId":7,"groupName":"Cherry Bullet","counter2":0,"zodiac":"Pisces","counter1":0,"chineseZodiac":"Horse","name":"Chaerin","zodiacId":12,"birthDate":20020313},
{"chineseZodiacId":8,"groupName":"ichillin","counter2":0,"zodiac":"Aries","counter1":1,"chineseZodiac":"Goat","name":"Chaerin","zodiacId":1,"birthDate":20030331},
{"chineseZodiacId":6,"groupName":"ITZY","counter2":0,"zodiac":"Gemini","counter1":0,"chineseZodiac":"Snake","name":"Chaeryeong","zodiacId":3,"birthDate":20010605},
{"chineseZodiacId":3,"groupName":"cignature","counter2":1,"zodiac":"Cancer","counter1":2,"chineseZodiac":"Tiger","name":"Chaesol","zodiacId":4,"birthDate":19980714},
{"chineseZodiacId":8,"groupName":"CLASS:y","counter2":0,"zodiac":"Gemini","counter1":1,"chineseZodiac":"Goat","name":"Chaewon","zodiacId":3,"birthDate":20030604},
{"chineseZodiacId":5,"groupName":"LE SSERAFIM","counter2":3,"zodiac":"Leo","counter1":1,"chineseZodiac":"Dragon","name":"Chaewon","zodiacId":5,"birthDate":20000801},
{"chineseZodiacId":5,"groupName":"soloist","counter2":1,"zodiac":"Capricorn","counter1":2,"chineseZodiac":"Dragon","name":"Chaeyeon","zodiacId":10,"birthDate":20000111},
{"chineseZodiacId":5,"groupName":"fromis_9","counter2":0,"zodiac":"Taurus","counter1":5,"chineseZodiac":"Dragon","name":"Chaeyoung","zodiacId":2,"birthDate":20000514},
{"chineseZodiacId":4,"groupName":"Twice","counter2":0,"zodiac":"Taurus","counter1":0,"chineseZodiac":"Rabbit","name":"Chaeyoung","zodiacId":2,"birthDate":19990423},
{"chineseZodiacId":6,"groupName":"cignature","counter2":0,"zodiac":"Capricorn","counter1":0,"chineseZodiac":"Snake","name":"Chloe","zodiacId":10,"birthDate":20010106},
{"chineseZodiacId":6,"groupName":"LOONA","counter2":0,"zodiac":"Gemini","counter1":3,"chineseZodiac":"Snake","name":"Choerry","zodiacId":3,"birthDate":20010604},
{"chineseZodiacId":10,"groupName":"ichillin","counter2":0,"zodiac":"Leo","counter1":0,"chineseZodiac":"Rooster","name":"Chowon","zodiacId":5,"birthDate":20050818},
{"chineseZodiacId":7,"groupName":"Lightsum","counter2":0,"zodiac":"Virgo","counter1":1,"chineseZodiac":"Horse","name":"Chowon","zodiacId":6,"birthDate":20020916},
{"chineseZodiacId":1,"groupName":"soloist","counter2":0,"zodiac":"Aquarius","counter1":2,"chineseZodiac":"Rat","name":"Chungha","zodiacId":11,"birthDate":19960209},
{"chineseZodiacId":4,"groupName":"LOONA","counter2":0,"zodiac":"Libra","counter1":0,"chineseZodiac":"Rabbit","name":"Chuu","zodiacId":7,"birthDate":19991020},
{"chineseZodiacId":10,"groupName":"Rocket Punch","counter2":0,"zodiac":"Taurus","counter1":0,"chineseZodiac":"Rooster","name":"Dahyun","zodiacId":2,"birthDate":20050429},
{"chineseZodiacId":3,"groupName":"Twice","counter2":0,"zodiac":"Gemini","counter1":0,"chineseZodiac":"Tiger","name":"Dahyun","zodiacId":3,"birthDate":19980528},
{"chineseZodiacId":8,"groupName":"Pixy","counter2":1,"zodiac":"Leo","counter1":4,"chineseZodiac":"Goat","name":"Dajeong","zodiacId":5,"birthDate":20030731},
{"chineseZodiacId":2,"groupName":"WJSN","counter2":0,"zodiac":"Aries","counter1":0,"chineseZodiac":"Ox","name":"Dawon","zodiacId":1,"birthDate":19970416},
{"chineseZodiacId":2,"groupName":"Dreamcatcher","counter2":0,"zodiac":"Pisces","counter1":0,"chineseZodiac":"Ox","name":"Dami","zodiacId":12,"birthDate":19970307},
{"chineseZodiacId":8,"groupName":"Kep1er","counter2":12,"zodiac":"Pisces","counter1":3,"chineseZodiac":"Goat","name":"Dayeon","zodiacId":12,"birthDate":20030302},
{"chineseZodiacId":4,"groupName":"WJSN","counter2":0,"zodiac":"Taurus","counter1":0,"chineseZodiac":"Rabbit","name":"Dayoung","zodiacId":2,"birthDate":19990514},
{"chineseZodiacId":6,"groupName":"Pixy","counter2":1,"zodiac":"Cancer","counter1":7,"chineseZodiac":"Snake","name":"Dia","zodiacId":4,"birthDate":20010716},
{"chineseZodiacId":1,"groupName":"Secret Number","counter2":0,"zodiac":"Capricorn","counter1":0,"chineseZodiac":"Rat","name":"Dita","zodiacId":10,"birthDate":19961225},
{"chineseZodiacId":7,"groupName":"cignature","counter2":0,"zodiac":"Leo","counter1":0,"chineseZodiac":"Horse","name":"Dohee","zodiacId":5,"birthDate":20020801},
{"chineseZodiacId":5,"groupName":"Purple Kiss","counter2":0,"zodiac":"Aquarius","counter1":9,"chineseZodiac":"Dragon","name":"Dosie","zodiacId":11,"birthDate":20000211},
{"chineseZodiacId":5,"groupName":"ichillin","counter2":0,"zodiac":"Scorpius","counter1":0,"chineseZodiac":"Dragon","name":"E.JI","zodiacId":8,"birthDate":20001108},
{"chineseZodiacId":3,"groupName":"Everglow","counter2":0,"zodiac":"Taurus","counter1":0,"chineseZodiac":"Tiger","name":"E:U","zodiacId":2,"birthDate":19980519},
{"chineseZodiacId":3,"groupName":"Pixy","counter2":0,"zodiac":"Aries","counter1":0,"chineseZodiac":"Tiger","name":"Ella","zodiacId":1,"birthDate":19980326},
{"chineseZodiacId":8,"groupName":"ily:1","counter2":0,"zodiac":"Taurus","counter1":1,"chineseZodiac":"Goat","name":"Elva","zodiacId":2,"birthDate":20030505},
{"chineseZodiacId":12,"groupName":"soloist","counter2":1,"zodiac":"Libra","counter1":1,"chineseZodiac":"Pig","name":"Eunbi","zodiacId":7,"birthDate":19950927},
{"chineseZodiacId":11,"groupName":"LE SSERAFIM","counter2":0,"zodiac":"Scorpius","counter1":2,"chineseZodiac":"Dog","name":"Eunchae","zodiacId":8,"birthDate":20061110},
{"chineseZodiacId":2,"groupName":"VIVIZ","counter2":0,"zodiac":"Gemini","counter1":4,"chineseZodiac":"Ox","name":"Eunha","zodiacId":3,"birthDate":19970530},
{"chineseZodiacId":9,"groupName":"Brave Girls","counter2":0,"zodiac":"Cancer","counter1":0,"chineseZodiac":"Monkey","name":"Eunji","zodiacId":4,"birthDate":19920719},
{"chineseZodiacId":7,"groupName":"Dream Note","counter2":0,"zodiac":"Pisces","counter1":1,"chineseZodiac":"Horse","name":"Eunjo","zodiacId":12,"birthDate":20020307},
{"chineseZodiacId":3,"groupName":"WJSN","counter2":0,"zodiac":"Gemini","counter1":0,"chineseZodiac":"Tiger","name":"Eunseo","zodiacId":3,"birthDate":19980527},
{"chineseZodiacId":12,"groupName":"WJSN","counter2":0,"zodiac":"Scorpius","counter1":0,"chineseZodiac":"Pig","name":"Exy","zodiacId":8,"birthDate":19951106},
{"chineseZodiacId":7,"groupName":"IVE","counter2":0,"zodiac":"Libra","counter1":1,"chineseZodiac":"Horse","name":"Gaeul","zodiacId":7,"birthDate":20020924},
{"chineseZodiacId":4,"groupName":"Dreamcatcher","counter2":4,"zodiac":"Aquarius","counter1":1,"chineseZodiac":"Rabbit","name":"Gahyeon","zodiacId":11,"birthDate":19990203},
{"chineseZodiacId":10,"groupName":"LE SSERAFIM","counter2":1,"zodiac":"Scorpius","counter1":1,"chineseZodiac":"Rooster","name":"Garam","zodiacId":8,"birthDate":20051116},
{"chineseZodiacId":5,"groupName":"aespa","counter2":0,"zodiac":"Scorpius","counter1":0,"chineseZodiac":"Dragon","name":"Giselle","zodiacId":8,"birthDate":20001030},
{"chineseZodiacId":4,"groupName":"Purple Kiss","counter2":0,"zodiac":"Virgo","counter1":2,"chineseZodiac":"Rabbit","name":"Goeun","zodiacId":6,"birthDate":19990903},
{"chineseZodiacId":5,"groupName":"LOONA","counter2":0,"zodiac":"Scorpius","counter1":1,"chineseZodiac":"Dragon","name":"Gowon","zodiacId":8,"birthDate":20001119},
{"chineseZodiacId":2,"groupName":"fromis_9","counter2":0,"zodiac":"Capricorn","counter1":0,"chineseZodiac":"Ox","name":"Gyuri","zodiacId":10,"birthDate":19971227},
{"chineseZodiacId":8,"groupName":"NMIXX","counter2":0,"zodiac":"Pisces","counter1":2,"chineseZodiac":"Goat","name":"Haewon","zodiacId":12,"birthDate":20030225},
{"chineseZodiacId":1,"groupName":"Cherry Bullet","counter2":0,"zodiac":"Capricorn","counter1":0,"chineseZodiac":"Rat","name":"Haeyoon","zodiacId":10,"birthDate":19960110},
{"chineseZodiacId":5,"groupName":"ily:1","counter2":0,"zodiac":"Pisces","counter1":0,"chineseZodiac":"Dragon","name":"Hana","zodiacId":12,"birthDate":20000227},
{"chineseZodiacId":1,"groupName":"Dreamcatcher","counter2":4,"zodiac":"Aries","counter1":4,"chineseZodiac":"Rat","name":"Handong","zodiacId":1,"birthDate":19960326},
{"chineseZodiacId":6,"groupName":"Billlie","counter2":2,"zodiac":"Capricorn","counter1":16,"chineseZodiac":"Snake","name":"Haram","zodiacId":10,"birthDate":20010113},
{"chineseZodiacId":11,"groupName":"Billlie","counter2":0,"zodiac":"Aquarius","counter1":1,"chineseZodiac":"Dog","name":"Haruna","zodiacId":11,"birthDate":20060130},
{"chineseZodiacId":2,"groupName":"LOONA","counter2":0,"zodiac":"Leo","counter1":4,"chineseZodiac":"Ox","name":"Haseul","zodiacId":5,"birthDate":19970818},
{"chineseZodiacId":2,"groupName":"fromis_9","counter2":0,"zodiac":"Libra","counter1":0,"chineseZodiac":"Ox","name":"Hayoung","zodiacId":7,"birthDate":19970929},
{"chineseZodiacId":5,"groupName":"LOONA","counter2":3,"zodiac":"Libra","counter1":6,"chineseZodiac":"Dragon","name":"Heejin","zodiacId":7,"birthDate":20001019},
{"chineseZodiacId":9,"groupName":"Kep1er","counter2":0,"zodiac":"Pisces","counter1":1,"chineseZodiac":"Monkey","name":"Hikaru","zodiacId":12,"birthDate":20040312},
{"chineseZodiacId":8,"groupName":"Lightsum","counter2":0,"zodiac":"Aries","counter1":1,"chineseZodiac":"Goat","name":"Hina","zodiacId":1,"birthDate":20030407},
{"chineseZodiacId":10,"groupName":"Lightsum","counter2":0,"zodiac":"Leo","counter1":0,"chineseZodiac":"Rooster","name":"Huiyeon","zodiacId":5,"birthDate":20050801},
{"chineseZodiacId":1,"groupName":"Momoland","counter2":0,"zodiac":"Capricorn","counter1":0,"chineseZodiac":"Rat","name":"Hyebin","zodiacId":10,"birthDate":19960112},
{"chineseZodiacId":8,"groupName":"CLASS:y","counter2":0,"zodiac":"Sagittarius","counter1":2,"chineseZodiac":"Goat","name":"Hyeju","zodiacId":9,"birthDate":20031209},
{"chineseZodiacId":4,"groupName":"soloist","counter2":1,"zodiac":"Cancer","counter1":1,"chineseZodiac":"Rabbit","name":"Hyewon","zodiacId":4,"birthDate":19990705},
{"chineseZodiacId":11,"groupName":"Oh My Girl","counter2":2,"zodiac":"Leo","counter1":4,"chineseZodiac":"Dog","name":"Hyojung","zodiacId":5,"birthDate":19940728},
{"chineseZodiacId":9,"groupName":"TRI.BE","counter2":9,"zodiac":"Gemini","counter1":7,"chineseZodiac":"Monkey","name":"Hyunbin","zodiacId":3,"birthDate":20040526},
{"chineseZodiacId":5,"groupName":"LOONA","counter2":2,"zodiac":"Scorpius","counter1":1,"chineseZodiac":"Dragon","name":"Hyunjin","zodiacId":8,"birthDate":20001115},
{"chineseZodiacId":6,"groupName":"CLASS:y","counter2":0,"zodiac":"Cancer","counter1":1,"chineseZodiac":"Snake","name":"Hyungseo","zodiacId":4,"birthDate":20010625},
{"chineseZodiacId":6,"groupName":"Majors","counter2":0,"zodiac":"Aquarius","counter1":0,"chineseZodiac":"Snake","name":"Ida","zodiacId":11,"birthDate":20010212},
{"chineseZodiacId":7,"groupName":"Purple Kiss","counter2":0,"zodiac":"Taurus","counter1":1,"chineseZodiac":"Horse","name":"Ireh","zodiacId":2,"birthDate":20020430},
{"chineseZodiacId":7,"groupName":"Stayc","counter2":8,"zodiac":"Aquarius","counter1":5,"chineseZodiac":"Horse","name":"ISA","zodiacId":11,"birthDate":20020123},
{"chineseZodiacId":9,"groupName":"Stayc","counter2":2,"zodiac":"Sagittarius","counter1":6,"chineseZodiac":"Monkey","name":"J","zodiacId":9,"birthDate":20041209},
{"chineseZodiacId":6,"groupName":"ichillin","counter2":0,"zodiac":"Scorpius","counter1":2,"chineseZodiac":"Snake","name":"Jackie","zodiacId":8,"birthDate":20011117},
{"chineseZodiacId":9,"groupName":"Weeekly","counter2":0,"zodiac":"Pisces","counter1":2,"chineseZodiac":"Monkey","name":"Jaehee","zodiacId":12,"birthDate":20040318},
{"chineseZodiacId":2,"groupName":"Momoland","counter2":0,"zodiac":"Sagittarius","counter1":0,"chineseZodiac":"Ox","name":"Jane","zodiacId":9,"birthDate":19971220},
{"chineseZodiacId":4,"groupName":"cignature","counter2":1,"zodiac":"Aries","counter1":1,"chineseZodiac":"Rabbit","name":"Jeewon","zodiacId":1,"birthDate":19990401},
{"chineseZodiacId":1,"groupName":"Blackpink","counter2":0,"zodiac":"Capricorn","counter1":0,"chineseZodiac":"Rat","name":"Jennie","zodiacId":10,"birthDate":19960116},
{"chineseZodiacId":1,"groupName":"Twice","counter2":0,"zodiac":"Scorpius","counter1":0,"chineseZodiac":"Rat","name":"Jeongyeon","zodiacId":8,"birthDate":19961101},
{"chineseZodiacId":11,"groupName":"TRI.BE","counter2":0,"zodiac":"Leo","counter1":0,"chineseZodiac":"Dog","name":"Jia","zodiacId":5,"birthDate":20060730},
{"chineseZodiacId":11,"groupName":"Lightsum","counter2":0,"zodiac":"Scorpius","counter1":0,"chineseZodiac":"Dog","name":"Jian","zodiacId":8,"birthDate":20061104},
{"chineseZodiacId":2,"groupName":"Purple Kiss","counter2":0,"zodiac":"Virgo","counter1":2,"chineseZodiac":"Ox","name":"Jieun","zodiacId":6,"birthDate":19970904},
{"chineseZodiacId":9,"groupName":"Weeekly","counter2":5,"zodiac":"Cancer","counter1":1,"chineseZodiac":"Monkey","name":"Jihan","zodiacId":4,"birthDate":20040712},
{"chineseZodiacId":8,"groupName":"fromis_9","counter2":1,"zodiac":"Aries","counter1":3,"chineseZodiac":"Goat","name":"Jiheon","zodiacId":1,"birthDate":20030417},
{"chineseZodiacId":2,"groupName":"Oh My Girl","counter2":1,"zodiac":"Aries","counter1":0,"chineseZodiac":"Ox","name":"Jiho","zodiacId":1,"birthDate":19970404},
{"chineseZodiacId":2,"groupName":"Twice","counter2":1,"zodiac":"Aquarius","counter1":0,"chineseZodiac":"Ox","name":"Jihyo","zodiacId":11,"birthDate":19970201},
{"chineseZodiacId":12,"groupName":"CLASS:y","counter2":0,"zodiac":"Leo","counter1":4,"chineseZodiac":"Pig","name":"Jimin","zodiacId":5,"birthDate":20070725},
{"chineseZodiacId":8,"groupName":"TRI.BE","counter2":1,"zodiac":"Scorpius","counter1":1,"chineseZodiac":"Goat","name":"Jinha","zodiacId":8,"birthDate":20031121},
{"chineseZodiacId":9,"groupName":"NMIXX","counter2":0,"zodiac":"Aries","counter1":3,"chineseZodiac":"Monkey","name":"Jinni","zodiacId":1,"birthDate":20040416},
{"chineseZodiacId":3,"groupName":"Secret Number","counter2":2,"zodiac":"Aquarius","counter1":4,"chineseZodiac":"Tiger","name":"Jinny","zodiacId":11,"birthDate":19980120},
{"chineseZodiacId":2,"groupName":"LOONA","counter2":0,"zodiac":"Gemini","counter1":2,"chineseZodiac":"Ox","name":"Jinsoul","zodiacId":3,"birthDate":19970613},
{"chineseZodiacId":12,"groupName":"Blackpink","counter2":0,"zodiac":"Capricorn","counter1":2,"chineseZodiac":"Pig","name":"Jisoo","zodiacId":10,"birthDate":19950103},
{"chineseZodiacId":3,"groupName":"fromis_9","counter2":0,"zodiac":"Sagittarius","counter1":1,"chineseZodiac":"Tiger","name":"Jisun","zodiacId":9,"birthDate":19981122},
{"chineseZodiacId":11,"groupName":"Dreamcatcher","counter2":1,"zodiac":"Taurus","counter1":4,"chineseZodiac":"Dog","name":"Jiu","zodiacId":2,"birthDate":19940517},
{"chineseZodiacId":5,"groupName":"Cherry Bullet","counter2":0,"zodiac":"Virgo","counter1":0,"chineseZodiac":"Dragon","name":"Jiwon","zodiacId":6,"birthDate":20000904},
{"chineseZodiacId":3,"groupName":"fromis_9","counter2":0,"zodiac":"Pisces","counter1":0,"chineseZodiac":"Tiger","name":"Jiwon","zodiacId":12,"birthDate":19980320},
{"chineseZodiacId":10,"groupName":"NMIXX","counter2":0,"zodiac":"Aries","counter1":3,"chineseZodiac":"Rooster","name":"Jiwoo","zodiacId":1,"birthDate":20050413},
{"chineseZodiacId":4,"groupName":"Momoland","counter2":1,"zodiac":"Leo","counter1":1,"chineseZodiac":"Rabbit","name":"Jooe","zodiacId":5,"birthDate":19990818},
{"chineseZodiacId":7,"groupName":"ichillin","counter2":0,"zodiac":"Gemini","counter1":0,"chineseZodiac":"Horse","name":"Joonie","zodiacId":3,"birthDate":20020524},
{"chineseZodiacId":9,"groupName":"Lightsum","counter2":0,"zodiac":"Aries","counter1":2,"chineseZodiac":"Monkey","name":"Juhyeon","zodiacId":1,"birthDate":20040408},
{"chineseZodiacId":2,"groupName":"Rocket Punch","counter2":1,"zodiac":"Libra","counter1":2,"chineseZodiac":"Ox","name":"Juri","zodiacId":7,"birthDate":19971003},
{"chineseZodiacId":5,"groupName":"aespa","counter2":2,"zodiac":"Aries","counter1":0,"chineseZodiac":"Dragon","name":"Karina","zodiacId":1,"birthDate":20000411},
{"chineseZodiacId":8,"groupName":"LE SSERAFIM","counter2":1,"zodiac":"Leo","counter1":1,"chineseZodiac":"Goat","name":"Kazuha","zodiacId":5,"birthDate":20030809},
{"chineseZodiacId":7,"groupName":"TRI.BE","counter2":0,"zodiac":"Capricorn","counter1":0,"chineseZodiac":"Horse","name":"Kelly","zodiacId":10,"birthDate":20020116},
{"chineseZodiacId":4,"groupName":"LOONA","counter2":0,"zodiac":"Aquarius","counter1":3,"chineseZodiac":"Rabbit","name":"KimLip","zodiacId":11,"birthDate":19990210},
{"chineseZodiacId":11,"groupName":"NMIXX","counter2":1,"zodiac":"Gemini","counter1":0,"chineseZodiac":"Dog","name":"Kyujin","zodiacId":3,"birthDate":20060526},
{"chineseZodiacId":5,"groupName":"Dream Note","counter2":0,"zodiac":"Leo","counter1":1,"chineseZodiac":"Dragon","name":"Lara","zodiacId":5,"birthDate":20000809},
{"chineseZodiacId":12,"groupName":"Secret Number","counter2":0,"zodiac":"Leo","counter1":0,"chineseZodiac":"Pig","name":"Lea","zodiacId":5,"birthDate":19950812},
{"chineseZodiacId":12,"groupName":"IVE","counter2":1,"zodiac":"Pisces","counter1":6,"chineseZodiac":"Pig","name":"Leeseo","zodiacId":12,"birthDate":20070221},
{"chineseZodiacId":5,"groupName":"ITZY","counter2":2,"zodiac":"Cancer","counter1":1,"chineseZodiac":"Dragon","name":"Lia","zodiacId":4,"birthDate":20000721},
{"chineseZodiacId":7,"groupName":"NMIXX","counter2":0,"zodiac":"Libra","counter1":0,"chineseZodiac":"Horse","name":"Lily","zodiacId":7,"birthDate":20021017},
{"chineseZodiacId":2,"groupName":"Blackpink","counter2":0,"zodiac":"Aries","counter1":0,"chineseZodiac":"Ox","name":"Lisa","zodiacId":1,"birthDate":19970327},
{"chineseZodiacId":9,"groupName":"IVE","counter2":3,"zodiac":"Scorpius","counter1":0,"chineseZodiac":"Monkey","name":"Liz","zodiacId":8,"birthDate":20041121},
{"chineseZodiacId":6,"groupName":"Pixy","counter2":1,"zodiac":"Pisces","counter1":1,"chineseZodiac":"Snake","name":"Lola","zodiacId":12,"birthDate":20010222},
{"chineseZodiacId":9,"groupName":"woo!ah!","counter2":0,"zodiac":"Aries","counter1":0,"chineseZodiac":"Monkey","name":"Lucy","zodiacId":1,"birthDate":20040409},
{"chineseZodiacId":2,"groupName":"WJSN","counter2":0,"zodiac":"Pisces","counter1":0,"chineseZodiac":"Ox","name":"Luda","zodiacId":12,"birthDate":19970306},
{"chineseZodiacId":4,"groupName":"Kep1er","counter2":0,"zodiac":"Sagittarius","counter1":0,"chineseZodiac":"Rabbit","name":"Mashiro","zodiacId":9,"birthDate":19991216},
{"chineseZodiacId":9,"groupName":"Cherry Bullet","counter2":0,"zodiac":"Scorpius","counter1":0,"chineseZodiac":"Monkey","name":"May","zodiacId":8,"birthDate":20041116},
{"chineseZodiacId":5,"groupName":"Everglow","counter2":0,"zodiac":"Capricorn","counter1":0,"chineseZodiac":"Dragon","name":"Mia","zodiacId":10,"birthDate":20000113},
{"chineseZodiacId":12,"groupName":"Oh My Girl","counter2":0,"zodiac":"Taurus","counter1":0,"chineseZodiac":"Pig","name":"Mimi","zodiacId":2,"birthDate":19950501},
{"chineseZodiacId":2,"groupName":"Twice","counter2":0,"zodiac":"Aries","counter1":0,"chineseZodiac":"Ox","name":"Mina","zodiacId":1,"birthDate":19970324},
{"chineseZodiacId":4,"groupName":"Secret Number","counter2":0,"zodiac":"Aries","counter1":0,"chineseZodiac":"Rabbit","name":"Minji","zodiacId":1,"birthDate":19990331},
{"chineseZodiacId":6,"groupName":"soloist","counter2":0,"zodiac":"Aquarius","counter1":2,"chineseZodiac":"Snake","name":"Minju","zodiacId":11,"birthDate":20010205},
{"chineseZodiacId":2,"groupName":"(g)i-dle","counter2":0,"zodiac":"Scorpius","counter1":1,"chineseZodiac":"Ox","name":"Minnie","zodiacId":8,"birthDate":19971023},
{"chineseZodiacId":9,"groupName":"woo!ah!","counter2":0,"zodiac":"Leo","counter1":1,"chineseZodiac":"Monkey","name":"Minseo","zodiacId":5,"birthDate":20040812},
{"chineseZodiacId":7,"groupName":"Brave Girls","counter2":0,"zodiac":"Virgo","counter1":0,"chineseZodiac":"Horse","name":"Minyoung","zodiacId":6,"birthDate":19900912},
{"chineseZodiacId":11,"groupName":"TRI.BE","counter2":1,"zodiac":"Aries","counter1":1,"chineseZodiac":"Dog","name":"Mire","zodiacId":1,"birthDate":20060326},
{"chineseZodiacId":5,"groupName":"Dream Note","counter2":1,"zodiac":"Scorpius","counter1":5,"chineseZodiac":"Dragon","name":"Miso","zodiacId":8,"birthDate":20001025},
{"chineseZodiacId":2,"groupName":"(g)i-dle","counter2":6,"zodiac":"Aquarius","counter1":7,"chineseZodiac":"Ox","name":"Miyeon","zodiacId":11,"birthDate":19970131},
{"chineseZodiacId":1,"groupName":"Twice","counter2":2,"zodiac":"Scorpius","counter1":0,"chineseZodiac":"Rat","name":"Momo","zodiacId":8,"birthDate":19961109},
{"chineseZodiacId":7,"groupName":"Weeekly","counter2":4,"zodiac":"Taurus","counter1":2,"chineseZodiac":"Horse","name":"Monday","zodiacId":2,"birthDate":20020510},
{"chineseZodiacId":4,"groupName":"Billlie","counter2":0,"zodiac":"Virgo","counter1":2,"chineseZodiac":"Rabbit","name":"Moon Sua","zodiacId":6,"birthDate":19990909},
{"chineseZodiacId":5,"groupName":"fromis_9","counter2":0,"zodiac":"Gemini","counter1":0,"chineseZodiac":"Dragon","name":"Nakyung","zodiacId":3,"birthDate":20000601},
{"chineseZodiacId":6,"groupName":"woo!ah!","counter2":2,"zodiac":"Pisces","counter1":2,"chineseZodiac":"Snake","name":"Nana","zodiacId":12,"birthDate":20010309},
{"chineseZodiacId":5,"groupName":"Momoland","counter2":2,"zodiac":"Aries","counter1":2,"chineseZodiac":"Dragon","name":"Nancy","zodiacId":1,"birthDate":20000413},
{"chineseZodiacId":12,"groupName":"Twice","counter2":0,"zodiac":"Virgo","counter1":0,"chineseZodiac":"Pig","name":"Nayeon","zodiacId":6,"birthDate":19950922},
{"chineseZodiacId":7,"groupName":"Lightsum","counter2":0,"zodiac":"Sagittarius","counter1":2,"chineseZodiac":"Horse","name":"Nayoung","zodiacId":9,"birthDate":20021130},
{"chineseZodiacId":7,"groupName":"ily:1","counter2":0,"zodiac":"Leo","counter1":0,"chineseZodiac":"Horse","name":"Nayu","zodiacId":5,"birthDate":20020723},
{"chineseZodiacId":3,"groupName":"Momoland","counter2":0,"zodiac":"Leo","counter1":0,"chineseZodiac":"Tiger","name":"Nayun","zodiacId":5,"birthDate":19980731},
{"chineseZodiacId":7,"groupName":"aespa","counter2":0,"zodiac":"Scorpius","counter1":2,"chineseZodiac":"Horse","name":"Ning Ning","zodiacId":8,"birthDate":20021023},
{"chineseZodiacId":6,"groupName":"LOONA","counter2":0,"zodiac":"Scorpius","counter1":0,"chineseZodiac":"Snake","name":"Olivia Hye","zodiacId":8,"birthDate":20011113},
{"chineseZodiacId":5,"groupName":"Everglow","counter2":0,"zodiac":"Taurus","counter1":0,"chineseZodiac":"Dragon","name":"Onda","zodiacId":2,"birthDate":20000518},
{"chineseZodiacId":9,"groupName":"IVE","counter2":0,"zodiac":"Aquarius","counter1":4,"chineseZodiac":"Monkey","name":"Rei","zodiacId":11,"birthDate":20040203},
{"chineseZodiacId":6,"groupName":"Cherry Bullet","counter2":0,"zodiac":"Taurus","counter1":0,"chineseZodiac":"Snake","name":"Remi","zodiacId":2,"birthDate":20010426},
{"chineseZodiacId":7,"groupName":"ily:1","counter2":0,"zodiac":"Cancer","counter1":1,"chineseZodiac":"Horse","name":"Ririka","zodiacId":4,"birthDate":20020702},
{"chineseZodiacId":12,"groupName":"CLASS:y","counter2":0,"zodiac":"Capricorn","counter1":1,"chineseZodiac":"Pig","name":"Riwon","zodiacId":10,"birthDate":20070111},
{"chineseZodiacId":7,"groupName":"ily:1","counter2":9,"zodiac":"Gemini","counter1":3,"chineseZodiac":"Horse","name":"Rona","zodiacId":3,"birthDate":20020605},
{"chineseZodiacId":2,"groupName":"Blackpink","counter2":1,"zodiac":"Aquarius","counter1":0,"chineseZodiac":"Ox","name":"Rose","zodiacId":11,"birthDate":19970211},
{"chineseZodiacId":6,"groupName":"ITZY","counter2":0,"zodiac":"Aries","counter1":0,"chineseZodiac":"Snake","name":"Ryujin","zodiacId":1,"birthDate":20010417},
{"chineseZodiacId":2,"groupName":"fromis_9","counter2":2,"zodiac":"Capricorn","counter1":0,"chineseZodiac":"Ox","name":"Saerom","zodiacId":10,"birthDate":19970107},
{"chineseZodiacId":3,"groupName":"LE SSERAFIM","counter2":1,"zodiac":"Pisces","counter1":0,"chineseZodiac":"Tiger","name":"Sakura","zodiacId":12,"birthDate":19980319},
{"chineseZodiacId":1,"groupName":"Twice","counter2":3,"zodiac":"Capricorn","counter1":3,"chineseZodiac":"Rat","name":"Sana","zodiacId":10,"birthDate":19961229},
{"chineseZodiacId":7,"groupName":"Lightsum","counter2":1,"zodiac":"Virgo","counter1":6,"chineseZodiac":"Horse","name":"Sangah","zodiacId":6,"birthDate":20020904},
{"chineseZodiacId":6,"groupName":"Pixy","counter2":0,"zodiac":"Pisces","counter1":0,"chineseZodiac":"Snake","name":"Satbyeol","zodiacId":12,"birthDate":20010227},
{"chineseZodiacId":8,"groupName":"Stayc","counter2":0,"zodiac":"Gemini","counter1":1,"chineseZodiac":"Goat","name":"Seeun","zodiacId":3,"birthDate":20030614},
{"chineseZodiacId":5,"groupName":"cignature","counter2":0,"zodiac":"Gemini","counter1":0,"chineseZodiac":"Dragon","name":"Seline","zodiacId":3,"birthDate":20000620},
{"chineseZodiacId":7,"groupName":"cignature","counter2":0,"zodiac":"Aries","counter1":0,"chineseZodiac":"Horse","name":"Semi","zodiacId":1,"birthDate":20020410},
{"chineseZodiacId":11,"groupName":"WJSN","counter2":0,"zodiac":"Capricorn","counter1":0,"chineseZodiac":"Dog","name":"Seola","zodiacId":10,"birthDate":19941224},
{"chineseZodiacId":1,"groupName":"CLASS:y","counter2":0,"zodiac":"Pisces","counter1":0,"chineseZodiac":"Rat","name":"Seonyu","zodiacId":12,"birthDate":20080320},
{"chineseZodiacId":5,"groupName":"fromis_9","counter2":0,"zodiac":"Aquarius","counter1":0,"chineseZodiac":"Dragon","name":"Seoyeon","zodiacId":11,"birthDate":20000122},
{"chineseZodiacId":1,"groupName":"Oh My Girl","counter2":0,"zodiac":"Aquarius","counter1":0,"chineseZodiac":"Rat","name":"Seunghee","zodiacId":11,"birthDate":19960125},
{"chineseZodiacId":8,"groupName":"Billlie","counter2":3,"zodiac":"Aquarius","counter1":5,"chineseZodiac":"Goat","name":"Sheon","zodiacId":11,"birthDate":20030128},
{"chineseZodiacId":9,"groupName":"Majors","counter2":0,"zodiac":"Pisces","counter1":0,"chineseZodiac":"Monkey","name":"Shinye","zodiacId":12,"birthDate":20040307},
{"chineseZodiacId":5,"groupName":"(g)i-dle","counter2":0,"zodiac":"Capricorn","counter1":3,"chineseZodiac":"Dragon","name":"Shuhua","zodiacId":10,"birthDate":20000106},
{"chineseZodiacId":6,"groupName":"Stayc","counter2":2,"zodiac":"Leo","counter1":0,"chineseZodiac":"Snake","name":"Sieun","zodiacId":5,"birthDate":20010801},
{"chineseZodiacId":4,"groupName":"Everglow","counter2":0,"zodiac":"Leo","counter1":2,"chineseZodiac":"Rabbit","name":"Sihyeon","zodiacId":5,"birthDate":19990805},
{"chineseZodiacId":3,"groupName":"VIVIZ","counter2":5,"zodiac":"Gemini","counter1":13,"chineseZodiac":"Tiger","name":"SinB","zodiacId":3,"birthDate":19980603},
{"chineseZodiacId":12,"groupName":"Dreamcatcher","counter2":0,"zodiac":"Libra","counter1":0,"chineseZodiac":"Pig","name":"Siyeon","zodiacId":7,"birthDate":19951001},
{"chineseZodiacId":10,"groupName":"Billlie","counter2":2,"zodiac":"Aquarius","counter1":0,"chineseZodiac":"Rooster","name":"Siyoon","zodiacId":11,"birthDate":20050216},
{"chineseZodiacId":10,"groupName":"TRI.BE","counter2":0,"zodiac":"Sagittarius","counter1":0,"chineseZodiac":"Rooster","name":"Soeun","zodiacId":9,"birthDate":20051210},
{"chineseZodiacId":7,"groupName":"Weeekly","counter2":5,"zodiac":"Scorpius","counter1":10,"chineseZodiac":"Horse","name":"Soeun","zodiacId":8,"birthDate":20021026},
{"chineseZodiacId":9,"groupName":"ichillin","counter2":0,"zodiac":"Capricorn","counter1":1,"chineseZodiac":"Monkey","name":"Sohee","zodiacId":10,"birthDate":20040101},
{"chineseZodiacId":8,"groupName":"Rocket Punch","counter2":0,"zodiac":"Leo","counter1":0,"chineseZodiac":"Goat","name":"Sohee","zodiacId":5,"birthDate":20030814},
{"chineseZodiacId":2,"groupName":"TRI.BE","counter2":0,"zodiac":"Aries","counter1":0,"chineseZodiac":"Ox","name":"Songsun","zodiacId":1,"birthDate":19970322},
{"chineseZodiacId":1,"groupName":"WJSN","counter2":0,"zodiac":"Virgo","counter1":0,"chineseZodiac":"Rat","name":"Soobin","zodiacId":6,"birthDate":19960914},
{"chineseZodiacId":4,"groupName":"Secret Number","counter2":0,"zodiac":"Scorpius","counter1":2,"chineseZodiac":"Rabbit","name":"Soodam","zodiacId":8,"birthDate":19991109},
{"chineseZodiacId":6,"groupName":"Weeekly","counter2":0,"zodiac":"Sagittarius","counter1":2,"chineseZodiac":"Snake","name":"Soojin","zodiacId":9,"birthDate":20011212},
{"chineseZodiacId":8,"groupName":"woo!ah!","counter2":0,"zodiac":"Virgo","counter1":0,"chineseZodiac":"Goat","name":"Sora","zodiacId":6,"birthDate":20030830},
{"chineseZodiacId":12,"groupName":"Gfriend","counter2":2,"zodiac":"Sagittarius","counter1":0,"chineseZodiac":"Pig","name":"Sowon","zodiacId":9,"birthDate":19951207},
{"chineseZodiacId":3,"groupName":"(g)i-dle","counter2":0,"zodiac":"Virgo","counter1":1,"chineseZodiac":"Tiger","name":"Soyeon","zodiacId":6,"birthDate":19980826},
{"chineseZodiacId":11,"groupName":"Dreamcatcher","counter2":1,"zodiac":"Leo","counter1":0,"chineseZodiac":"Dog","name":"Sua","zodiacId":5,"birthDate":19940810},
{"chineseZodiacId":8,"groupName":"Pixy","counter2":0,"zodiac":"Pisces","counter1":1,"chineseZodiac":"Goat","name":"Sua","zodiacId":12,"birthDate":20030224},
{"chineseZodiacId":5,"groupName":"Billlie","counter2":1,"zodiac":"Capricorn","counter1":3,"chineseZodiac":"Dragon","name":"Suhyeon","zodiacId":10,"birthDate":20000115},
{"chineseZodiacId":9,"groupName":"NMIXX","counter2":0,"zodiac":"Aquarius","counter1":3,"chineseZodiac":"Monkey","name":"Sullyoon","zodiacId":11,"birthDate":20040126},
{"chineseZodiacId":6,"groupName":"Dream Note","counter2":1,"zodiac":"Virgo","counter1":3,"chineseZodiac":"Snake","name":"Sumin","zodiacId":6,"birthDate":20010907},
{"chineseZodiacId":6,"groupName":"Stayc","counter2":5,"zodiac":"Pisces","counter1":6,"chineseZodiac":"Snake","name":"Sumin","zodiacId":12,"birthDate":20010313},
{"chineseZodiacId":6,"groupName":"Rocket Punch","counter2":0,"zodiac":"Pisces","counter1":2,"chineseZodiac":"Snake","name":"Suyun","zodiacId":12,"birthDate":20010317},
{"chineseZodiacId":6,"groupName":"Majors","counter2":0,"zodiac":"Gemini","counter1":0,"chineseZodiac":"Snake","name":"Suzy","zodiacId":3,"birthDate":20010603},
{"chineseZodiacId":8,"groupName":"Purple Kiss","counter2":0,"zodiac":"Cancer","counter1":1,"chineseZodiac":"Goat","name":"Swan","zodiacId":4,"birthDate":20030711},
{"chineseZodiacId":7,"groupName":"Billlie","counter2":1,"zodiac":"Virgo","counter1":2,"chineseZodiac":"Horse","name":"Tsuki","zodiacId":6,"birthDate":20020921},
{"chineseZodiacId":4,"groupName":"Twice","counter2":1,"zodiac":"Gemini","counter1":0,"chineseZodiac":"Rabbit","name":"Tzuyu","zodiacId":3,"birthDate":19990614},
{"chineseZodiacId":3,"groupName":"VIVIZ","counter2":1,"zodiac":"Leo","counter1":4,"chineseZodiac":"Tiger","name":"Umji","zodiacId":5,"birthDate":19980819},
{"chineseZodiacId":1,"groupName":"LOONA","counter2":0,"zodiac":"Sagittarius","counter1":0,"chineseZodiac":"Rat","name":"Vivi","zodiacId":9,"birthDate":19961209},
{"chineseZodiacId":6,"groupName":"aespa","counter2":0,"zodiac":"Capricorn","counter1":1,"chineseZodiac":"Snake","name":"Winter","zodiacId":10,"birthDate":20010101},
{"chineseZodiacId":9,"groupName":"IVE","counter2":7,"zodiac":"Virgo","counter1":4,"chineseZodiac":"Monkey","name":"Wonyoung","zodiacId":6,"birthDate":20040831},
{"chineseZodiacId":8,"groupName":"woo!ah!","counter2":0,"zodiac":"Aquarius","counter1":2,"chineseZodiac":"Goat","name":"Wooyeon","zodiacId":11,"birthDate":20030211},
{"chineseZodiacId":4,"groupName":"Kep1er","counter2":0,"zodiac":"Scorpius","counter1":6,"chineseZodiac":"Rabbit","name":"Xiaoting","zodiacId":8,"birthDate":19991112},
{"chineseZodiacId":5,"groupName":"ITZY","counter2":0,"zodiac":"Gemini","counter1":4,"chineseZodiac":"Dragon","name":"Yeji","zodiacId":3,"birthDate":20000526},
{"chineseZodiacId":4,"groupName":"soloist","counter2":0,"zodiac":"Libra","counter1":0,"chineseZodiac":"Rabbit","name":"Yena","zodiacId":7,"birthDate":19990929},
{"chineseZodiacId":7,"groupName":"LOONA","counter2":2,"zodiac":"Scorpius","counter1":17,"chineseZodiac":"Horse","name":"Yeojin","zodiacId":8,"birthDate":20021111},
{"chineseZodiacId":5,"groupName":"Rocket Punch","counter2":0,"zodiac":"Sagittarius","counter1":3,"chineseZodiac":"Dragon","name":"Yeonhee","zodiacId":9,"birthDate":20001206},
{"chineseZodiacId":4,"groupName":"WJSN","counter2":1,"zodiac":"Leo","counter1":0,"chineseZodiac":"Rabbit","name":"Yeonjung","zodiacId":5,"birthDate":19990803},
{"chineseZodiacId":1,"groupName":"Momoland","counter2":0,"zodiac":"Leo","counter1":0,"chineseZodiac":"Rat","name":"Yeonwoo","zodiacId":5,"birthDate":19960801},
{"chineseZodiacId":4,"groupName":"WJSN","counter2":1,"zodiac":"Capricorn","counter1":1,"chineseZodiac":"Rabbit","name":"Yeoreum","zodiacId":10,"birthDate":19990110},
{"chineseZodiacId":1,"groupName":"Gfriend","counter2":1,"zodiac":"Leo","counter1":1,"chineseZodiac":"Rat","name":"Yerin","zodiacId":5,"birthDate":19960819},
{"chineseZodiacId":10,"groupName":"Kep1er","counter2":0,"zodiac":"Leo","counter1":3,"chineseZodiac":"Rooster","name":"Yeseo","zodiacId":5,"birthDate":20050822},
{"chineseZodiacId":9,"groupName":"ichillin","counter2":0,"zodiac":"Aquarius","counter1":2,"chineseZodiac":"Monkey","name":"Yeju","zodiacId":11,"birthDate":20040201},
{"chineseZodiacId":5,"groupName":"Everglow","counter2":2,"zodiac":"Capricorn","counter1":3,"chineseZodiac":"Dragon","name":"Yiren","zodiacId":10,"birthDate":20001229},
{"chineseZodiacId":12,"groupName":"Oh My Girl","counter2":0,"zodiac":"Virgo","counter1":5,"chineseZodiac":"Pig","name":"Yooa","zodiacId":6,"birthDate":19950917},
{"chineseZodiacId":2,"groupName":"Dreamcatcher","counter2":2,"zodiac":"Capricorn","counter1":2,"chineseZodiac":"Ox","name":"Yoohyeon","zodiacId":10,"birthDate":19970107},
{"chineseZodiacId":9,"groupName":"Stayc","counter2":0,"zodiac":"Aries","counter1":11,"chineseZodiac":"Monkey","name":"Yoon","zodiacId":1,"birthDate":20040414},
{"chineseZodiacId":5,"groupName":"Dream Note","counter2":1,"zodiac":"Taurus","counter1":1,"chineseZodiac":"Dragon","name":"YOUI","zodiacId":2,"birthDate":20000424},
{"chineseZodiacId":9,"groupName":"Kep1er","counter2":0,"zodiac":"Capricorn","counter1":4,"chineseZodiac":"Monkey","name":"Youngeun","zodiacId":10,"birthDate":20041227},
{"chineseZodiacId":2,"groupName":"Oh My Girl","counter2":0,"zodiac":"Virgo","counter1":3,"chineseZodiac":"Ox","name":"Yubin","zodiacId":6,"birthDate":19970909},
{"chineseZodiacId":8,"groupName":"Brave Girls","counter2":1,"zodiac":"Taurus","counter1":0,"chineseZodiac":"Goat","name":"Yujeong","zodiacId":2,"birthDate":19910502},
{"chineseZodiacId":9,"groupName":"Lightsum","counter2":0,"zodiac":"Gemini","counter1":0,"chineseZodiac":"Monkey","name":"Yujeong","zodiacId":3,"birthDate":20040614},
{"chineseZodiacId":8,"groupName":"IVE","counter2":0,"zodiac":"Virgo","counter1":4,"chineseZodiac":"Goat","name":"Yujin","zodiacId":6,"birthDate":20030901},
{"chineseZodiacId":1,"groupName":"Kep1er","counter2":0,"zodiac":"Leo","counter1":2,"chineseZodiac":"Rat","name":"Yujin","zodiacId":5,"birthDate":19960812},
{"chineseZodiacId":2,"groupName":"Cherry Bullet","counter2":0,"zodiac":"Pisces","counter1":0,"chineseZodiac":"Ox","name":"Yuju","zodiacId":12,"birthDate":19970305},
{"chineseZodiacId":2,"groupName":"Gfriend","counter2":0,"zodiac":"Libra","counter1":1,"chineseZodiac":"Ox","name":"Yuju","zodiacId":7,"birthDate":19971004},
{"chineseZodiacId":7,"groupName":"Purple Kiss","counter2":0,"zodiac":"Scorpius","counter1":2,"chineseZodiac":"Horse","name":"Yuki","zodiacId":8,"birthDate":20021106},
{"chineseZodiacId":10,"groupName":"Brave Girls","counter2":0,"zodiac":"Aries","counter1":0,"chineseZodiac":"Rooster","name":"Yuna","zodiacId":1,"birthDate":19930406},
{"chineseZodiacId":8,"groupName":"ITZY","counter2":0,"zodiac":"Sagittarius","counter1":3,"chineseZodiac":"Goat","name":"Yuna","zodiacId":9,"birthDate":20031209},
{"chineseZodiacId":6,"groupName":"LE SSERAFIM","counter2":0,"zodiac":"Scorpius","counter1":8,"chineseZodiac":"Snake","name":"Yunjin","zodiacId":8,"birthDate":20011108},
{"chineseZodiacId":6,"groupName":"Rocket Punch","counter2":0,"zodiac":"Scorpius","counter1":4,"chineseZodiac":"Snake","name":"Yunkyoung","zodiacId":8,"birthDate":20011101},
{"chineseZodiacId":4,"groupName":"(g)i-dle","counter2":2,"zodiac":"Libra","counter1":2,"chineseZodiac":"Rabbit","name":"Yuqi","zodiacId":7,"birthDate":19990923},
{"chineseZodiacId":6,"groupName":"soloist","counter2":0,"zodiac":"Libra","counter1":1,"chineseZodiac":"Snake","name":"Yuri","zodiacId":7,"birthDate":20011022},
{"chineseZodiacId":2,"groupName":"LOONA","counter2":0,"zodiac":"Gemini","counter1":1,"chineseZodiac":"Ox","name":"Yves","zodiacId":3,"birthDate":19970524},
{"chineseZodiacId":10,"groupName":"Weeekly","counter2":2,"zodiac":"Gemini","counter1":1,"chineseZodiac":"Rooster","name":"Zoa","zodiacId":3,"birthDate":20050531},
{"chineseZodiacId":5,"groupName":"Secret Number","counter2":0,"zodiac":"Aries","counter1":0,"chineseZodiac":"Dragon","name":"Zuu","zodiacId":1,"birthDate":20000324}
]);

artist().each(function (item) {
    console.log(item.name + ' - ' + item.groupName + ' - ' + item.birthDate + ' - ' + item.counter1 + ' - ' + item.counter2);
});



artist().order("groupName").each(function (item) {
    console.log(item.name + ' - ' + item.groupName + ' - ' + item.birthDate + ' - ' + item.counter1 + ' - ' + item.counter2);
});